import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { projectLuaBridgeFacts, renderLuaBridgeOutputs } from "../packages/compiler/src/lua-bridge-output-emitter.mjs";
import { generateHeader, generateSource, validateLuaSchema } from "../scripts/generate-lua-bridge.mjs";

const schema = validateLuaSchema(
  JSON.parse(await readFile(new URL("../packages/bindings/lua-compat.json", import.meta.url), "utf8")),
);
const facts = projectLuaBridgeFacts(schema);
const legacy = new Map([
  ["defold/defold_hermes/include/defold_hermes/generated_lua_bridge.hpp", generateHeader(schema)],
  ["defold/defold_hermes/src/generated_lua_bridge.cpp", generateSource(schema)],
]);

test("Lua bridge projection retains the complete compact ABI and Lua call schema", () => {
  assert.equal(facts.modules.length, schema.modules.length);
  assert.ok(facts.modules.some((module) => module.functions.some(({ timerOperation }) => timerOperation === "delay")));
  assert.ok(
    facts.modules
      .flatMap(({ functions }) => functions)
      .some(({ parameters }) => parameters.some(({ type }) => type === "callback")),
  );
});

test("Lua bridge emitters preserve previous generated bytes", async () => {
  const rendered = renderLuaBridgeOutputs(facts);
  assert.equal(rendered.size, 2);
  for (const [path, contents] of rendered) {
    assert.equal(legacy.get(path), contents, `${path} differs from the prior renderer`);
    assert.equal(await readFile(new URL(`../${path}`, import.meta.url), "utf8"), contents, `${path} is stale`);
  }
});

test("Lua bridge facts reject unsupported argument and return domains", () => {
  const invalidParameter = structuredClone(facts);
  invalidParameter.modules[0].functions[0].parameters[0].type = "userdata";
  assert.throws(() => renderLuaBridgeOutputs(invalidParameter), /invalid parameter fact/u);

  const invalidReturn = structuredClone(facts);
  invalidReturn.modules[0].functions[0].returns = "userdata";
  assert.throws(() => renderLuaBridgeOutputs(invalidReturn), /invalid signature facts/u);
});
