// Generated by tools/generate-art.mjs. Do not edit.
// Defold tile ids are one-based, matching tilemap.setTile.
export const ARENA_ART_THEMES = [
  {
    id: "frontier",
    name: "Frontier",
    groundRoleTileIds: [
      1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 13, 11, 9, 5, 12, 10, 8, 5, 7, 6, 5,
    ],
    markRoleTileIds: [0, 14, 15, 16, 18],
    decorRoleTileIds: [0, 21, 20, 18, 22, 23, 19],
  },
  {
    id: "refinery",
    name: "Slate Refinery",
    groundRoleTileIds: [
      24, 25, 26, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 28, 28, 28, 28, 36, 34, 32, 28, 35, 33, 31, 28, 30, 29,
      28,
    ],
    markRoleTileIds: [0, 37, 38, 39, 41],
    decorRoleTileIds: [0, 44, 43, 41, 45, 46, 42],
  },
  {
    id: "canyon",
    name: "Ember Canyon",
    groundRoleTileIds: [
      47, 48, 49, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 51, 51, 51, 51, 59, 57, 55, 51, 58, 56, 54, 51, 53, 52,
      51,
    ],
    markRoleTileIds: [0, 60, 61, 62, 64],
    decorRoleTileIds: [0, 67, 66, 64, 68, 69, 65],
  },
] as const;
export type ArenaArtThemeId = (typeof ARENA_ART_THEMES)[number]["id"];

export function arenaGroundTileId(themeIndex: number, role: number): number {
  return ARENA_ART_THEMES[themeIndex]?.groundRoleTileIds[role] ?? 0;
}

export function arenaDecorTileId(themeIndex: number, role: number): number {
  return ARENA_ART_THEMES[themeIndex]?.decorRoleTileIds[role] ?? 0;
}

export function arenaMarkTileId(themeIndex: number, role: number): number {
  return ARENA_ART_THEMES[themeIndex]?.markRoleTileIds[role] ?? 0;
}
