// Generated by scripts/generate-script-universal-value-bindings.mjs. Do not edit.
#include <defold_hermes/generated_script_universal_value_capi.h>

#include <defold_hermes/generated_script_universal_value_bindings.hpp>
#include <defold_hermes/script_bridge_capi.hpp>
#include <defold_hermes/script_matrix4_arena.hpp>
#include <defold_hermes/script_url_arena.hpp>

#include <array>
#include <cmath>
#include <cstdio>
#include <cstring>

namespace {
using namespace defold_hermes;

DehermScriptUniversalStatus fail(
    DehermScriptUniversalStatus status, char* error, uint32_t capacity,
    const char* message) noexcept {
  if (error && capacity) std::snprintf(error, capacity, "%s", message);
  return status;
}

bool span(uint32_t offset, uint32_t length, uint32_t capacity) noexcept {
  return offset <= capacity && length <= capacity - offset;
}

bool releasable(const ScriptValue& value) noexcept {
  return value.tag == ScriptValueTag::kHandle &&
      (value.handleKind == ScriptHandleKind::kGuiNode ||
       value.handleKind == ScriptHandleKind::kLuaUserdata ||
       value.handleKind == ScriptHandleKind::kLuaSemanticHandle);
}

void releaseGraph(const ScriptValue& value, uint32_t depth) noexcept {
  if (releasable(value)) {
    releaseScriptHandle(value.handleKind, value.length, value.payload);
    return;
  }
  if (value.tag != ScriptValueTag::kTable || !value.data ||
      depth >= DEHERM_SCRIPT_UNIVERSAL_MAX_DEPTH) return;
  const auto* entries = static_cast<const ScriptTableEntry*>(value.data);
  for (uint32_t index = 0; index < value.length; ++index) {
    releaseGraph(entries[index].key, depth + 1);
    releaseGraph(entries[index].value, depth + 1);
  }
}

struct DecodeContext {
  const DehermScriptUniversalValue* values = nullptr;
  uint32_t valueCount = 0;
  const DehermScriptUniversalEntry* entries = nullptr;
  uint32_t entryCount = 0;
  const char* strings = nullptr;
  uint32_t stringBytes = 0;
  const float* floats = nullptr;
  uint32_t floatCount = 0;
  const DehermScriptUniversalUrl* urls = nullptr;
  uint32_t urlCount = 0;
  ScriptTableEntry* scratch = nullptr;
  uint32_t scratchUsed = 0;
  ScriptMatrix4Arena* matrices = nullptr;
  ScriptUrlArena<32>* urlArena = nullptr;
  char* error = nullptr;
  uint32_t errorCapacity = 0;
  DehermScriptUniversalStatus status = DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE;

  bool reject(DehermScriptUniversalStatus next, const char* message) noexcept {
    status = next;
    fail(next, error, errorCapacity, message);
    return false;
  }

  bool decode(uint32_t index, ScriptValue* output, uint32_t depth,
      const uint32_t* ancestors, uint32_t ancestorCount) noexcept {
    if (!output || index >= valueCount) return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire value index is out of range");
    if (depth > DEHERM_SCRIPT_UNIVERSAL_MAX_DEPTH) return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire value graph exceeds the depth bound");
    const auto& wire = values[index];
    *output = {};
    if (wire.tag > static_cast<uint8_t>(ScriptValueTag::kDefoldValue)) {
      return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire value tag is invalid");
    }
    output->tag = static_cast<ScriptValueTag>(wire.tag);
    switch (output->tag) {
      case ScriptValueTag::kUndefined:
      case ScriptValueTag::kNull:
        return true;
      case ScriptValueTag::kBoolean:
        if (wire.number != 0.0 && wire.number != 1.0) return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire boolean is not exact");
        output->number = wire.number;
        return true;
      case ScriptValueTag::kNumber:
        output->number = wire.number;
        return true;
      case ScriptValueTag::kString:
        if (!span(wire.data_offset, wire.length, stringBytes) || (wire.length && !strings)) {
          return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire string span is invalid");
        }
        output->length = wire.length;
        output->data = strings ? strings + wire.data_offset : nullptr;
        return true;
      case ScriptValueTag::kHandle: {
        if (wire.handle_kind < static_cast<uint8_t>(ScriptHandleKind::kHash) ||
            wire.handle_kind > static_cast<uint8_t>(ScriptHandleKind::kLuaSemanticHandle)) {
          return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire handle kind is invalid");
        }
        output->handleKind = static_cast<ScriptHandleKind>(wire.handle_kind);
        if (output->handleKind == ScriptHandleKind::kUrl) {
          if (wire.data_offset >= urlCount || !urls || !urlArena) {
            return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire URL index is invalid");
          }
          const auto& url = urls[wire.data_offset];
          if (!urlArena->store({url.socket, url.reserved, url.path, url.fragment}, output)) {
            return reject(DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED, "Universal URL scratch is exhausted");
          }
          return true;
        }
        output->reserved = wire.auxiliary;
        output->length = wire.runtime;
        output->payload = wire.payload;
        if (output->handleKind != ScriptHandleKind::kHash && wire.runtime == 0) {
          return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire retained handle has no runtime token");
        }
        return true;
      }
      case ScriptValueTag::kDefoldValue: {
        if (wire.defold_kind < static_cast<uint8_t>(ScriptDefoldValueKind::kVector3) ||
            wire.defold_kind > static_cast<uint8_t>(ScriptDefoldValueKind::kMatrix4)) {
          return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire Defold value kind is invalid");
        }
        output->defoldKind = static_cast<ScriptDefoldValueKind>(wire.defold_kind);
        if (output->defoldKind == ScriptDefoldValueKind::kMatrix4) {
          if (wire.length != 16 || !span(wire.data_offset, 16, floatCount) || !floats || !matrices ||
              !matrices->store(floats + wire.data_offset, output)) {
            return reject(DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED, "Universal Matrix4 scratch is exhausted or invalid");
          }
          return true;
        }
        const uint32_t count = output->defoldKind == ScriptDefoldValueKind::kVector3 ? 3 : 4;
        for (uint32_t lane = 0; lane < count; ++lane) output->defoldValue[lane] = wire.lanes[lane];
        return true;
      }
      case ScriptValueTag::kTable: {
        if (depth >= DEHERM_SCRIPT_UNIVERSAL_MAX_DEPTH) return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire table exceeds the depth bound");
        if (wire.auxiliary < static_cast<uint8_t>(ScriptTableKind::kSequence) ||
            wire.auxiliary > static_cast<uint8_t>(ScriptTableKind::kMap) ||
            !span(wire.data_offset, wire.length, entryCount) ||
            wire.length > DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES) {
          return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire table span or kind is invalid");
        }
        for (uint32_t ancestor = 0; ancestor < ancestorCount; ++ancestor) {
          if (ancestors[ancestor] == index) return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire value graph contains a cycle");
        }
        if (wire.length > DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES - scratchUsed) {
          return reject(DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED, "Universal input table scratch is exhausted");
        }
        const uint32_t start = scratchUsed;
        scratchUsed += wire.length;
        std::array<uint32_t, DEHERM_SCRIPT_UNIVERSAL_MAX_DEPTH> next{};
        for (uint32_t ancestor = 0; ancestor < ancestorCount; ++ancestor) next[ancestor] = ancestors[ancestor];
        next[ancestorCount] = index;
        std::array<bool, DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES> sequenceKeys{};
        for (uint32_t item = 0; item < wire.length; ++item) {
          const auto& entry = entries[wire.data_offset + item];
          if (!decode(entry.key_index, &scratch[start + item].key, depth + 1, next.data(), ancestorCount + 1) ||
              !decode(entry.value_index, &scratch[start + item].value, depth + 1, next.data(), ancestorCount + 1)) return false;
          const auto& key = scratch[start + item].key;
          if (key.tag == ScriptValueTag::kNull || key.tag == ScriptValueTag::kUndefined) {
            return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal table key cannot be null or undefined");
          }
          if (wire.auxiliary == static_cast<uint8_t>(ScriptTableKind::kRecord) && key.tag != ScriptValueTag::kString) {
            return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal record key must be a string");
          }
          if (wire.auxiliary == static_cast<uint8_t>(ScriptTableKind::kSequence)) {
            if (key.tag != ScriptValueTag::kNumber || !std::isfinite(key.number) || std::trunc(key.number) != key.number ||
                key.number < 1.0 || key.number > static_cast<double>(wire.length) || sequenceKeys[static_cast<uint32_t>(key.number - 1.0)]) {
              return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal sequence keys are not dense and unique");
            }
            sequenceKeys[static_cast<uint32_t>(key.number - 1.0)] = true;
          }
        }
        output->reserved = wire.auxiliary;
        output->length = wire.length;
        output->data = scratch + start;
        return true;
      }
      case ScriptValueTag::kCallback:
        return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal value family does not accept callbacks");
    }
    return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal wire value is unsupported");
  }
};

struct EncodeContext {
  DehermScriptUniversalValue* values = nullptr;
  uint32_t valueCapacity = 0;
  uint32_t valueUsed = 0;
  DehermScriptUniversalEntry* entries = nullptr;
  uint32_t entryCapacity = 0;
  uint32_t entryUsed = 0;
  char* strings = nullptr;
  uint32_t stringCapacity = 0;
  uint32_t stringUsed = 0;
  float* floats = nullptr;
  uint32_t floatCapacity = 0;
  uint32_t floatUsed = 0;
  DehermScriptUniversalUrl* urls = nullptr;
  uint32_t urlCapacity = 0;
  uint32_t urlUsed = 0;
  const ScriptMatrix4Arena* matrices = nullptr;
  const ScriptUrlArena<32>* urlArena = nullptr;
  char* error = nullptr;
  uint32_t errorCapacity = 0;
  DehermScriptUniversalStatus status = DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED;

  bool reject(DehermScriptUniversalStatus next, const char* message) noexcept {
    status = next;
    fail(next, error, errorCapacity, message);
    return false;
  }

  bool encode(const ScriptValue& input, uint32_t* outputIndex, uint32_t depth,
      const void* const* ancestors, uint32_t ancestorCount) noexcept {
    if (!outputIndex || valueUsed >= valueCapacity || !values) return reject(DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED, "Universal output value arena is exhausted");
    const uint32_t index = valueUsed++;
    *outputIndex = index;
    auto& wire = values[index];
    wire = {};
    wire.tag = static_cast<uint8_t>(input.tag);
    wire.handle_kind = static_cast<uint8_t>(input.handleKind);
    wire.defold_kind = static_cast<uint8_t>(input.defoldKind);
    wire.auxiliary = input.reserved;
    wire.number = input.number;
    wire.payload = input.payload;
    wire.runtime = input.length;
    for (uint32_t lane = 0; lane < 4; ++lane) wire.lanes[lane] = input.defoldValue[lane];
    switch (input.tag) {
      case ScriptValueTag::kUndefined:
      case ScriptValueTag::kNull:
      case ScriptValueTag::kBoolean:
      case ScriptValueTag::kNumber:
        return true;
      case ScriptValueTag::kString: {
        if (input.length && !input.data) return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal backend returned an invalid string");
        const char* source = static_cast<const char*>(input.data);
        if (source && strings && source >= strings && source + input.length <= strings + stringUsed) {
          wire.data_offset = static_cast<uint32_t>(source - strings);
          wire.length = input.length;
          return true;
        }
        if (input.length > stringCapacity - stringUsed || (input.length && !strings)) return reject(DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED, "Universal output string arena is exhausted");
        wire.data_offset = stringUsed;
        wire.length = input.length;
        if (input.length) std::memmove(strings + stringUsed, input.data, input.length);
        stringUsed += input.length;
        return true;
      }
      case ScriptValueTag::kHandle:
        if (input.handleKind == ScriptHandleKind::kUrl) {
          ScriptResolvedUrl url{};
          if (!urlArena || !urlArena->resolve(input, urlArena->runtimeToken(), &url)) return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal backend returned a stale URL");
          if (urlUsed >= urlCapacity || !urls) return reject(DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED, "Universal output URL arena is exhausted");
          wire.data_offset = urlUsed;
          wire.length = 1;
          wire.runtime = 0;
          urls[urlUsed++] = {url.socket, url.reserved, url.path, url.fragment};
        }
        return true;
      case ScriptValueTag::kDefoldValue:
        if (input.defoldKind == ScriptDefoldValueKind::kMatrix4) {
          const float* matrix = matrices ? matrices->resolve(input) : nullptr;
          if (!matrix) return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal backend returned a stale Matrix4");
          if (16 > floatCapacity - floatUsed || !floats) return reject(DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED, "Universal output float arena is exhausted");
          wire.data_offset = floatUsed;
          wire.length = 16;
          std::memcpy(floats + floatUsed, matrix, sizeof(float) * 16);
          floatUsed += 16;
        }
        return true;
      case ScriptValueTag::kTable: {
        if (depth >= DEHERM_SCRIPT_UNIVERSAL_MAX_DEPTH || input.length > DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES ||
            (input.length && !input.data)) return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal backend returned an invalid or over-depth table");
        for (uint32_t ancestor = 0; ancestor < ancestorCount; ++ancestor) {
          if (ancestors[ancestor] == input.data) return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal backend returned a cyclic table");
        }
        if (input.length > entryCapacity - entryUsed || (input.length && !entries)) return reject(DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED, "Universal output entry arena is exhausted");
        const uint32_t start = entryUsed;
        entryUsed += input.length;
        wire.data_offset = start;
        wire.length = input.length;
        std::array<const void*, DEHERM_SCRIPT_UNIVERSAL_MAX_DEPTH> next{};
        for (uint32_t ancestor = 0; ancestor < ancestorCount; ++ancestor) next[ancestor] = ancestors[ancestor];
        next[ancestorCount] = input.data;
        const auto* source = static_cast<const ScriptTableEntry*>(input.data);
        for (uint32_t item = 0; item < input.length; ++item) {
          if (!encode(source[item].key, &entries[start + item].key_index, depth + 1, next.data(), ancestorCount + 1) ||
              !encode(source[item].value, &entries[start + item].value_index, depth + 1, next.data(), ancestorCount + 1)) return false;
        }
        return true;
      }
      case ScriptValueTag::kCallback:
        return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal backend returned an unsupported callback");
    }
    return reject(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, "Universal backend returned an unknown tag");
  }
};
}  // namespace

extern "C" DehermScriptUniversalStatus deherm_script_universal_dispatch(
    uint32_t stable_id,
    const DehermScriptUniversalValue* input_values, uint32_t input_value_count,
    const DehermScriptUniversalEntry* input_entries, uint32_t input_entry_count,
    const char* input_strings, uint32_t input_string_bytes,
    const float* input_floats, uint32_t input_float_count,
    const DehermScriptUniversalUrl* input_urls, uint32_t input_url_count,
    const uint32_t* argument_roots, uint32_t argument_count,
    DehermScriptUniversalValue* output_values, uint32_t output_value_capacity,
    uint32_t* output_value_count,
    DehermScriptUniversalEntry* output_entries, uint32_t output_entry_capacity,
    uint32_t* output_entry_count,
    char* output_strings, uint32_t output_string_capacity,
    uint32_t* output_string_bytes,
    float* output_floats, uint32_t output_float_capacity,
    uint32_t* output_float_count,
    DehermScriptUniversalUrl* output_urls, uint32_t output_url_capacity,
    uint32_t* output_url_count,
    uint32_t* result_roots, uint32_t result_capacity,
    uint32_t* result_count,
    char* error, uint32_t error_capacity) {
  if (output_value_count) *output_value_count = 0;
  if (output_entry_count) *output_entry_count = 0;
  if (output_string_bytes) *output_string_bytes = 0;
  if (output_float_count) *output_float_count = 0;
  if (output_url_count) *output_url_count = 0;
  if (result_count) *result_count = 0;
  if (error && error_capacity) error[0] = '\0';
  const auto* operation = defold_hermes::universal_value::find(stable_id);
  if (!operation) return fail(DEHERM_SCRIPT_UNIVERSAL_ROUTE_MISSING, error, error_capacity, "Stable ID is not in the universal-value family");
  if (argument_count < operation->minimumArgumentCount || argument_count > operation->maximumArgumentCount ||
      argument_count > DEHERM_SCRIPT_UNIVERSAL_MAX_ARGUMENTS || (argument_count && !argument_roots) ||
      input_value_count > DEHERM_SCRIPT_UNIVERSAL_MAX_VALUES || (input_value_count && !input_values) ||
      input_entry_count > DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES || (input_entry_count && !input_entries) ||
      input_string_bytes > DEHERM_SCRIPT_UNIVERSAL_MAX_STRING_BYTES || (input_string_bytes && !input_strings) ||
      input_float_count > DEHERM_SCRIPT_UNIVERSAL_MAX_MATRIX4_VALUES * 16u || (input_float_count && !input_floats) ||
      input_url_count > DEHERM_SCRIPT_UNIVERSAL_MAX_URL_VALUES || (input_url_count && !input_urls)) {
    return fail(DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE, error, error_capacity, "Universal input frame violates generated bounds");
  }
  if (!output_value_count || !output_entry_count || !output_string_bytes || !output_float_count || !output_url_count || !result_count ||
      output_value_capacity > DEHERM_SCRIPT_UNIVERSAL_MAX_VALUES || (output_value_capacity && !output_values) ||
      output_entry_capacity > DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES || (output_entry_capacity && !output_entries) ||
      output_string_capacity > DEHERM_SCRIPT_UNIVERSAL_MAX_STRING_BYTES || (output_string_capacity && !output_strings) ||
      output_float_capacity > DEHERM_SCRIPT_UNIVERSAL_MAX_MATRIX4_VALUES * 16u || (output_float_capacity && !output_floats) ||
      output_url_capacity > DEHERM_SCRIPT_UNIVERSAL_MAX_URL_VALUES || (output_url_capacity && !output_urls) ||
      result_capacity < operation->resultCount || (result_capacity && !result_roots)) {
    return fail(DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED, error, error_capacity, "Universal output frame violates generated bounds or capacity");
  }

  std::array<ScriptValue, DEHERM_SCRIPT_UNIVERSAL_MAX_ARGUMENTS> arguments{};
  std::array<ScriptValue, DEHERM_SCRIPT_UNIVERSAL_MAX_RESULTS> results{};
  std::array<ScriptTableEntry, DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES> inputTableScratch{};
  std::array<ScriptTableEntry, DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES> outputTableScratch{};
  ScriptMatrix4Arena matrixArena{};
  ScriptUrlArena<32> urlArena{1};
  DecodeContext decoder{input_values, input_value_count, input_entries, input_entry_count,
      input_strings, input_string_bytes, input_floats, input_float_count, input_urls, input_url_count,
      inputTableScratch.data(), 0, &matrixArena, &urlArena, error, error_capacity};
  const uint32_t noAncestors[DEHERM_SCRIPT_UNIVERSAL_MAX_DEPTH]{};
  for (uint32_t index = 0; index < argument_count; ++index) {
    if (!decoder.decode(argument_roots[index], &arguments[index], 0, noAncestors, 0)) return decoder.status;
  }

  ScriptCallFrame frame{};
  frame.stableId = stable_id;
  frame.arguments = arguments.data();
  frame.argumentCount = argument_count;
  frame.results = results.data();
  frame.resultCapacity = results.size();
  frame.stringScratch = output_strings;
  frame.stringScratchCapacity = output_string_capacity;
  frame.tableScratch = outputTableScratch.data();
  frame.tableScratchCapacity = outputTableScratch.size();
  frame.matrix4Arena = &matrixArena;
  frame.urlArena = &urlArena;
  if (!dispatchScriptCall(&frame)) {
    return fail(DEHERM_SCRIPT_UNIVERSAL_BACKEND_ERROR, error, error_capacity, scriptBridgeLastError());
  }
  if (frame.resultCount != operation->resultCount) {
    for (uint32_t index = 0; index < frame.resultCount && index < results.size(); ++index) releaseGraph(results[index], 0);
    return fail(DEHERM_SCRIPT_UNIVERSAL_BACKEND_ERROR, error, error_capacity, "Universal backend returned the wrong result count");
  }

  EncodeContext encoder{output_values, output_value_capacity, 0, output_entries, output_entry_capacity, 0,
      output_strings, output_string_capacity, frame.stringScratchUsed, output_floats, output_float_capacity, 0,
      output_urls, output_url_capacity, 0, &matrixArena, &urlArena, error, error_capacity};
  const void* noPointers[DEHERM_SCRIPT_UNIVERSAL_MAX_DEPTH]{};
  for (uint32_t index = 0; index < frame.resultCount; ++index) {
    if (!encoder.encode(results[index], &result_roots[index], 0, noPointers, 0)) {
      for (uint32_t release = 0; release < frame.resultCount; ++release) releaseGraph(results[release], 0);
      return encoder.status;
    }
  }
  *output_value_count = encoder.valueUsed;
  *output_entry_count = encoder.entryUsed;
  *output_string_bytes = encoder.stringUsed;
  *output_float_count = encoder.floatUsed;
  *output_url_count = encoder.urlUsed;
  *result_count = frame.resultCount;
  return DEHERM_SCRIPT_UNIVERSAL_OK;
}

extern "C" void deherm_script_universal_release(DehermScriptUniversalValue* value) {
  if (!value) return;
  if (value->tag == static_cast<uint8_t>(ScriptValueTag::kHandle)) {
    const auto kind = static_cast<ScriptHandleKind>(value->handle_kind);
    if (kind == ScriptHandleKind::kGuiNode || kind == ScriptHandleKind::kLuaUserdata ||
        kind == ScriptHandleKind::kLuaSemanticHandle) {
      releaseScriptHandle(kind, value->runtime, value->payload);
    }
  }
  *value = {};
}
