// Generated by scripts/generate-dmsdk-named-scalar-bindings.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_named_scalar.h>
#include <defold_hermes/generated_dmsdk_named_scalar_runtime.h>
#ifndef DLIB_LOG_DOMAIN
#define DLIB_LOG_DOMAIN "defold_hermes"
#endif
#include <dmsdk/dlib/profile.h>
#include <dmsdk/dlib/thread.h>
#include <dmsdk/gameobject/gameobject.h>
#include <dmsdk/sound/sound.h>
#include <cstring>
#include <type_traits>

void ProfilePropertyAddF32(ProfileIdx idx, float v);
void ProfilePropertyAddF64(ProfileIdx idx, double v);
void ProfilePropertyAddS32(ProfileIdx idx, int32_t v);
void ProfilePropertyAddS64(ProfileIdx idx, int64_t v);
void ProfilePropertyAddU32(ProfileIdx idx, uint32_t v);
void ProfilePropertyAddU64(ProfileIdx idx, uint64_t v);
void ProfilePropertySetBool(ProfileIdx idx, int v);
void ProfilePropertySetF32(ProfileIdx idx, float v);
void ProfilePropertySetF64(ProfileIdx idx, double v);
void ProfilePropertySetS32(ProfileIdx idx, int32_t v);
void ProfilePropertySetS64(ProfileIdx idx, int64_t v);
void ProfilePropertySetU32(ProfileIdx idx, uint32_t v);
void ProfilePropertySetU64(ProfileIdx idx, uint64_t v);
using DehermNamedScalarSignature0=dmhash_t (*)(void);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature0>(&dmGameObject::CreateInstanceId)),DehermNamedScalarSignature0>::value,"dmsdk:dmGameObject::CreateInstanceId@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:598:1005");
using DehermNamedScalarSignature1=bool (*)(dmhash_t);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature1>(&dmSound::IsGroupMuted)),DehermNamedScalarSignature1>::value,"dmsdk:dmSound::IsGroupMuted@upstream/defold/engine/sound/src/dmsdk/sound/sound.h:108:2140");
using DehermNamedScalarSignature2=dmThread::TlsKey (*)(void);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature2>(&dmThread::AllocTls)),DehermNamedScalarSignature2>::value,"dmsdk:dmThread::AllocTls@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:119:608");
using DehermNamedScalarSignature3=void (*)(dmThread::Thread);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature3>(&dmThread::Detach)),DehermNamedScalarSignature3>::value,"dmsdk:dmThread::Detach@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:112:607");
using DehermNamedScalarSignature4=void (*)(dmThread::TlsKey);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature4>(&dmThread::FreeTls)),DehermNamedScalarSignature4>::value,"dmsdk:dmThread::FreeTls@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:126:609");
using DehermNamedScalarSignature5=dmThread::Thread (*)(void);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature5>(&dmThread::GetCurrentThread)),DehermNamedScalarSignature5>::value,"dmsdk:dmThread::GetCurrentThread@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:148:612");
using DehermNamedScalarSignature6=void (*)(dmThread::Thread);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature6>(&dmThread::Join)),DehermNamedScalarSignature6>::value,"dmsdk:dmThread::Join@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:102:606");
using DehermNamedScalarSignature7=void (*)(ProfileIdx, float);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature7>(&ProfilePropertyAddF32)),DehermNamedScalarSignature7>::value,"dmsdk:ProfilePropertyAddF32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:480");
using DehermNamedScalarSignature8=void (*)(ProfileIdx, double);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature8>(&ProfilePropertyAddF64)),DehermNamedScalarSignature8>::value,"dmsdk:ProfilePropertyAddF64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:492");
using DehermNamedScalarSignature9=void (*)(ProfileIdx, int32_t);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature9>(&ProfilePropertyAddS32)),DehermNamedScalarSignature9>::value,"dmsdk:ProfilePropertyAddS32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:472");
using DehermNamedScalarSignature10=void (*)(ProfileIdx, int64_t);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature10>(&ProfilePropertyAddS64)),DehermNamedScalarSignature10>::value,"dmsdk:ProfilePropertyAddS64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:484");
using DehermNamedScalarSignature11=void (*)(ProfileIdx, uint32_t);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature11>(&ProfilePropertyAddU32)),DehermNamedScalarSignature11>::value,"dmsdk:ProfilePropertyAddU32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:476");
using DehermNamedScalarSignature12=void (*)(ProfileIdx, uint64_t);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature12>(&ProfilePropertyAddU64)),DehermNamedScalarSignature12>::value,"dmsdk:ProfilePropertyAddU64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:488");
using DehermNamedScalarSignature13=void (*)(ProfileIdx, int);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature13>(&ProfilePropertySetBool)),DehermNamedScalarSignature13>::value,"dmsdk:ProfilePropertySetBool@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:467");
using DehermNamedScalarSignature14=void (*)(ProfileIdx, float);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature14>(&ProfilePropertySetF32)),DehermNamedScalarSignature14>::value,"dmsdk:ProfilePropertySetF32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:479");
using DehermNamedScalarSignature15=void (*)(ProfileIdx, double);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature15>(&ProfilePropertySetF64)),DehermNamedScalarSignature15>::value,"dmsdk:ProfilePropertySetF64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:491");
using DehermNamedScalarSignature16=void (*)(ProfileIdx, int32_t);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature16>(&ProfilePropertySetS32)),DehermNamedScalarSignature16>::value,"dmsdk:ProfilePropertySetS32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:471");
using DehermNamedScalarSignature17=void (*)(ProfileIdx, int64_t);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature17>(&ProfilePropertySetS64)),DehermNamedScalarSignature17>::value,"dmsdk:ProfilePropertySetS64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:483");
using DehermNamedScalarSignature18=void (*)(ProfileIdx, uint32_t);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature18>(&ProfilePropertySetU32)),DehermNamedScalarSignature18>::value,"dmsdk:ProfilePropertySetU32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:475");
using DehermNamedScalarSignature19=void (*)(ProfileIdx, uint64_t);
static_assert(std::is_same<decltype(static_cast<DehermNamedScalarSignature19>(&ProfilePropertySetU64)),DehermNamedScalarSignature19>::value,"dmsdk:ProfilePropertySetU64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:487");

namespace {
const DehermDmSdkNamedScalarDescriptor kDescriptors[] = {
  { UINT16_C(0), UINT8_C(0), "dmsdk:dmGameObject::CreateInstanceId@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:598:1005", "dmGameObject::CreateInstanceId" },
  { UINT16_C(1), UINT8_C(1), "dmsdk:dmSound::IsGroupMuted@upstream/defold/engine/sound/src/dmsdk/sound/sound.h:108:2140", "dmSound::IsGroupMuted" },
  { UINT16_C(2), UINT8_C(0), "dmsdk:dmThread::AllocTls@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:119:608", "dmThread::AllocTls" },
  { UINT16_C(3), UINT8_C(1), "dmsdk:dmThread::Detach@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:112:607", "dmThread::Detach" },
  { UINT16_C(4), UINT8_C(1), "dmsdk:dmThread::FreeTls@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:126:609", "dmThread::FreeTls" },
  { UINT16_C(5), UINT8_C(0), "dmsdk:dmThread::GetCurrentThread@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:148:612", "dmThread::GetCurrentThread" },
  { UINT16_C(6), UINT8_C(1), "dmsdk:dmThread::Join@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:102:606", "dmThread::Join" },
  { UINT16_C(7), UINT8_C(2), "dmsdk:ProfilePropertyAddF32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:480", "ProfilePropertyAddF32" },
  { UINT16_C(8), UINT8_C(2), "dmsdk:ProfilePropertyAddF64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:492", "ProfilePropertyAddF64" },
  { UINT16_C(9), UINT8_C(2), "dmsdk:ProfilePropertyAddS32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:472", "ProfilePropertyAddS32" },
  { UINT16_C(10), UINT8_C(2), "dmsdk:ProfilePropertyAddS64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:484", "ProfilePropertyAddS64" },
  { UINT16_C(11), UINT8_C(2), "dmsdk:ProfilePropertyAddU32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:476", "ProfilePropertyAddU32" },
  { UINT16_C(12), UINT8_C(2), "dmsdk:ProfilePropertyAddU64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:488", "ProfilePropertyAddU64" },
  { UINT16_C(13), UINT8_C(2), "dmsdk:ProfilePropertySetBool@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:467", "ProfilePropertySetBool" },
  { UINT16_C(14), UINT8_C(2), "dmsdk:ProfilePropertySetF32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:479", "ProfilePropertySetF32" },
  { UINT16_C(15), UINT8_C(2), "dmsdk:ProfilePropertySetF64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:491", "ProfilePropertySetF64" },
  { UINT16_C(16), UINT8_C(2), "dmsdk:ProfilePropertySetS32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:471", "ProfilePropertySetS32" },
  { UINT16_C(17), UINT8_C(2), "dmsdk:ProfilePropertySetS64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:483", "ProfilePropertySetS64" },
  { UINT16_C(18), UINT8_C(2), "dmsdk:ProfilePropertySetU32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:475", "ProfilePropertySetU32" },
  { UINT16_C(19), UINT8_C(2), "dmsdk:ProfilePropertySetU64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:487", "ProfilePropertySetU64" }
};
float unpack_f32(uint64_t raw){uint32_t bits=static_cast<uint32_t>(raw);float value=0;std::memcpy(&value,&bits,sizeof(value));return value;}
double unpack_f64(uint64_t raw){double value=0;std::memcpy(&value,&raw,sizeof(value));return value;}
int32_t unpack_i32(uint64_t raw){uint32_t bits=static_cast<uint32_t>(raw);int32_t value=0;std::memcpy(&value,&bits,sizeof(value));return value;}
int64_t unpack_i64(uint64_t raw){int64_t value=0;std::memcpy(&value,&raw,sizeof(value));return value;}
[[maybe_unused]] uint64_t pack_f32(float value){uint32_t bits=0;std::memcpy(&bits,&value,sizeof(bits));return bits;}
[[maybe_unused]] uint64_t pack_f64(double value){uint64_t bits=0;std::memcpy(&bits,&value,sizeof(bits));return bits;}
} // namespace

extern "C" {

uint64_t deherm_dmsdk_named_scalar_dm_game_object_create_instance_id(void)
{
  return static_cast<uint64_t>(dmGameObject::CreateInstanceId());
}

uint8_t deherm_dmsdk_named_scalar_dm_sound_is_group_muted(uint64_t group)
{
  return dmSound::IsGroupMuted(static_cast<dmhash_t>(group)) ? UINT8_C(1) : UINT8_C(0);
}

uintptr_t deherm_dmsdk_named_scalar_dm_thread_alloc_tls(void)
{
  return static_cast<uintptr_t>(dmThread::AllocTls());
}

void deherm_dmsdk_named_scalar_dm_thread_detach(uintptr_t thread)
{
  dmThread::Detach(static_cast<dmThread::Thread>(thread));
}

void deherm_dmsdk_named_scalar_dm_thread_free_tls(uintptr_t key)
{
  dmThread::FreeTls(static_cast<dmThread::TlsKey>(key));
}

uintptr_t deherm_dmsdk_named_scalar_dm_thread_get_current_thread(void)
{
  return static_cast<uintptr_t>(dmThread::GetCurrentThread());
}

void deherm_dmsdk_named_scalar_dm_thread_join(uintptr_t thread)
{
  dmThread::Join(static_cast<dmThread::Thread>(thread));
}

void deherm_dmsdk_named_scalar_profile_property_add_f32(uint64_t idx, float v)
{
  ProfilePropertyAddF32(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_add_f64(uint64_t idx, double v)
{
  ProfilePropertyAddF64(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_add_s32(uint64_t idx, int32_t v)
{
  ProfilePropertyAddS32(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_add_s64(uint64_t idx, int64_t v)
{
  ProfilePropertyAddS64(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_add_u32(uint64_t idx, uint32_t v)
{
  ProfilePropertyAddU32(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_add_u64(uint64_t idx, uint64_t v)
{
  ProfilePropertyAddU64(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_set_bool(uint64_t idx, int32_t v)
{
  ProfilePropertySetBool(static_cast<ProfileIdx>(idx), static_cast<int>(v));
}

void deherm_dmsdk_named_scalar_profile_property_set_f32(uint64_t idx, float v)
{
  ProfilePropertySetF32(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_set_f64(uint64_t idx, double v)
{
  ProfilePropertySetF64(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_set_s32(uint64_t idx, int32_t v)
{
  ProfilePropertySetS32(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_set_s64(uint64_t idx, int64_t v)
{
  ProfilePropertySetS64(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_set_u32(uint64_t idx, uint32_t v)
{
  ProfilePropertySetU32(static_cast<ProfileIdx>(idx), v);
}

void deherm_dmsdk_named_scalar_profile_property_set_u64(uint64_t idx, uint64_t v)
{
  ProfilePropertySetU64(static_cast<ProfileIdx>(idx), v);
}

uint32_t deherm_dmsdk_named_scalar_count(void){return UINT32_C(20);}
const DehermDmSdkNamedScalarDescriptor* deherm_dmsdk_named_scalar_descriptors(void){return kDescriptors;}

DehermDmSdkNamedScalarStatus deherm_dmsdk_named_scalar_dispatch(
    uint16_t id, const uint64_t* arguments, uint32_t argument_count, uint64_t* result)
{
  if(id>=deherm_dmsdk_named_scalar_count())return DEHERM_DMSDK_NAMED_SCALAR_UNKNOWN_ID;
  const auto& descriptor=kDescriptors[id];
  if(argument_count!=descriptor.argument_count)return DEHERM_DMSDK_NAMED_SCALAR_WRONG_ARITY;
  if(result==nullptr||(argument_count!=0&&arguments==nullptr))return DEHERM_DMSDK_NAMED_SCALAR_NULL_STORAGE;
  switch(id){
    case 0:
      *result = static_cast<uint64_t>(deherm_dmsdk_named_scalar_dm_game_object_create_instance_id());
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 1:
      *result = static_cast<uint64_t>(deherm_dmsdk_named_scalar_dm_sound_is_group_muted(static_cast<uint64_t>(arguments[0])));
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 2:
      *result = static_cast<uint64_t>(deherm_dmsdk_named_scalar_dm_thread_alloc_tls());
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 3:
      if (arguments[0] > static_cast<uint64_t>(UINTPTR_MAX)) return DEHERM_DMSDK_NAMED_SCALAR_RANGE;
      deherm_dmsdk_named_scalar_dm_thread_detach(static_cast<uintptr_t>(arguments[0]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 4:
      if (arguments[0] > static_cast<uint64_t>(UINTPTR_MAX)) return DEHERM_DMSDK_NAMED_SCALAR_RANGE;
      deherm_dmsdk_named_scalar_dm_thread_free_tls(static_cast<uintptr_t>(arguments[0]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 5:
      *result = static_cast<uint64_t>(deherm_dmsdk_named_scalar_dm_thread_get_current_thread());
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 6:
      if (arguments[0] > static_cast<uint64_t>(UINTPTR_MAX)) return DEHERM_DMSDK_NAMED_SCALAR_RANGE;
      deherm_dmsdk_named_scalar_dm_thread_join(static_cast<uintptr_t>(arguments[0]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 7:
      if (arguments[1] > UINT32_MAX) return DEHERM_DMSDK_NAMED_SCALAR_RANGE;
      deherm_dmsdk_named_scalar_profile_property_add_f32(static_cast<uint64_t>(arguments[0]), unpack_f32(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 8:
      deherm_dmsdk_named_scalar_profile_property_add_f64(static_cast<uint64_t>(arguments[0]), unpack_f64(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 9:
      if (arguments[1] != static_cast<uint64_t>(static_cast<int64_t>(static_cast<int32_t>(arguments[1])))) return DEHERM_DMSDK_NAMED_SCALAR_RANGE;
      deherm_dmsdk_named_scalar_profile_property_add_s32(static_cast<uint64_t>(arguments[0]), unpack_i32(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 10:
      deherm_dmsdk_named_scalar_profile_property_add_s64(static_cast<uint64_t>(arguments[0]), unpack_i64(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 11:
      if (arguments[1] > UINT32_MAX) return DEHERM_DMSDK_NAMED_SCALAR_RANGE;
      deherm_dmsdk_named_scalar_profile_property_add_u32(static_cast<uint64_t>(arguments[0]), static_cast<uint32_t>(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 12:
      deherm_dmsdk_named_scalar_profile_property_add_u64(static_cast<uint64_t>(arguments[0]), static_cast<uint64_t>(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 13:
      if (arguments[1] != static_cast<uint64_t>(static_cast<int64_t>(static_cast<int32_t>(arguments[1])))) return DEHERM_DMSDK_NAMED_SCALAR_RANGE;
      deherm_dmsdk_named_scalar_profile_property_set_bool(static_cast<uint64_t>(arguments[0]), unpack_i32(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 14:
      if (arguments[1] > UINT32_MAX) return DEHERM_DMSDK_NAMED_SCALAR_RANGE;
      deherm_dmsdk_named_scalar_profile_property_set_f32(static_cast<uint64_t>(arguments[0]), unpack_f32(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 15:
      deherm_dmsdk_named_scalar_profile_property_set_f64(static_cast<uint64_t>(arguments[0]), unpack_f64(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 16:
      if (arguments[1] != static_cast<uint64_t>(static_cast<int64_t>(static_cast<int32_t>(arguments[1])))) return DEHERM_DMSDK_NAMED_SCALAR_RANGE;
      deherm_dmsdk_named_scalar_profile_property_set_s32(static_cast<uint64_t>(arguments[0]), unpack_i32(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 17:
      deherm_dmsdk_named_scalar_profile_property_set_s64(static_cast<uint64_t>(arguments[0]), unpack_i64(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 18:
      if (arguments[1] > UINT32_MAX) return DEHERM_DMSDK_NAMED_SCALAR_RANGE;
      deherm_dmsdk_named_scalar_profile_property_set_u32(static_cast<uint64_t>(arguments[0]), static_cast<uint32_t>(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    case 19:
      deherm_dmsdk_named_scalar_profile_property_set_u64(static_cast<uint64_t>(arguments[0]), static_cast<uint64_t>(arguments[1]));
      *result = UINT64_C(0);
      return DEHERM_DMSDK_NAMED_SCALAR_OK;
    default:return DEHERM_DMSDK_NAMED_SCALAR_UNKNOWN_ID;
  }
}

} // extern "C"
