// Generated by scripts/generate-native-module-providers.mjs. Do not edit.
#include <defold_hermes/native_module_provider.h>
#include <array>
#include <cstring>
#include <mutex>
namespace {
constexpr size_t kMaximumProviders = 16, kMaximumMethods = 32, kMaximumNameBytes = 64;
struct Slot {
  bool occupied = false;
  DehermNativeModuleProviderV1 provider{};
  char module_name[kMaximumNameBytes]{};
  std::array<DehermNativeModuleMethodV1, kMaximumMethods> methods{};
  std::array<std::array<char, kMaximumNameBytes>, kMaximumMethods> method_names{};
};
std::mutex g_mutex;
std::array<Slot, kMaximumProviders> g_slots{};
bool validName(const char* name) { if (!name) return false; const size_t n = std::strlen(name); return n && n < kMaximumNameBytes; }
bool validProvider(const DehermNativeModuleProviderV1& p) {
  if (p.abi_version != DEHERM_NATIVE_MODULE_PROVIDER_ABI_VERSION ||
      p.struct_size < sizeof(DehermNativeModuleProviderV1) || !validName(p.module_name) ||
      !p.module_abi_version || !p.methods || !p.invoke || !p.method_count || p.method_count > kMaximumMethods) return false;
  for (uint32_t i = 0; i < p.method_count; ++i) {
    const auto& m = p.methods[i];
    if (!m.id || !validName(m.name) || m.argument_count > DEHERM_NATIVE_MODULE_MAX_ARGUMENTS ||
        (m.result_kind != DEHERM_NATIVE_MODULE_RESULT_STATUS && m.result_kind != DEHERM_NATIVE_MODULE_RESULT_U32)) return false;
    for (uint32_t a = 0; a < m.argument_count; ++a)
      if (m.argument_kinds[a] < DEHERM_NATIVE_MODULE_ARGUMENT_U32 || m.argument_kinds[a] > DEHERM_NATIVE_MODULE_ARGUMENT_BOOL) return false;
    for (uint32_t j = 0; j < i; ++j)
      if (p.methods[j].id == m.id || std::strcmp(p.methods[j].name, m.name) == 0) return false;
  }
  return true;
}
void repair(Slot& s) {
  s.provider.module_name = s.module_name; s.provider.methods = s.methods.data();
  for (uint32_t i = 0; i < s.provider.method_count; ++i) s.methods[i].name = s.method_names[i].data();
}
}
extern "C" int32_t deherm_native_module_register_v1(const DehermNativeModuleProviderV1* p) {
  if (!p || !validProvider(*p)) return DEHERM_NATIVE_MODULE_REGISTRY_INVALID_ARGUMENT;
  std::lock_guard<std::mutex> lock(g_mutex); Slot* available = nullptr;
  for (auto& s : g_slots) { if (!s.occupied) { if (!available) available = &s; continue; }
    if (std::strcmp(s.module_name, p->module_name) == 0) return DEHERM_NATIVE_MODULE_REGISTRY_DUPLICATE; }
  if (!available) return DEHERM_NATIVE_MODULE_REGISTRY_FULL;
  *available = Slot{}; available->occupied = true; available->provider = *p;
  std::strcpy(available->module_name, p->module_name);
  for (uint32_t i = 0; i < p->method_count; ++i) { available->methods[i] = p->methods[i]; std::strcpy(available->method_names[i].data(), p->methods[i].name); }
  repair(*available); return DEHERM_NATIVE_MODULE_REGISTRY_OK;
}
extern "C" int32_t deherm_native_module_unregister_v1(const char* name) {
  if (!validName(name)) return DEHERM_NATIVE_MODULE_REGISTRY_INVALID_ARGUMENT;
  std::lock_guard<std::mutex> lock(g_mutex);
  for (auto& s : g_slots) if (s.occupied && std::strcmp(s.module_name, name) == 0) { s = Slot{}; return DEHERM_NATIVE_MODULE_REGISTRY_OK; }
  return DEHERM_NATIVE_MODULE_REGISTRY_NOT_FOUND;
}
extern "C" size_t deherm_native_module_provider_count_v1(void) {
  std::lock_guard<std::mutex> lock(g_mutex); size_t count = 0; for (const auto& s : g_slots) if (s.occupied) ++count; return count;
}
extern "C" int32_t deherm_native_module_copy_provider_v1(size_t index, DehermNativeModuleProviderV1* out) {
  if (!out) return DEHERM_NATIVE_MODULE_REGISTRY_INVALID_ARGUMENT;
  std::lock_guard<std::mutex> lock(g_mutex); size_t current = 0;
  for (auto& s : g_slots) if (s.occupied && current++ == index) { *out = s.provider; return DEHERM_NATIVE_MODULE_REGISTRY_OK; }
  return DEHERM_NATIVE_MODULE_REGISTRY_NOT_FOUND;
}
extern "C" int32_t deherm_native_module_resolve_v1(const char* name, uint32_t abi, DehermNativeModuleProviderV1* out) {
  if (!validName(name) || !abi || !out) return DEHERM_NATIVE_MODULE_REGISTRY_INVALID_ARGUMENT;
  std::lock_guard<std::mutex> lock(g_mutex);
  for (auto& s : g_slots) if (s.occupied && std::strcmp(s.module_name, name) == 0) {
    if (s.provider.module_abi_version != abi) return DEHERM_NATIVE_MODULE_REGISTRY_NOT_FOUND;
    *out = s.provider; return DEHERM_NATIVE_MODULE_REGISTRY_OK;
  }
  return DEHERM_NATIVE_MODULE_REGISTRY_NOT_FOUND;
}
