// Generated by scripts/generate-dmsdk-scalar-thunks.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_scalar.h>
#include <dmsdk/dlib/endian.hpp>

extern "C" {

uint16_t deherm_dmsdk_dm_endian_byte_swap_u16(uint16_t x)
{
    return dmEndian::ByteSwap(x);
}

uint32_t deherm_dmsdk_dm_endian_byte_swap_u32(uint32_t x)
{
    return dmEndian::ByteSwap(x);
}

uint64_t deherm_dmsdk_dm_endian_byte_swap_u64(uint64_t x)
{
    return dmEndian::ByteSwap(x);
}

uint32_t deherm_dmsdk_dm_endian_to_host_u32(uint32_t x)
{
    return dmEndian::ToHost(x);
}

uint64_t deherm_dmsdk_dm_endian_to_host_u64(uint64_t x)
{
    return dmEndian::ToHost(x);
}

uint16_t deherm_dmsdk_dm_endian_to_host_u16(uint16_t x)
{
    return dmEndian::ToHost(x);
}

uint64_t deherm_dmsdk_dm_endian_to_network_u64(uint64_t x)
{
    return dmEndian::ToNetwork(x);
}

uint16_t deherm_dmsdk_dm_endian_to_network_u16(uint16_t x)
{
    return dmEndian::ToNetwork(x);
}

uint32_t deherm_dmsdk_dm_endian_to_network_u32(uint32_t x)
{
    return dmEndian::ToNetwork(x);
}

uint16_t deherm_dmsdk_endian_swap16_u16(uint16_t x)
{
    return EndianSwap16(x);
}

uint32_t deherm_dmsdk_endian_swap32_u32(uint32_t x)
{
    return EndianSwap32(x);
}

uint64_t deherm_dmsdk_endian_swap64_u64(uint64_t x)
{
    return EndianSwap64(x);
}

uint16_t deherm_dmsdk_endian_to_host16_u16(uint16_t x)
{
    return EndianToHost16(x);
}

uint32_t deherm_dmsdk_endian_to_host32_u32(uint32_t x)
{
    return EndianToHost32(x);
}

uint64_t deherm_dmsdk_endian_to_host64_u64(uint64_t x)
{
    return EndianToHost64(x);
}

uint16_t deherm_dmsdk_endian_to_network16_u16(uint16_t x)
{
    return EndianToNetwork16(x);
}

uint32_t deherm_dmsdk_endian_to_network32_u32(uint32_t x)
{
    return EndianToNetwork32(x);
}

uint64_t deherm_dmsdk_endian_to_network64_u64(uint64_t x)
{
    return EndianToNetwork64(x);
}

} // extern "C"
