// Generated by scripts/generate-dmsdk-xtea-span-bindings.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_xtea_span.h>
#include <dmsdk/dlib/crypt.h>
extern "C" {uint8_t deherm_dmsdk_xtea_span_dm_crypt_decrypt(uint8_t*d,uint32_t n,const uint8_t*k,uint32_t z){if(!d||!k||z>16)return 0;return dmCrypt::Decrypt(dmCrypt::ALGORITHM_XTEA,d,n,k,z)==dmCrypt::RESULT_OK;}uint8_t deherm_dmsdk_xtea_span_dm_crypt_encrypt(uint8_t*d,uint32_t n,const uint8_t*k,uint32_t z){if(!d||!k||z>16)return 0;return dmCrypt::Encrypt(dmCrypt::ALGORITHM_XTEA,d,n,k,z)==dmCrypt::RESULT_OK;} }
