// Generated by scripts/generate-dmsdk-scalar-thunks.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_scalar.h>
#ifndef DLIB_LOG_DOMAIN
#define DLIB_LOG_DOMAIN "defold_hermes"
#endif
#include <dmsdk/dlib/utf8.h>

extern "C" {

uint8_t deherm_dmsdk_dm_utf8_is_breaking_u32(uint32_t c)
{
    return dmUtf8::IsBreaking(c) ? UINT8_C(1) : UINT8_C(0);
}

uint8_t deherm_dmsdk_dm_utf8_is_white_space_u32(uint32_t c)
{
    return dmUtf8::IsWhiteSpace(c) ? UINT8_C(1) : UINT8_C(0);
}

} // extern "C"
