// Generated by scripts/generate-dmsdk-fixed-digest-bindings.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_fixed_digest.h>
#include <dmsdk/dlib/crypt.h>
extern "C" {
uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_md5(const uint8_t* input, uint32_t input_length, uint8_t* output, uint32_t output_capacity)
{
  if(output==nullptr||output_capacity<UINT32_C(16)||(input_length!=0&&input==nullptr))return UINT8_C(0); dmCrypt::HashMd5(input, input_length, output); return UINT8_C(1);
}
uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_sha1(const uint8_t* input, uint32_t input_length, uint8_t* output, uint32_t output_capacity)
{
  if(output==nullptr||output_capacity<UINT32_C(20)||(input_length!=0&&input==nullptr))return UINT8_C(0); dmCrypt::HashSha1(input, input_length, output); return UINT8_C(1);
}
uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_sha256(const uint8_t* input, uint32_t input_length, uint8_t* output, uint32_t output_capacity)
{
  if(output==nullptr||output_capacity<UINT32_C(32)||(input_length!=0&&input==nullptr))return UINT8_C(0); dmCrypt::HashSha256(input, input_length, output); return UINT8_C(1);
}
uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_sha512(const uint8_t* input, uint32_t input_length, uint8_t* output, uint32_t output_capacity)
{
  if(output==nullptr||output_capacity<UINT32_C(64)||(input_length!=0&&input==nullptr))return UINT8_C(0); dmCrypt::HashSha512(input, input_length, output); return UINT8_C(1);
} }
