// Generated by scripts/generate-lua-bridge.mjs. Do not edit.
#include <defold_hermes/generated_lua_bridge.hpp>

namespace defold_hermes::lua_bridge::generated {
namespace {
constexpr BindingDescriptor kBindings[] = {
  {"timer", "delay"},
  {"timer", "cancel"},
  {"timer", "trigger"},
};
}  // namespace

bool initialize(LuaBridge& bridge, lua_State* state, RegistryApi registryApi, InstanceApi instanceApi) {
  return bridge.initialize(state, kBindings, 3, 32, registryApi, instanceApi);
}

bool timerDelay(LuaBridge& bridge, double delay, bool repeating, Handle callback, uint32_t* out) {
  LuaCall call = bridge.beginCall(static_cast<uint32_t>(Binding::TimerDelay));
  if (!call) return false;
  call.pushF64(delay);
  call.pushBoolean(repeating);
  call.pushTimerCallback(callback, repeating);
  if (!call.invoke(3, 1)) return false;
  if (!call.readU32(0, out)) return false;
  return bridge.trackTimerCallback(*out, callback, repeating);
}

bool timerCancel(LuaBridge& bridge, uint32_t handle, bool* out) {
  LuaCall call = bridge.beginCall(static_cast<uint32_t>(Binding::TimerCancel));
  if (!call) return false;
  call.pushU32(handle);
  if (!call.invoke(1, 1)) return false;
  if (!call.readBoolean(0, out)) return false;
  if (*out) bridge.releaseTimerCallback(handle);
  return true;
}

bool timerTrigger(LuaBridge& bridge, uint32_t handle, bool* out) {
  LuaCall call = bridge.beginCall(static_cast<uint32_t>(Binding::TimerTrigger));
  if (!call) return false;
  call.pushU32(handle);
  if (!call.invoke(1, 1)) return false;
  if (!call.readBoolean(0, out)) return false;
  return true;
}

}  // namespace defold_hermes::lua_bridge::generated
