// Generated by scripts/generate-dmsdk-scratch-scalar-out-bindings.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_scratch_scalar_out.h>
#include <string.h>
namespace {
const DehermDmSdkScratchDescriptor kDescriptors[] = {
  { UINT16_C(0), UINT8_C(3), UINT8_C(3), UINT8_C(1), UINT8_C(DEHERM_DMSDK_SCRATCH_ENUM), { DEHERM_DMSDK_SCRATCH_HANDLE, DEHERM_DMSDK_SCRATCH_U16, DEHERM_DMSDK_SCRATCH_U64, 0 }, { DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_INOUT, 0 }, { UINT16_C(0), DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetComponentId@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:673:1013" },
  { UINT16_C(1), UINT8_C(4), UINT8_C(3), UINT8_C(1), UINT8_C(DEHERM_DMSDK_SCRATCH_ENUM), { DEHERM_DMSDK_SCRATCH_HANDLE, DEHERM_DMSDK_SCRATCH_U64, DEHERM_DMSDK_SCRATCH_U64, DEHERM_DMSDK_SCRATCH_BOOL }, { DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_OUT }, { UINT16_C(0), DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetPropertyAsBool@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:993:1048" },
  { UINT16_C(2), UINT8_C(4), UINT8_C(3), UINT8_C(1), UINT8_C(DEHERM_DMSDK_SCRATCH_ENUM), { DEHERM_DMSDK_SCRATCH_HANDLE, DEHERM_DMSDK_SCRATCH_U64, DEHERM_DMSDK_SCRATCH_U64, DEHERM_DMSDK_SCRATCH_F32 }, { DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_OUT }, { UINT16_C(0), DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetPropertyAsFloat@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:949:1044" },
  { UINT16_C(3), UINT8_C(4), UINT8_C(3), UINT8_C(1), UINT8_C(DEHERM_DMSDK_SCRATCH_ENUM), { DEHERM_DMSDK_SCRATCH_HANDLE, DEHERM_DMSDK_SCRATCH_U64, DEHERM_DMSDK_SCRATCH_U64, DEHERM_DMSDK_SCRATCH_U64 }, { DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_OUT }, { UINT16_C(0), DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetPropertyAsHash@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:938:1043" },
  { UINT16_C(4), UINT8_C(3), UINT8_C(2), UINT8_C(1), UINT8_C(DEHERM_DMSDK_SCRATCH_ENUM), { DEHERM_DMSDK_SCRATCH_HANDLE, DEHERM_DMSDK_SCRATCH_U32, DEHERM_DMSDK_SCRATCH_I32, 0 }, { DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_OUT, 0 }, { UINT16_C(1), DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetPropertyOptionsIndex@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:917:1041" },
  { UINT16_C(5), UINT8_C(3), UINT8_C(2), UINT8_C(1), UINT8_C(DEHERM_DMSDK_SCRATCH_ENUM), { DEHERM_DMSDK_SCRATCH_HANDLE, DEHERM_DMSDK_SCRATCH_U32, DEHERM_DMSDK_SCRATCH_U64, 0 }, { DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_OUT, 0 }, { UINT16_C(1), DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetPropertyOptionsKey@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:927:1042" },
  { UINT16_C(6), UINT8_C(3), UINT8_C(2), UINT8_C(1), UINT8_C(DEHERM_DMSDK_SCRATCH_BOOL), { DEHERM_DMSDK_SCRATCH_HANDLE, DEHERM_DMSDK_SCRATCH_HANDLE, DEHERM_DMSDK_SCRATCH_U32, 0 }, { DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_VALUE, DEHERM_DMSDK_SCRATCH_OUT, 0 }, { UINT16_C(2), UINT16_C(3), DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND, DEHERM_DMSDK_SCRATCH_NO_HANDLE_KIND }, "dmsdk:dmHID::GetGamepadUserId@upstream/defold/engine/hid/src/dmsdk/hid/hid.h:619:1616" }
};
const DehermDmSdkScratchHandleKind kHandleKinds[] = {
  { UINT16_C(0), "dmGameObject::HInstance", "opaque" },
  { UINT16_C(1), "dmGameObject::HPropertyOptions", "opaque" },
  { UINT16_C(2), "dmHID::HContext", "opaque" },
  { UINT16_C(3), "dmHID::HGamepad", "opaque" }
};
DehermDmSdkScratchProvider gProvider = {};
thread_local bool gDispatchActive = false;
bool validLane(uint8_t kind, uint64_t value) {
  if (kind == DEHERM_DMSDK_SCRATCH_BOOL) return value <= UINT64_C(1);
  if (kind == DEHERM_DMSDK_SCRATCH_U16) return value <= UINT64_C(0xffff);
  if (kind == DEHERM_DMSDK_SCRATCH_U32 || kind == DEHERM_DMSDK_SCRATCH_F32) return value <= UINT64_C(0xffffffff);
  if (kind == DEHERM_DMSDK_SCRATCH_I32 || kind == DEHERM_DMSDK_SCRATCH_ENUM) return value == static_cast<uint64_t>(static_cast<int64_t>(static_cast<int32_t>(value)));
  return true;
}
void clearWritable(const DehermDmSdkScratchDescriptor& descriptor, uint64_t* slots) { for (uint32_t index=0; index<descriptor.parameter_count; ++index) if (descriptor.parameter_directions[index] == DEHERM_DMSDK_SCRATCH_OUT || descriptor.parameter_directions[index] == DEHERM_DMSDK_SCRATCH_INOUT) slots[index]=0; }
struct DispatchScope { DispatchScope(){gDispatchActive=true;} ~DispatchScope(){gDispatchActive=false;} };
}
extern "C" {
uint32_t deherm_dmsdk_scratch_count(void) { return UINT32_C(7); }
const DehermDmSdkScratchDescriptor* deherm_dmsdk_scratch_descriptors(void) { return kDescriptors; }
uint32_t deherm_dmsdk_scratch_handle_kind_count(void) { return UINT32_C(4); }
const DehermDmSdkScratchHandleKind* deherm_dmsdk_scratch_handle_kinds(void) { return kHandleKinds; }
DehermDmSdkScratchStatus deherm_dmsdk_scratch_set_provider(const DehermDmSdkScratchProvider* provider) {
  if (provider == nullptr) { memset(&gProvider, 0, sizeof(gProvider)); return DEHERM_DMSDK_SCRATCH_OK; }
  if (provider->abi_version != DEHERM_DMSDK_SCRATCH_PROVIDER_ABI || provider->is_current_thread == nullptr || provider->validate_handle == nullptr || provider->invoke == nullptr) return DEHERM_DMSDK_SCRATCH_INVALID_PROVIDER;
  gProvider = *provider; return DEHERM_DMSDK_SCRATCH_OK;
}
DehermDmSdkScratchStatus deherm_dmsdk_scratch_dispatch(uint16_t id, uint64_t* slots, uint32_t parameter_count, uint64_t* out_result) {
  if (id >= deherm_dmsdk_scratch_count()) return DEHERM_DMSDK_SCRATCH_UNKNOWN_ID;
  const DehermDmSdkScratchDescriptor& descriptor = kDescriptors[id];
  if (parameter_count != descriptor.parameter_count) return DEHERM_DMSDK_SCRATCH_WRONG_ARITY;
  if (slots == nullptr || out_result == nullptr) return DEHERM_DMSDK_SCRATCH_NULL_STORAGE;
  *out_result = 0;
  for (uint32_t index=0; index<parameter_count; ++index) if (descriptor.parameter_directions[index] == DEHERM_DMSDK_SCRATCH_OUT) slots[index]=0;
  if (gProvider.invoke == nullptr) { clearWritable(descriptor, slots); return DEHERM_DMSDK_SCRATCH_PROVIDER_MISSING; }
  if (gDispatchActive) { clearWritable(descriptor, slots); return DEHERM_DMSDK_SCRATCH_REENTRANT; }
  if (gProvider.is_current_thread(gProvider.context) == 0) { clearWritable(descriptor, slots); return DEHERM_DMSDK_SCRATCH_WRONG_THREAD; }
  for (uint32_t index=0; index<parameter_count; ++index) {
    if (descriptor.parameter_directions[index] != DEHERM_DMSDK_SCRATCH_OUT && !validLane(descriptor.parameter_kinds[index], slots[index])) { clearWritable(descriptor, slots); return DEHERM_DMSDK_SCRATCH_INVALID_LANE; }
    if (descriptor.parameter_kinds[index] == DEHERM_DMSDK_SCRATCH_HANDLE && (slots[index] == 0 || gProvider.validate_handle(gProvider.context, descriptor.handle_kinds[index], slots[index]) == 0)) { clearWritable(descriptor, slots); return DEHERM_DMSDK_SCRATCH_INVALID_HANDLE; }
  }
  DispatchScope scope;
  const DehermDmSdkScratchStatus status = gProvider.invoke(gProvider.context, id, slots, parameter_count, out_result);
  if (status != DEHERM_DMSDK_SCRATCH_OK || !validLane(descriptor.result_kind, *out_result)) { clearWritable(descriptor, slots); *out_result=0; return status == DEHERM_DMSDK_SCRATCH_OK ? DEHERM_DMSDK_SCRATCH_INVALID_LANE : status; }
  for (uint32_t index=0; index<parameter_count; ++index) if ((descriptor.parameter_directions[index] == DEHERM_DMSDK_SCRATCH_OUT || descriptor.parameter_directions[index] == DEHERM_DMSDK_SCRATCH_INOUT) && !validLane(descriptor.parameter_kinds[index], slots[index])) { clearWritable(descriptor, slots); *out_result=0; return DEHERM_DMSDK_SCRATCH_INVALID_LANE; }
  return DEHERM_DMSDK_SCRATCH_OK;
}
}
