// Generated by scripts/generate-dmsdk-base64-span-bindings.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_base64_span.h>
#include <defold_hermes/generated_dmsdk_base64_span_runtime.h>
namespace {
uint8_t sextet(uint8_t value) {
  if (value >= 'A' && value <= 'Z') return value - 'A';
  if (value >= 'a' && value <= 'z') return value - 'a' + UINT8_C(26);
  if (value >= '0' && value <= '9') return value - '0' + UINT8_C(52);
  if (value == '+') return UINT8_C(62);
  if (value == '/') return UINT8_C(63);
  return UINT8_MAX;
}
bool canonical(const uint8_t* input, uint32_t length) {
  if ((length & UINT32_C(3)) != 0) return false;
  uint32_t padding = 0;
  if (length && input[length - 1] == '=') ++padding;
  if (length > 1 && input[length - 2] == '=') ++padding;
  if (padding > 2) return false;
  for (uint32_t index = 0; index < length - padding; ++index) {
    if (sextet(input[index]) == UINT8_MAX) return false;
  }
  for (uint32_t index = length - padding; index < length; ++index) {
    if (input[index] != '=') return false;
  }
  if (padding == 2 && (sextet(input[length - 3]) & UINT8_C(0x0f)) != 0) return false;
  if (padding == 1 && (sextet(input[length - 2]) & UINT8_C(0x03)) != 0) return false;
  return true;
}
const DehermDmSdkBase64SpanDescriptor kDescriptors[] = {
  { UINT16_C(0), UINT8_C(1), "dmsdk:dmCrypt::Base64Decode@upstream/defold/engine/dlib/src/dmsdk/dlib/crypt.h:133:162" },
  { UINT16_C(1), UINT8_C(0), "dmsdk:dmCrypt::Base64Encode@upstream/defold/engine/dlib/src/dmsdk/dlib/crypt.h:120:161" }
};
}
extern "C" {
uint32_t deherm_dmsdk_base64_span_count(void) { return UINT32_C(2); }
const DehermDmSdkBase64SpanDescriptor* deherm_dmsdk_base64_span_descriptors(void) { return kDescriptors; }
DehermDmSdkBase64SpanStatus deherm_dmsdk_base64_span_dispatch(uint16_t id, const uint8_t* input, uint32_t input_length, uint8_t* output, uint32_t output_capacity, uint32_t* out_written) {
  if (id >= deherm_dmsdk_base64_span_count()) return DEHERM_DMSDK_BASE64_SPAN_UNKNOWN_ID;
  if (out_written == nullptr || (input_length != 0 && input == nullptr) || (output_capacity != 0 && output == nullptr)) return DEHERM_DMSDK_BASE64_SPAN_NULL_STORAGE;
  if (kDescriptors[id].requires_padded_input && !canonical(input,input_length)) return DEHERM_DMSDK_BASE64_SPAN_NONCANONICAL_INPUT;
  uint32_t written=output_capacity; uint8_t success=0;
  switch (id) {
    case 0: success=deherm_dmsdk_base64_span_dm_crypt_base64_decode(input,input_length,output,&written); break;
    case 1: success=deherm_dmsdk_base64_span_dm_crypt_base64_encode(input,input_length,output,&written); break;
    default: return DEHERM_DMSDK_BASE64_SPAN_UNKNOWN_ID;
  }
  *out_written=written;
  if (output_capacity == 0) return DEHERM_DMSDK_BASE64_SPAN_QUERY;
  return success ? DEHERM_DMSDK_BASE64_SPAN_OK : DEHERM_DMSDK_BASE64_SPAN_NATIVE_FAILURE;
}
}
