// Generated by scripts/generate-dmsdk-scalar-thunks.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_scalar.h>
#ifndef DLIB_LOG_DOMAIN
#define DLIB_LOG_DOMAIN "defold_hermes"
#endif
#include <dmsdk/dlib/time.h>

extern "C" {

uint64_t deherm_dmsdk_dm_time_get_monotonic_time_v(void)
{
    return dmTime::GetMonotonicTime();
}

uint64_t deherm_dmsdk_dm_time_get_time_v(void)
{
    return dmTime::GetTime();
}

void deherm_dmsdk_dm_time_sleep_u32(uint32_t useconds)
{
    dmTime::Sleep(useconds);
}

} // extern "C"
