// Generated by scripts/generate-script-dynamic-values.mjs. Do not edit.
#include <defold_hermes/generated_script_dynamic_values.hpp>
#include <cstdio>

namespace defold_hermes::dynamic_value { namespace {
constexpr Operation kOperations[] = {
  {0, 0x0892398eu, "script:bit.bor", "bit", "bor", Strategy::kExactLuaCall, ResultMode::kNumber, 1, 32},
  {1, 0x206a89bau, "script:types.is_hash", "types", "is_hash", Strategy::kExactLuaTypeQuery, ResultMode::kBoolean, 0, 32},
  {2, 0x7872f480u, "script:bit.band", "bit", "band", Strategy::kExactLuaCall, ResultMode::kNumber, 1, 32},
  {3, 0x948f508cu, "script:bit.bxor", "bit", "bxor", Strategy::kExactLuaCall, ResultMode::kNumber, 1, 32},
  {4, 0x9acd4145u, "script:types.is_matrix4", "types", "is_matrix4", Strategy::kExactLuaTypeQuery, ResultMode::kBoolean, 0, 32},
  {5, 0x9b0d4932u, "script:socket.skip", "socket", "skip", Strategy::kExactLuaCall, ResultMode::kVariableValues, 1, 32},
  {6, 0xc6f91f35u, "script:types.is_quat", "types", "is_quat", Strategy::kExactLuaTypeQuery, ResultMode::kBoolean, 0, 32},
  {7, 0xc8496cbdu, "script:types.is_vector", "types", "is_vector", Strategy::kExactLuaTypeQuery, ResultMode::kBoolean, 0, 32},
  {8, 0xd495dbabu, "script:types.is_vector4", "types", "is_vector4", Strategy::kExactLuaTypeQuery, ResultMode::kBoolean, 0, 32},
  {9, 0xd995e38au, "script:types.is_vector3", "types", "is_vector3", Strategy::kExactLuaTypeQuery, ResultMode::kBoolean, 0, 32},
  {10, 0xfaf3e587u, "script:types.is_url", "types", "is_url", Strategy::kExactLuaTypeQuery, ResultMode::kBoolean, 0, 32},
};
void fail(char* error, size_t capacity, const char* message) noexcept { if (error && capacity) std::snprintf(error, capacity, "%s", message); }
bool resultMatches(const Operation& operation, const ScriptCallFrame& frame) noexcept {
  if (operation.resultMode == ResultMode::kVariableValues) return frame.resultCount <= frame.resultCapacity;
  if (frame.resultCount != 1 || !frame.results) return false;
  return operation.resultMode == ResultMode::kNumber ? frame.results[0].tag == ScriptValueTag::kNumber : frame.results[0].tag == ScriptValueTag::kBoolean;
}
}
const Operation* find(uint32_t stableId) noexcept { size_t first=0,count=kBindingCount; while(count){const size_t step=count/2,index=first+step;if(kOperations[index].stableId<stableId){first=index+1;count-=step+1;}else count=step;} return first<kBindingCount&&kOperations[first].stableId==stableId?&kOperations[first]:nullptr; }
DispatchStatus dispatch(ScriptCallFrame* frame, char* error, size_t capacity, const LuaApi* api) noexcept {
  if (!frame) { fail(error,capacity,"Dynamic-value call frame is null"); return DispatchStatus::kError; }
  const Operation* operation=find(frame->stableId); if(!operation) return DispatchStatus::kMissing; frame->resultCount=0;
  if(frame->argumentCount<operation->minimumArguments||frame->argumentCount>operation->maximumArguments||(frame->argumentCount&&!frame->arguments)){fail(error,capacity,"Dynamic-value argument count is outside the generated fixed capacity");return DispatchStatus::kError;}
  if(!frame->results||frame->resultCapacity==0){fail(error,capacity,"Dynamic-value result storage is exhausted");return DispatchStatus::kError;}
  if(!api||!api->invoke){fail(error,capacity,"Dynamic-value exact Lua backend is unavailable");return DispatchStatus::kError;}
  const DispatchStatus status=api->invoke(api->context,*operation,frame,error,capacity);
  if(status!=DispatchStatus::kSuccess){frame->resultCount=0;return status==DispatchStatus::kMissing?DispatchStatus::kError:status;}
  if(!resultMatches(*operation,*frame)){frame->resultCount=0;fail(error,capacity,"Dynamic-value Lua result does not match the generated result mode");return DispatchStatus::kError;}
  return DispatchStatus::kSuccess;
}
}
