// Generated by scripts/generate-dmsdk-scalar-thunks.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_scalar_jsi.hpp>

#if !defined(DM_PLATFORM_HTML5)
#include <defold_hermes/generated_dmsdk_scalar_runtime.h>

#include <cmath>
#include <cstring>
#include <utility>

namespace defold_hermes {
namespace jsi = facebook::jsi;
namespace {
bool isIntegerInRange(const jsi::Value& value, double maximum)
{
  return value.isNumber() && std::isfinite(value.asNumber()) &&
      std::trunc(value.asNumber()) == value.asNumber() &&
      value.asNumber() >= 0.0 && value.asNumber() <= maximum;
}

uint64_t encodeArgument(jsi::Runtime& runtime, const jsi::Value& value, uint8_t kind)
{
  switch (kind) {
    case DEHERM_DMSDK_SCALAR_BOOL:
      if (!value.isBool()) throw jsi::JSError(runtime, "dmSDK scalar argument must be boolean");
      return value.getBool() ? UINT64_C(1) : UINT64_C(0);
    case DEHERM_DMSDK_SCALAR_U16:
      if (!isIntegerInRange(value, 65535.0)) throw jsi::JSError(runtime, "dmSDK scalar argument must be u16");
      return static_cast<uint16_t>(value.asNumber());
    case DEHERM_DMSDK_SCALAR_U32:
      if (!isIntegerInRange(value, 4294967295.0)) throw jsi::JSError(runtime, "dmSDK scalar argument must be u32");
      return static_cast<uint32_t>(value.asNumber());
    case DEHERM_DMSDK_SCALAR_U64: {
      if (!value.isBigInt()) throw jsi::JSError(runtime, "dmSDK scalar argument must be u64 bigint");
      auto bigint = value.asBigInt(runtime);
      if (!bigint.isUint64(runtime)) throw jsi::JSError(runtime, "dmSDK scalar bigint is outside the u64 range");
      return bigint.asUint64(runtime);
    }
    case DEHERM_DMSDK_SCALAR_F32: {
      if (!value.isNumber() || !std::isfinite(value.asNumber())) throw jsi::JSError(runtime, "dmSDK scalar argument must be a finite f32");
      const float narrowed = static_cast<float>(value.asNumber());
      uint32_t bits = 0;
      std::memcpy(&bits, &narrowed, sizeof(bits));
      return bits;
    }
    default:
      throw jsi::JSError(runtime, "dmSDK scalar type is not JavaScript-callable");
  }
}

jsi::Value decodeResult(jsi::Runtime& runtime, uint8_t kind, uint64_t raw)
{
  switch (kind) {
    case DEHERM_DMSDK_SCALAR_VOID: return jsi::Value::undefined();
    case DEHERM_DMSDK_SCALAR_BOOL: return jsi::Value(raw != 0);
    case DEHERM_DMSDK_SCALAR_U16: return jsi::Value(static_cast<double>(static_cast<uint16_t>(raw)));
    case DEHERM_DMSDK_SCALAR_U32: return jsi::Value(static_cast<double>(static_cast<uint32_t>(raw)));
    case DEHERM_DMSDK_SCALAR_U64: return jsi::Value(runtime, jsi::BigInt::fromUint64(runtime, raw));
    case DEHERM_DMSDK_SCALAR_F32: {
      const uint32_t bits = static_cast<uint32_t>(raw);
      float value = 0.0f;
      std::memcpy(&value, &bits, sizeof(value));
      return jsi::Value(static_cast<double>(value));
    }
    default:
      throw jsi::JSError(runtime, "dmSDK scalar result is not JavaScript-callable");
  }
}
} // namespace

void installDmSdkScalarModule(jsi::Runtime& runtime, jsi::Object& modules)
{
  jsi::Object module(runtime);
  auto call = jsi::Function::createFromHostFunction(
      runtime, jsi::PropNameID::forAscii(runtime, "call"), 2,
      [](jsi::Runtime& runtime, const jsi::Value&, const jsi::Value* args, size_t count) {
        if (count < 1 || !isIntegerInRange(args[0], 65535.0)) {
          throw jsi::JSError(runtime, "DmSdkScalar.call expects a numeric binding id");
        }
        const uint16_t id = static_cast<uint16_t>(args[0].asNumber());
        if (id >= deherm_dmsdk_scalar_count()) throw jsi::JSError(runtime, "Unknown dmSDK scalar binding id");
        const DehermDmSdkScalarDescriptor& descriptor = deherm_dmsdk_scalar_descriptors()[id];
        if ((descriptor.flags & DEHERM_DMSDK_SCALAR_NATIVE_JS) == 0) {
          throw jsi::JSError(runtime, "dmSDK scalar binding requires a 64-bit adapter");
        }
        if (count != static_cast<size_t>(descriptor.argument_count) + 1) {
          throw jsi::JSError(runtime, "Wrong dmSDK scalar argument count");
        }
        uint64_t rawArguments[DEHERM_DMSDK_SCALAR_MAX_ARGUMENTS] = {};
        for (uint8_t index = 0; index < descriptor.argument_count; ++index) {
          rawArguments[index] = encodeArgument(runtime, args[index + 1], descriptor.argument_kinds[index]);
        }
        uint64_t rawResult = 0;
        const DehermDmSdkScalarStatus status = deherm_dmsdk_scalar_dispatch(
            id, rawArguments, descriptor.argument_count, &rawResult);
        if (status != DEHERM_DMSDK_SCALAR_OK) throw jsi::JSError(runtime, "dmSDK scalar dispatch failed");
        return decodeResult(runtime, descriptor.return_kind, rawResult);
      });
  module.setProperty(runtime, "call", std::move(call));
  modules.setProperty(runtime, "DmSdkScalar", std::move(module));
}

} // namespace defold_hermes
#endif // !DM_PLATFORM_HTML5
