// Generated by scripts/generate-dmsdk-astc-probe-bindings.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_astc_probe.h>
#include <dmsdk/dlib/image.h>
extern "C" {
uint8_t deherm_dmsdk_astc_probe_dm_image_get_astc_block_size(const uint8_t* input,uint32_t input_length,DehermDmSdkAstcProbeResult* out_result)
{
  if(input==nullptr||out_result==nullptr||input_length<UINT32_C(16))return UINT8_C(0); uint32_t width=0,height=0,depth=0; const bool valid=dmImage::GetAstcBlockSize(input,input_length,&width,&height,&depth); if(valid){out_result->width=width;out_result->height=height;out_result->depth=depth;} return valid ? UINT8_C(1) : UINT8_C(0);
}
uint8_t deherm_dmsdk_astc_probe_dm_image_get_astc_dimensions(const uint8_t* input,uint32_t input_length,DehermDmSdkAstcProbeResult* out_result)
{
  if(input==nullptr||out_result==nullptr||input_length<UINT32_C(16))return UINT8_C(0); uint32_t width=0,height=0,depth=0; const bool valid=dmImage::GetAstcDimensions(input,input_length,&width,&height,&depth); if(valid){out_result->width=width;out_result->height=height;out_result->depth=depth;} return valid ? UINT8_C(1) : UINT8_C(0);
} }
