// Generated by scripts/generate-script-universal-value-bindings.mjs. Do not edit.
#include <defold_hermes/generated_script_universal_static_frame.h>
#include <defold_hermes/generated_script_universal_value_capi.h>

#include <array>
#include <cstring>
#include <memory>
#include <new>

struct DehermScriptUniversalStaticFrame {
  bool used = false;
  std::array<DehermScriptUniversalValue, DEHERM_SCRIPT_UNIVERSAL_MAX_VALUES> input_values{};
  std::array<DehermScriptUniversalEntry, DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES> input_entries{};
  std::array<char, DEHERM_SCRIPT_STATIC_FRAME_STRING_BYTES> input_strings{};
  std::array<float, DEHERM_SCRIPT_UNIVERSAL_MAX_MATRIX4_VALUES * DEHERM_DEFOLD_MATRIX4_STORAGE_ELEMENTS> input_floats{};
  std::array<DehermScriptUniversalUrl, DEHERM_SCRIPT_UNIVERSAL_MAX_URL_VALUES> input_urls{};
  std::array<uint32_t, DEHERM_SCRIPT_UNIVERSAL_MAX_ARGUMENTS> argument_roots{};
  std::array<DehermScriptUniversalValue, DEHERM_SCRIPT_UNIVERSAL_MAX_VALUES> output_values{};
  std::array<DehermScriptUniversalEntry, DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES> output_entries{};
  std::array<char, DEHERM_SCRIPT_STATIC_FRAME_STRING_BYTES> output_strings{};
  std::array<float, DEHERM_SCRIPT_UNIVERSAL_MAX_MATRIX4_VALUES * 16> output_floats{};
  std::array<DehermScriptUniversalUrl, DEHERM_SCRIPT_UNIVERSAL_MAX_URL_VALUES> output_urls{};
  std::array<uint32_t, DEHERM_SCRIPT_UNIVERSAL_MAX_RESULTS> result_roots{};
  uint32_t input_value_count = 0;
  uint32_t input_entry_count = 0;
  uint32_t input_string_bytes = 0;
  uint32_t input_float_count = 0;
  uint32_t input_url_count = 0;
  uint32_t output_value_count = 0;
  uint32_t output_entry_count = 0;
  uint32_t output_string_bytes = 0;
  uint32_t output_float_count = 0;
  uint32_t output_url_count = 0;
  uint32_t result_count = 0;
  char error[256]{};
};

static_assert(DEHERM_SCRIPT_STATIC_FRAME_REENTRANCY > 0u,
    "Static Hermes frame pool needs at least one reentrant frame");
static_assert(DEHERM_SCRIPT_STATIC_FRAME_STRING_BYTES > 0u,
    "Static Hermes frame string scratch must be non-empty");
static_assert(sizeof(DehermScriptUniversalStaticFrame) <= UINT32_MAX,
    "Static Hermes frame byte reporting uses uint32_t");
static_assert(sizeof(DehermScriptUniversalStaticFrame) * DEHERM_SCRIPT_STATIC_FRAME_REENTRANCY <= UINT32_MAX,
    "Static Hermes frame pool byte reporting uses uint32_t");
static_assert(sizeof(DehermScriptUniversalUrl) == DEHERM_DEFOLD_URL_BYTES,
    "Static Hermes URL scratch drifted from the pinned dmMessage::URL layout");
static_assert(sizeof(float) * DEHERM_DEFOLD_MATRIX4_STORAGE_ELEMENTS == DEHERM_DEFOLD_MATRIX4_BYTES,
    "Static Hermes Matrix4 scratch drifted from the pinned dmVMath::Matrix4 layout");

namespace {
using StaticFramePool = std::array<DehermScriptUniversalStaticFrame, DEHERM_SCRIPT_STATIC_FRAME_REENTRANCY>;
// Keep only the pool owner in static TLS. Embedding the complete ~368 KiB pool
// there makes glibc count it against every pthread's requested stack, including
// Defold's 128 KiB AsyncLoad thread, so pthread_create rejects that otherwise
// valid engine thread with EINVAL before any Hermes route can execute.
thread_local std::unique_ptr<StaticFramePool> frames;
constexpr uint32_t invalid = UINT32_MAX;

DehermScriptUniversalValue* add(DehermScriptUniversalStaticFrame* frame, uint32_t* index) noexcept {
  if (!frame || frame->input_value_count >= frame->input_values.size()) return nullptr;
  *index = frame->input_value_count++;
  auto* value = &frame->input_values[*index];
  *value = {};
  return value;
}
const DehermScriptUniversalValue* value(const DehermScriptUniversalStaticFrame* frame, uint32_t index) noexcept {
  return frame && index < frame->output_value_count ? &frame->output_values[index] : nullptr;
}
}

extern "C" DehermScriptUniversalStaticFrame* deherm_script_static_frame_acquire(void) {
  if (!frames) frames.reset(new (std::nothrow) StaticFramePool{});
  if (!frames) return nullptr;
  for (auto& frame : *frames) if (!frame.used) { frame.used = true; deherm_script_static_frame_reset(&frame); return &frame; }
  return nullptr;
}
extern "C" uint32_t deherm_script_static_frame_bytes(void) { return static_cast<uint32_t>(sizeof(DehermScriptUniversalStaticFrame)); }
extern "C" uint32_t deherm_script_static_frame_pool_bytes(void) { return static_cast<uint32_t>(sizeof(StaticFramePool)); }
extern "C" void deherm_script_static_frame_release(DehermScriptUniversalStaticFrame* frame) { if (frame) { deherm_script_static_frame_reset(frame); frame->used = false; } }
extern "C" void deherm_script_static_frame_reset(DehermScriptUniversalStaticFrame* frame) {
  if (!frame) return;
  frame->input_value_count = frame->input_entry_count = frame->input_string_bytes = 0;
  frame->input_float_count = frame->input_url_count = 0;
  frame->output_value_count = frame->output_entry_count = frame->output_string_bytes = 0;
  frame->output_float_count = frame->output_url_count = frame->result_count = 0;
  frame->error[0] = 0;
}
#define PUSH_SCALAR(name, tagValue, assignment) extern "C" uint32_t name(DehermScriptUniversalStaticFrame* frame assignment) { uint32_t index; auto* out = add(frame, &index); if (!out) return invalid; out->tag = tagValue; return index; }
PUSH_SCALAR(deherm_script_static_push_undefined, 0, )
PUSH_SCALAR(deherm_script_static_push_null, 1, )
extern "C" uint32_t deherm_script_static_push_boolean(DehermScriptUniversalStaticFrame* frame, uint8_t input) { uint32_t index; auto* out = add(frame, &index); if (!out) return invalid; out->tag = 2; out->number = input ? 1 : 0; return index; }
extern "C" uint32_t deherm_script_static_push_number(DehermScriptUniversalStaticFrame* frame, double input) { uint32_t index; auto* out = add(frame, &index); if (!out) return invalid; out->tag = 3; out->number = input; return index; }
extern "C" uint32_t deherm_script_static_push_string(DehermScriptUniversalStaticFrame* frame, uint32_t length) { if (!frame || length > frame->input_strings.size() - frame->input_string_bytes) return invalid; uint32_t index; auto* out = add(frame, &index); if (!out) return invalid; out->tag = 4; out->length = length; out->data_offset = frame->input_string_bytes; frame->input_string_bytes += length; return index; }
extern "C" uint8_t deherm_script_static_write_string_byte(DehermScriptUniversalStaticFrame* frame, uint32_t index, uint32_t offset, uint8_t input) { if (!frame || index >= frame->input_value_count) return 0; const auto& item = frame->input_values[index]; if (item.tag != 4 || offset >= item.length) return 0; frame->input_strings[item.data_offset + offset] = static_cast<char>(input); return 1; }
extern "C" uint32_t deherm_script_static_push_handle(DehermScriptUniversalStaticFrame* frame, uint8_t kind, uint8_t semantic, uint32_t runtime, uint32_t low, uint32_t high) { uint32_t index; auto* out = add(frame, &index); if (!out) return invalid; out->tag = 5; out->handle_kind = kind; out->auxiliary = semantic; out->runtime = runtime; out->payload = (static_cast<uint64_t>(high) << 32u) | low; return index; }
extern "C" uint32_t deherm_script_static_push_defold_value(DehermScriptUniversalStaticFrame* frame, uint8_t kind, float x, float y, float z, float w) { uint32_t index; auto* out = add(frame, &index); if (!out) return invalid; out->tag = 8; out->defold_kind = kind; out->lanes[0]=x; out->lanes[1]=y; out->lanes[2]=z; out->lanes[3]=w; return index; }
extern "C" uint32_t deherm_script_static_push_matrix4(DehermScriptUniversalStaticFrame* frame, float e0, float e1, float e2, float e3, float e4, float e5, float e6, float e7, float e8, float e9, float e10, float e11, float e12, float e13, float e14, float e15) { if (!frame || DEHERM_DEFOLD_MATRIX4_STORAGE_ELEMENTS > frame->input_floats.size() - frame->input_float_count) return invalid; uint32_t index; auto* out = add(frame, &index); if (!out) return invalid; const float elements[DEHERM_DEFOLD_MATRIX4_STORAGE_ELEMENTS] = {e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15}; out->tag = 8; out->defold_kind = 4; out->data_offset = frame->input_float_count; out->length = DEHERM_DEFOLD_MATRIX4_STORAGE_ELEMENTS; std::memcpy(frame->input_floats.data() + frame->input_float_count, elements, sizeof(elements)); frame->input_float_count += DEHERM_DEFOLD_MATRIX4_STORAGE_ELEMENTS; return index; }
extern "C" uint32_t deherm_script_static_push_url(DehermScriptUniversalStaticFrame* frame, uint32_t socket_low, uint32_t socket_high, uint32_t reserved_low, uint32_t reserved_high, uint32_t path_low, uint32_t path_high, uint32_t fragment_low, uint32_t fragment_high) { if (!frame || frame->input_url_count >= frame->input_urls.size()) return invalid; uint32_t index; auto* out = add(frame, &index); if (!out) return invalid; const uint32_t slot = frame->input_url_count++; frame->input_urls[slot] = {(static_cast<uint64_t>(socket_high) << 32u) | socket_low, (static_cast<uint64_t>(reserved_high) << 32u) | reserved_low, (static_cast<uint64_t>(path_high) << 32u) | path_low, (static_cast<uint64_t>(fragment_high) << 32u) | fragment_low}; out->tag = 5; out->handle_kind = 2; out->data_offset = slot; out->length = 1; return index; }
extern "C" uint32_t deherm_script_static_push_table(DehermScriptUniversalStaticFrame* frame, uint8_t kind, uint32_t length) { if (!frame || length > frame->input_entries.size() - frame->input_entry_count) return invalid; uint32_t index; auto* out = add(frame, &index); if (!out) return invalid; out->tag = 7; out->auxiliary = kind; out->data_offset = frame->input_entry_count; out->length = length; frame->input_entry_count += length; return index; }
extern "C" uint8_t deherm_script_static_set_entry(DehermScriptUniversalStaticFrame* frame, uint32_t table, uint32_t entry, uint32_t key, uint32_t child) { if (!frame || table >= frame->input_value_count || key >= frame->input_value_count || child >= frame->input_value_count) return 0; auto& owner=frame->input_values[table]; if (owner.tag != 7 || entry >= owner.length || owner.data_offset + entry >= frame->input_entry_count) return 0; frame->input_entries[owner.data_offset+entry]={key,child}; return 1; }
extern "C" uint8_t deherm_script_static_set_argument(DehermScriptUniversalStaticFrame* frame, uint32_t slot, uint32_t index) { if (!frame || slot >= frame->argument_roots.size() || index >= frame->input_value_count) return 0; frame->argument_roots[slot]=index; return 1; }
extern "C" uint32_t deherm_script_static_dispatch(DehermScriptUniversalStaticFrame* frame, uint32_t stable, uint32_t count) { if (!frame || count > frame->argument_roots.size()) return DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE; return deherm_script_universal_dispatch(stable, frame->input_values.data(), frame->input_value_count, frame->input_entries.data(), frame->input_entry_count, frame->input_strings.data(), frame->input_string_bytes, frame->input_floats.data(), frame->input_float_count, frame->input_urls.data(), frame->input_url_count, frame->argument_roots.data(), count, frame->output_values.data(), frame->output_values.size(), &frame->output_value_count, frame->output_entries.data(), frame->output_entries.size(), &frame->output_entry_count, frame->output_strings.data(), frame->output_strings.size(), &frame->output_string_bytes, frame->output_floats.data(), frame->output_floats.size(), &frame->output_float_count, frame->output_urls.data(), frame->output_urls.size(), &frame->output_url_count, frame->result_roots.data(), frame->result_roots.size(), &frame->result_count, frame->error, sizeof(frame->error)); }
extern "C" uint32_t deherm_script_static_result_count(const DehermScriptUniversalStaticFrame* f){return f?f->result_count:0;} extern "C" uint32_t deherm_script_static_result_root(const DehermScriptUniversalStaticFrame* f,uint32_t i){return f&&i<f->result_count?f->result_roots[i]:invalid;}
extern "C" uint8_t deherm_script_static_value_tag(const DehermScriptUniversalStaticFrame* f,uint32_t i){auto*v=value(f,i);return v?v->tag:255;} extern "C" uint8_t deherm_script_static_value_auxiliary(const DehermScriptUniversalStaticFrame* f,uint32_t i){auto*v=value(f,i);return v?v->auxiliary:0;} extern "C" uint8_t deherm_script_static_value_handle_kind(const DehermScriptUniversalStaticFrame* f,uint32_t i){auto*v=value(f,i);return v?v->handle_kind:0;} extern "C" uint8_t deherm_script_static_value_defold_kind(const DehermScriptUniversalStaticFrame* f,uint32_t i){auto*v=value(f,i);return v?v->defold_kind:0;}
extern "C" uint32_t deherm_script_static_value_length(const DehermScriptUniversalStaticFrame* f,uint32_t i){auto*v=value(f,i);return v?v->length:0;} extern "C" double deherm_script_static_value_number(const DehermScriptUniversalStaticFrame* f,uint32_t i){auto*v=value(f,i);return v?v->number:0;} extern "C" uint32_t deherm_script_static_value_payload_low(const DehermScriptUniversalStaticFrame* f,uint32_t i){auto*v=value(f,i);return v?static_cast<uint32_t>(v->payload):0;} extern "C" uint32_t deherm_script_static_value_payload_high(const DehermScriptUniversalStaticFrame* f,uint32_t i){auto*v=value(f,i);return v?static_cast<uint32_t>(v->payload>>32u):0;} extern "C" uint32_t deherm_script_static_value_runtime(const DehermScriptUniversalStaticFrame* f,uint32_t i){auto*v=value(f,i);return v?v->runtime:0;}
extern "C" void deherm_script_static_release_handle(uint8_t kind,uint32_t runtime,uint32_t low,uint32_t high){DehermScriptUniversalValue item{};item.tag=5;item.handle_kind=kind;item.runtime=runtime;item.payload=(static_cast<uint64_t>(high)<<32u)|low;deherm_script_universal_release(&item);}
extern "C" float deherm_script_static_value_lane(const DehermScriptUniversalStaticFrame* f,uint32_t i,uint32_t lane){auto*v=value(f,i);return v&&lane<4?v->lanes[lane]:0;}
extern "C" float deherm_script_static_value_element(const DehermScriptUniversalStaticFrame* f,uint32_t i,uint32_t element){auto*v=value(f,i);if(!v||v->tag!=8||v->defold_kind!=4||element>=v->length||v->length!=DEHERM_DEFOLD_MATRIX4_STORAGE_ELEMENTS||v->length>f->output_float_count||v->data_offset>f->output_float_count-v->length)return 0;return f->output_floats[v->data_offset+element];}
extern "C" uint32_t deherm_script_static_value_url_low(const DehermScriptUniversalStaticFrame* f,uint32_t i,uint32_t lane){auto*v=value(f,i);if(!v||v->tag!=5||v->handle_kind!=2||lane>=DEHERM_DEFOLD_URL_SEMANTIC_LANES||v->data_offset>=f->output_url_count)return 0;const auto&u=f->output_urls[v->data_offset];const uint64_t lanes[DEHERM_DEFOLD_URL_SEMANTIC_LANES]={u.socket, u.reserved, u.path, u.fragment};return static_cast<uint32_t>(lanes[lane]);}
extern "C" uint32_t deherm_script_static_value_url_high(const DehermScriptUniversalStaticFrame* f,uint32_t i,uint32_t lane){auto*v=value(f,i);if(!v||v->tag!=5||v->handle_kind!=2||lane>=DEHERM_DEFOLD_URL_SEMANTIC_LANES||v->data_offset>=f->output_url_count)return 0;const auto&u=f->output_urls[v->data_offset];const uint64_t lanes[DEHERM_DEFOLD_URL_SEMANTIC_LANES]={u.socket, u.reserved, u.path, u.fragment};return static_cast<uint32_t>(lanes[lane]>>32u);}
extern "C" char* deherm_script_static_value_string(DehermScriptUniversalStaticFrame* f,uint32_t i){auto*v=value(f,i);return v&&v->tag==4&&v->data_offset<=f->output_string_bytes&&v->length<=f->output_string_bytes-v->data_offset?f->output_strings.data()+v->data_offset:nullptr;}
extern "C" uint32_t deherm_script_static_entry_key(const DehermScriptUniversalStaticFrame* f,uint32_t i,uint32_t e){auto*v=value(f,i);return v&&v->tag==7&&e<v->length&&v->data_offset+e<f->output_entry_count?f->output_entries[v->data_offset+e].key_index:invalid;} extern "C" uint32_t deherm_script_static_entry_value(const DehermScriptUniversalStaticFrame* f,uint32_t i,uint32_t e){auto*v=value(f,i);return v&&v->tag==7&&e<v->length&&v->data_offset+e<f->output_entry_count?f->output_entries[v->data_offset+e].value_index:invalid;} extern "C" char* deherm_script_static_error(DehermScriptUniversalStaticFrame* f){static char unavailable[]="Static frame unavailable";return f?f->error:unavailable;}
