// Generated by scripts/generate-dmsdk-scalar-thunks.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_scalar.h>
#ifndef DLIB_LOG_DOMAIN
#define DLIB_LOG_DOMAIN "defold_hermes"
#endif
#include <dmsdk/dlib/trig_lookup.h>

extern "C" {

float deherm_dmsdk_dm_trig_lookup_cos_f32(float radians)
{
    return dmTrigLookup::Cos(radians);
}

float deherm_dmsdk_dm_trig_lookup_sin_f32(float radians)
{
    return dmTrigLookup::Sin(radians);
}

} // extern "C"
