// Generated by scripts/generate-script-universal-value-bindings.mjs. Do not edit.
#include <defold_hermes/generated_script_universal_value_bindings.hpp>

#include <cstdio>

namespace defold_hermes::universal_value {
namespace {
constexpr Operation kOperations[] = {
  {0x00283b48u, "script:physics.raycast", "physics", "raycast", 3, 4, 1},
  {0x03af0f86u, "script:b2d.joint.create_motor", "b2d.joint", "create_motor", 2, 3, 1},
  {0x04d9692du, "script:b2d.world.cast_mover", "b2d.world", "cast_mover", 3, 4, 1},
  {0x0648b4c4u, "script:b2d.joint.create_pulley", "b2d.joint", "create_pulley", 2, 3, 1},
  {0x06853223u, "script:resource.create_sound_data", "resource", "create_sound_data", 1, 2, 1},
  {0x090c69ffu, "script:bullet3d.world.overlap_aabb", "bullet3d.world", "overlap_aabb", 2, 4, 1},
  {0x092b4990u, "script:b2d.body.get_contact_data", "b2d.body", "get_contact_data", 1, 1, 1},
  {0x0a4697d5u, "script:image.load", "image", "load", 1, 2, 1},
  {0x0d3d20a5u, "script:gui.set", "gui", "set", 2, 4, 0},
  {0x0e33bb5du, "script:socket.select", "socket", "select", 2, 3, 3},
  {0x14faa9dcu, "script:timer.get_info", "timer", "get_info", 1, 1, 1},
  {0x1556cbdcu, "script:bullet3d.constraint.create_hinge2", "bullet3d.constraint", "create_hinge2", 3, 3, 1},
  {0x15c6b6d3u, "script:b2d.joint.create_filter", "b2d.joint", "create_filter", 2, 3, 1},
  {0x16219374u, "script:b2d.chain.get_segments", "b2d.chain", "get_segments", 1, 1, 1},
  {0x1a9e1611u, "script:resource.set_buffer", "resource", "set_buffer", 2, 3, 0},
  {0x1aa5bfd7u, "script:b2d.shape.set_shape", "b2d.shape", "set_shape", 3, 3, 0},
  {0x1bd4ee21u, "script:sys.serialize", "sys", "serialize", 1, 1, 1},
  {0x1dc3ddf9u, "script:bullet3d.world.overlap_point", "bullet3d.world", "overlap_point", 2, 4, 1},
  {0x1e674bf3u, "script:b2d.shape.get_shape", "b2d.shape", "get_shape", 1, 1, 1},
  {0x1ee00607u, "script:b2d.joint.create_friction", "b2d.joint", "create_friction", 2, 3, 1},
  {0x211ed173u, "script:b2d.shape.get_contact_data", "b2d.shape", "get_contact_data", 1, 1, 1},
  {0x21361460u, "script:socket.tcp", "socket", "tcp", 0, 0, 2},
  {0x217b7098u, "script:b2d.world.collide_mover", "b2d.world", "collide_mover", 2, 4, 1},
  {0x22c26193u, "script:render.clear", "render", "clear", 1, 1, 0},
  {0x25121c36u, "script:model.get_aabb", "model", "get_aabb", 1, 1, 1},
  {0x268f477eu, "script:resource.create_texture", "resource", "create_texture", 2, 3, 1},
  {0x2778ab3eu, "script:b2d.body.get_mass_data", "b2d.body", "get_mass_data", 1, 1, 1},
  {0x28bf1f99u, "script:gui.get", "gui", "get", 2, 3, 0},
  {0x28c7f935u, "script:resource.create_buffer", "resource", "create_buffer", 2, 2, 1},
  {0x2a1f515eu, "script:b2d.joint.create_distance", "b2d.joint", "create_distance", 2, 3, 1},
  {0x2ef001fdu, "script:render.set_render_target", "render", "set_render_target", 0, 2, 0},
  {0x2f995668u, "script:sys.save", "sys", "save", 2, 2, 0},
  {0x32303967u, "script:b2d.body.get_transform", "b2d.body", "get_transform", 1, 1, 1},
  {0x32bfedabu, "script:sound.stop", "sound", "stop", 1, 2, 0},
  {0x3823d7b8u, "script:b2d.fixture.get_aabb", "b2d.fixture", "get_aabb", 3, 3, 1},
  {0x383c7411u, "script:b2d.fixture.set_filter_data", "b2d.fixture", "set_filter_data", 4, 4, 0},
  {0x3bb43612u, "script:camera.get_cameras", "camera", "get_cameras", 0, 0, 1},
  {0x3dfcbbe9u, "script:material.set_constants", "material", "set_constants", 2, 2, 0},
  {0x3ed92129u, "script:socket.connect", "socket", "connect", 2, 5, 2},
  {0x3fc7b706u, "script:material.get_vertex_attributes", "material", "get_vertex_attributes", 1, 1, 1},
  {0x40fce313u, "script:b2d.body.get_shapes", "b2d.body", "get_shapes", 1, 1, 1},
  {0x4144ac04u, "script:bullet3d.constraint.create_cone_twist", "bullet3d.constraint", "create_cone_twist", 2, 3, 1},
  {0x442f1e83u, "script:b2d.fixture.get_shape", "b2d.fixture", "get_shape", 2, 2, 1},
  {0x46075371u, "script:sys.get_ifaddrs", "sys", "get_ifaddrs", 0, 0, 1},
  {0x48bd6d25u, "script:physics.get_shape", "physics", "get_shape", 2, 2, 1},
  {0x4a27bbbfu, "script:crash.get_modules", "crash", "get_modules", 1, 1, 1},
  {0x4b1b9b09u, "script:sys.load", "sys", "load", 1, 1, 1},
  {0x4be28d1bu, "script:bullet3d.world.get_collision_objects", "bullet3d.world", "get_collision_objects", 1, 2, 1},
  {0x4d2aef1fu, "script:sys.get_application_info", "sys", "get_application_info", 1, 1, 1},
  {0x4d6a8946u, "script:socket.dns.tohostname", "socket.dns", "tohostname", 1, 1, 2},
  {0x50398501u, "script:compute.get_samplers", "compute", "get_samplers", 1, 1, 1},
  {0x52d6fadau, "script:window.get_safe_area", "window", "get_safe_area", 0, 0, 1},
  {0x55b0a5b4u, "script:render.draw", "render", "draw", 1, 2, 0},
  {0x55d170c8u, "script:image.load_buffer", "image", "load_buffer", 1, 2, 1},
  {0x56a53c59u, "script:vmath.vector", "vmath", "vector", 1, 1, 1},
  {0x5df58406u, "script:socket.udp6", "socket", "udp6", 0, 0, 2},
  {0x62e63c2au, "script:b2d.body.create_shape", "b2d.body", "create_shape", 2, 2, 0},
  {0x6376dabcu, "script:b2d.world.get_counters", "b2d.world", "get_counters", 1, 1, 1},
  {0x64ebca74u, "script:buffer.set_metadata", "buffer", "set_metadata", 4, 4, 0},
  {0x65195fd1u, "script:gui.clone_tree", "gui", "clone_tree", 1, 1, 1},
  {0x66447212u, "script:sys.get_sys_info", "sys", "get_sys_info", 0, 1, 1},
  {0x6af51603u, "script:profiler.view_recorded_frame", "profiler", "view_recorded_frame", 1, 1, 0},
  {0x6b7e6cc5u, "script:b2d.world.explode", "b2d.world", "explode", 2, 2, 0},
  {0x6d237016u, "script:render.dispatch_compute", "render", "dispatch_compute", 3, 4, 0},
  {0x6dec8627u, "script:bullet3d.rigid_body.compute_aabb", "bullet3d.rigid_body", "compute_aabb", 1, 1, 1},
  {0x6e9fff88u, "script:bullet3d.constraint.create_point_to_point", "bullet3d.constraint", "create_point_to_point", 2, 3, 1},
  {0x6f114000u, "script:font.get_info", "font", "get_info", 1, 1, 1},
  {0x70d92811u, "script:material.get_samplers", "material", "get_samplers", 1, 1, 1},
  {0x72d2f566u, "script:bullet3d.constraint.create_generic_6dof", "bullet3d.constraint", "create_generic_6dof", 2, 3, 1},
  {0x73855303u, "script:graphics.get_engine_adapters", "graphics", "get_engine_adapters", 0, 0, 1},
  {0x765b190eu, "script:resource.create_atlas", "resource", "create_atlas", 2, 2, 1},
  {0x76e96818u, "script:graphics.get_adapter_info", "graphics", "get_adapter_info", 0, 0, 1},
  {0x7b10d0abu, "script:sys.open_url", "sys", "open_url", 1, 2, 1},
  {0x81628ecbu, "script:b2d.shape.get_mass_data", "b2d.shape", "get_mass_data", 1, 1, 1},
  {0x81cb5dfdu, "script:material.get_constants", "material", "get_constants", 1, 1, 1},
  {0x824911f0u, "script:liveupdate.get_mounts", "liveupdate", "get_mounts", 0, 0, 1},
  {0x84f89a5au, "script:b2d.chain.get_geometry", "b2d.chain", "get_geometry", 1, 1, 1},
  {0x865ffdb1u, "script:socket.dns.getnameinfo", "socket.dns", "getnameinfo", 1, 1, 2},
  {0x892ccd10u, "script:bullet3d.world.cast_shape_closest", "bullet3d.world", "cast_shape_closest", 3, 4, 1},
  {0x8993930au, "script:sys.load_resource", "sys", "load_resource", 1, 1, 2},
  {0x8a8afda0u, "script:material.get_textures", "material", "get_textures", 1, 1, 1},
  {0x8b84b52eu, "script:tilemap.get_tiles", "tilemap", "get_tiles", 2, 2, 1},
  {0x8daa4dc7u, "script:b2d.fixture.set_shape", "b2d.fixture", "set_shape", 4, 4, 0},
  {0x8e78b880u, "script:physics.get_joint_properties", "physics", "get_joint_properties", 2, 2, 1},
  {0x8edf9c9cu, "script:gui.stop_particlefx", "gui", "stop_particlefx", 1, 2, 0},
  {0x8fa55416u, "script:resource.get_text_metrics", "resource", "get_text_metrics", 2, 3, 1},
  {0x92af88f8u, "script:bullet3d.shape.get_shape", "bullet3d.shape", "get_shape", 1, 1, 1},
  {0x9381baaeu, "script:sound.get_groups", "sound", "get_groups", 0, 0, 1},
  {0x944cfa9cu, "script:go.get", "go", "get", 2, 3, 1},
  {0x9738c1b0u, "script:b2d.body.get_joints", "b2d.body", "get_joints", 1, 1, 1},
  {0x97c4dedbu, "script:render.draw_debug3d", "render", "draw_debug3d", 0, 1, 0},
  {0x982605eeu, "script:bullet3d.collision_object.get_shapes", "bullet3d.collision_object", "get_shapes", 1, 1, 1},
  {0x9a1c4798u, "script:b2d.joint.create_mouse", "b2d.joint", "create_mouse", 2, 3, 1},
  {0x9e220362u, "script:socket.tcp6", "socket", "tcp6", 0, 0, 2},
  {0x9e2a09dfu, "script:physics.raycast_async", "physics", "raycast_async", 3, 4, 0},
  {0x9e5045d9u, "script:b2d.joint.create_rope", "b2d.joint", "create_rope", 2, 3, 1},
  {0xa0d058efu, "script:b2d.body.get_fixtures", "b2d.body", "get_fixtures", 1, 1, 1},
  {0xa1c7da0du, "script:compute.get_constants", "compute", "get_constants", 1, 1, 1},
  {0xa2c4685au, "script:b2d.world.get_profile", "b2d.world", "get_profile", 1, 1, 1},
  {0xa5ce9acau, "script:physics.create_joint", "physics", "create_joint", 6, 7, 0},
  {0xa6f9f554u, "script:bullet3d.world.cast_shape", "bullet3d.world", "cast_shape", 3, 5, 1},
  {0xab2f947cu, "script:b2d.body.compute_aabb", "b2d.body", "compute_aabb", 1, 1, 1},
  {0xad3b08d7u, "script:render.predicate", "render", "predicate", 1, 1, 1},
  {0xae9c8317u, "script:resource.get_texture_info", "resource", "get_texture_info", 1, 1, 1},
  {0xaf3e7d61u, "script:physics.set_shape", "physics", "set_shape", 3, 3, 0},
  {0xaf5833fdu, "script:b2d.shape.ray_cast", "b2d.shape", "ray_cast", 3, 4, 1},
  {0xaf8a0d12u, "script:bullet3d.constraint.create_generic_6dof_spring", "bullet3d.constraint", "create_generic_6dof_spring", 3, 3, 1},
  {0xaf8d3caeu, "script:bullet3d.world.overlap_shape", "bullet3d.world", "overlap_shape", 2, 4, 1},
  {0xafcef990u, "script:go.set", "go", "set", 3, 4, 0},
  {0xb3a8fbaau, "script:b2d.joint.create_gear", "b2d.joint", "create_gear", 2, 3, 1},
  {0xb4242e50u, "script:compute.get_textures", "compute", "get_textures", 1, 1, 1},
  {0xb5741506u, "script:particlefx.stop", "particlefx", "stop", 1, 2, 0},
  {0xb65f1aaeu, "script:gui.get_tree", "gui", "get_tree", 1, 1, 1},
  {0xb684efcdu, "script:b2d.fixture.get_filter_data", "b2d.fixture", "get_filter_data", 3, 3, 1},
  {0xb9334a1du, "script:b2d.joint.create_weld", "b2d.joint", "create_weld", 2, 3, 1},
  {0xb9a0a765u, "script:compute.set_samplers", "compute", "set_samplers", 2, 2, 0},
  {0xb9a22054u, "script:material.set_textures", "material", "set_textures", 2, 2, 0},
  {0xb9c87acau, "script:b2d.body.create_chain", "b2d.body", "create_chain", 2, 2, 2},
  {0xbfc3de06u, "script:bullet3d.constraint.create_hinge", "bullet3d.constraint", "create_hinge", 2, 3, 1},
  {0xc182ca5du, "script:bullet3d.world.cast_ray_closest", "bullet3d.world", "cast_ray_closest", 3, 4, 1},
  {0xc2b465e9u, "script:b2d.shape.get_sensor_overlaps", "b2d.shape", "get_sensor_overlaps", 1, 1, 1},
  {0xc35bab5fu, "script:b2d.joint.create_prismatic", "b2d.joint", "create_prismatic", 2, 3, 1},
  {0xc75a190au, "script:resource.set_texture", "resource", "set_texture", 3, 3, 0},
  {0xc9132880u, "script:buffer.get_metadata", "buffer", "get_metadata", 2, 2, 2},
  {0xc95426ecu, "script:physics.set_joint_properties", "physics", "set_joint_properties", 3, 3, 0},
  {0xcc608794u, "script:socket.udp", "socket", "udp", 0, 0, 2},
  {0xd0a4432au, "script:material.set_vertex_attributes", "material", "set_vertex_attributes", 2, 2, 0},
  {0xd17f4d08u, "script:collectionfactory.create", "collectionfactory", "create", 1, 5, 1},
  {0xd1b0f8b6u, "script:resource.get_render_target_info", "resource", "get_render_target_info", 1, 1, 1},
  {0xd24fdabau, "script:bullet3d.constraint.create_slider", "bullet3d.constraint", "create_slider", 2, 3, 1},
  {0xd425a864u, "script:compute.set_textures", "compute", "set_textures", 2, 2, 0},
  {0xd543ef60u, "script:b2d.joint.create_wheel", "b2d.joint", "create_wheel", 2, 3, 1},
  {0xd62e9599u, "script:model.get_blend_weights", "model", "get_blend_weights", 1, 1, 1},
  {0xd6bbfbdau, "script:crash.get_backtrace", "crash", "get_backtrace", 1, 1, 1},
  {0xd7b57bcbu, "script:sys.get_engine_info", "sys", "get_engine_info", 0, 0, 1},
  {0xdc6540d9u, "script:compute.set_constants", "compute", "set_constants", 2, 2, 0},
  {0xe0bfe2a4u, "script:bullet3d.shape.set_shape", "bullet3d.shape", "set_shape", 2, 2, 0},
  {0xe1b5afb4u, "script:bullet3d.constraint.create_universal", "bullet3d.constraint", "create_universal", 3, 3, 1},
  {0xe252d638u, "script:buffer.create", "buffer", "create", 2, 2, 1},
  {0xe2c13cfeu, "script:resource.get_atlas", "resource", "get_atlas", 1, 1, 1},
  {0xe5fd303au, "script:tilemap.get_tile_info", "tilemap", "get_tile_info", 4, 4, 1},
  {0xe6bf1a3au, "script:b2d.body.set_mass_data", "b2d.body", "set_mass_data", 2, 2, 0},
  {0xe9c25548u, "script:bullet3d.world.contact_test", "bullet3d.world", "contact_test", 2, 4, 1},
  {0xec37350du, "script:gui.get_layouts", "gui", "get_layouts", 0, 0, 1},
  {0xeeca6e90u, "script:sys.deserialize", "sys", "deserialize", 1, 1, 1},
  {0xef3874f5u, "script:bullet3d.world.cast_ray", "bullet3d.world", "cast_ray", 3, 5, 1},
  {0xef7661c9u, "script:socket.dns.getaddrinfo", "socket.dns", "getaddrinfo", 1, 1, 2},
  {0xf0f81b15u, "script:material.set_samplers", "material", "set_samplers", 2, 2, 0},
  {0xf18752f0u, "script:collectionproxy.get_resources", "collectionproxy", "get_resources", 1, 1, 1},
  {0xf18f50d2u, "script:socket.dns.toip", "socket.dns", "toip", 1, 1, 2},
  {0xf1c5b940u, "script:render.set_camera", "render", "set_camera", 0, 2, 0},
  {0xf3be81efu, "script:gui.get_layout_objects", "gui", "get_layout_objects", 1, 1, 1},
  {0xf70746c2u, "script:resource.set_atlas", "resource", "set_atlas", 2, 2, 0},
  {0xf74e8addu, "script:model.set_blend_weights", "model", "set_blend_weights", 1, 2, 0},
  {0xf9985630u, "script:label.get_layout_objects", "label", "get_layout_objects", 1, 1, 1},
  {0xfde489cdu, "script:bullet3d.world.contact_pair_test", "bullet3d.world", "contact_pair_test", 3, 4, 1},
  {0xfe649ddbu, "script:b2d.joint.create_revolute", "b2d.joint", "create_revolute", 2, 3, 1},
  {0xfed445ecu, "script:model.get_mesh_aabb", "model", "get_mesh_aabb", 1, 1, 1},
};

void fail(char* error, size_t capacity, const char* message) noexcept {
  if (error && capacity) std::snprintf(error, capacity, "%s", message);
}
}  // namespace

const Operation* operations() noexcept { return kOperations; }

const Operation* find(uint32_t stableId) noexcept {
  size_t first = 0;
  size_t count = kOperationCount;
  while (count) {
    const size_t step = count / 2;
    const size_t index = first + step;
    if (kOperations[index].stableId < stableId) {
      first = index + 1;
      count -= step + 1;
    } else {
      count = step;
    }
  }
  return first < kOperationCount && kOperations[first].stableId == stableId
      ? &kOperations[first] : nullptr;
}

DispatchStatus dispatch(
    ScriptCallFrame* frame,
    char* error,
    size_t errorCapacity,
    const LuaApi* api) noexcept {
  if (!frame) {
    fail(error, errorCapacity, "Universal-value call frame is null");
    return DispatchStatus::kError;
  }
  const Operation* operation = find(frame->stableId);
  if (!operation) return DispatchStatus::kMissing;
  frame->resultCount = 0;
  if (frame->argumentCount < operation->minimumArgumentCount ||
      frame->argumentCount > operation->maximumArgumentCount ||
      (frame->argumentCount && !frame->arguments)) {
    fail(error, errorCapacity, "Universal-value argument count does not match descriptor");
    return DispatchStatus::kError;
  }
  if (operation->resultCount &&
      (!frame->results || frame->resultCapacity < operation->resultCount)) {
    fail(error, errorCapacity, "Universal-value result storage is exhausted");
    return DispatchStatus::kError;
  }
  if (!api || !api->invoke) {
    fail(error, errorCapacity, "Universal-value captured Lua backend is unavailable");
    return DispatchStatus::kError;
  }
  const DispatchStatus status = api->invoke(
      api->context, *operation, frame, error, errorCapacity);
  if (status != DispatchStatus::kSuccess) {
    frame->resultCount = 0;
    if (status == DispatchStatus::kMissing) {
      fail(error, errorCapacity, "Universal-value backend rejected a generated operation");
      return DispatchStatus::kError;
    }
    return status;
  }
  if (frame->resultCount != operation->resultCount) {
    frame->resultCount = 0;
    fail(error, errorCapacity, "Universal-value Lua result count does not match descriptor");
    return DispatchStatus::kError;
  }
  return DispatchStatus::kSuccess;
}

}  // namespace defold_hermes::universal_value
