// Generated by scripts/generate-dmsdk-hash-span-bindings.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_hash_span.h>
#include <defold_hermes/generated_dmsdk_hash_span_runtime.h>
namespace {
const DehermDmSdkHashSpanDescriptor kDescriptors[] = {
  { UINT16_C(0), UINT8_C(32), "dmsdk:dmHashBuffer32@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:69:212" },
  { UINT16_C(1), UINT8_C(64), "dmsdk:dmHashBuffer64@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:79:213" }
};
}
extern "C" {
uint32_t deherm_dmsdk_hash_span_count(void) { return UINT32_C(2); }
const DehermDmSdkHashSpanDescriptor* deherm_dmsdk_hash_span_descriptors(void) { return kDescriptors; }
DehermDmSdkHashSpanStatus deherm_dmsdk_hash_span_dispatch(uint16_t id, const uint8_t* input, uint32_t input_length, uint64_t* out_hash)
{
  if (id >= deherm_dmsdk_hash_span_count()) return DEHERM_DMSDK_HASH_SPAN_UNKNOWN_ID;
  if (out_hash == 0 || (input_length != 0 && input == 0)) return DEHERM_DMSDK_HASH_SPAN_NULL_STORAGE;
  switch (id) {
    case 0: { uint32_t value=0; if (!deherm_dmsdk_hash_span_dm_hash_buffer32(input, input_length, &value)) return DEHERM_DMSDK_HASH_SPAN_NULL_STORAGE; *out_hash=value; return DEHERM_DMSDK_HASH_SPAN_OK; }
    case 1: return deherm_dmsdk_hash_span_dm_hash_buffer64(input, input_length, out_hash) ? DEHERM_DMSDK_HASH_SPAN_OK : DEHERM_DMSDK_HASH_SPAN_NULL_STORAGE;
    default: return DEHERM_DMSDK_HASH_SPAN_UNKNOWN_ID;
  }
}
}
