// Generated by scripts/generate-dmsdk-borrowed-handle-bindings.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_borrowed_handle.h>
#include <string.h>
namespace {
const DehermDmSdkBorrowedDescriptor kDescriptors[] = {
  { UINT16_C(0), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(7), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmBuffer::IsBufferValid@upstream/defold/engine/dlib/src/dmsdk/dlib/buffer.h:227:93" },
  { UINT16_C(1), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(9), UINT16_C(8) }, "dmsdk:dmConnectionPool::GetReuseCount@upstream/defold/engine/dlib/src/dmsdk/dlib/connection_pool.h:178:145" },
  { UINT16_C(2), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(11), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameObject::ComponentTypeGetTypeIndex@upstream/defold/engine/gameobject/src/dmsdk/gameobject/component.h:545:907" },
  { UINT16_C(3), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_U64 }, { UINT16_C(10), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetComponentTypeIndex@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:871:1036" },
  { UINT16_C(4), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(12), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetGeneration@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:631:1009" },
  { UINT16_C(5), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(12), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetIdentifier@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:622:1008" },
  { UINT16_C(6), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(13), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetPropertyOptionsCount@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:907:1040" },
  { UINT16_C(7), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_F32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(12), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetUniformScale@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:750:1022" },
  { UINT16_C(8), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_F32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(12), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameObject::GetWorldUniformScale@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:790:1027" },
  { UINT16_C(9), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(12), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameObject::IsBone@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:824:1031" },
  { UINT16_C(10), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_I32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(14), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameSystem::AreRenderConstantsUpdated@upstream/defold/engine/gamesys/src/dmsdk/gamesys/render_constants.h:146:1208" },
  { UINT16_C(11), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_I32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_U64 }, { UINT16_C(14), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameSystem::ClearRenderConstant@upstream/defold/engine/gamesys/src/dmsdk/gamesys/render_constants.h:130:1206" },
  { UINT16_C(12), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(16), UINT16_C(15) }, "dmsdk:dmGameSystem::CompFactoryIsDynamicPrototype@upstream/defold/engine/gamesys/src/dmsdk/gamesys/components/comp_factory.h:56:1139" },
  { UINT16_C(13), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(16), UINT16_C(15) }, "dmsdk:dmGameSystem::CompFactoryIsLoading@upstream/defold/engine/gamesys/src/dmsdk/gamesys/components/comp_factory.h:55:1138" },
  { UINT16_C(14), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(14), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGameSystem::GetRenderConstantCount@upstream/defold/engine/gamesys/src/dmsdk/gamesys/render_constants.h:90:1202" },
  { UINT16_C(15), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_F32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(17), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGraphics::GetDisplayScaleFactor@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1636:1450" },
  { UINT16_C(16), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(17), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGraphics::GetHeight@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1428:1425" },
  { UINT16_C(17), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(17), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGraphics::GetMaxElementsIndices@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1097:1391" },
  { UINT16_C(18), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(17), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGraphics::GetMaxElementsVertices@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1041:1385" },
  { UINT16_C(19), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(17), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGraphics::GetMaxTextureSize@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1396:1421" },
  { UINT16_C(20), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(17), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGraphics::GetNumSupportedExtensions@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1120:1394" },
  { UINT16_C(21), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(17), UINT16_C(18) }, "dmsdk:dmGraphics::GetRenderTargetSampleCount@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1596:1445" },
  { UINT16_C(22), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(17), UINT16_C(19) }, "dmsdk:dmGraphics::GetTextureResourceSize@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1244:1406" },
  { UINT16_C(23), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(17), UINT16_C(19) }, "dmsdk:dmGraphics::GetTextureStatusFlags@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1342:1416" },
  { UINT16_C(24), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(17), UINT16_C(19) }, "dmsdk:dmGraphics::GetTextureUsageHintFlags@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1332:1415" },
  { UINT16_C(25), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_U64 }, { UINT16_C(20), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGraphics::GetVertexStreamOffset@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:995:1380" },
  { UINT16_C(26), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(17), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGraphics::GetWidth@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1420:1424" },
  { UINT16_C(27), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(17), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGraphics::GetWindowHeight@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1412:1423" },
  { UINT16_C(28), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(17), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmGraphics::GetWindowWidth@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1404:1422" },
  { UINT16_C(29), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(22), UINT16_C(21) }, "dmsdk:dmGui::GetNodeCustomType@upstream/defold/engine/gui/src/dmsdk/gui/gui.h:429:1569" },
  { UINT16_C(30), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(22), UINT16_C(21) }, "dmsdk:dmGui::GetNodeId@upstream/defold/engine/gui/src/dmsdk/gui/gui.h:261:1555" },
  { UINT16_C(31), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(22), UINT16_C(21) }, "dmsdk:dmGui::GetNodeIsBone@upstream/defold/engine/gui/src/dmsdk/gui/gui.h:308:1560" },
  { UINT16_C(32), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_HANDLE }, { UINT16_C(22), UINT16_C(21) }, "dmsdk:dmGui::GetNodeTextureId@upstream/defold/engine/gui/src/dmsdk/gui/gui.h:445:1571" },
  { UINT16_C(33), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(23), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmImage::GetHeight@upstream/defold/engine/dlib/src/dmsdk/dlib/image.h:114:347" },
  { UINT16_C(34), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(23), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmImage::GetWidth@upstream/defold/engine/dlib/src/dmsdk/dlib/image.h:107:346" },
  { UINT16_C(35), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(24), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmMessage::GetSocketNameHash@upstream/defold/engine/dlib/src/dmsdk/dlib/message.h:159:417" },
  { UINT16_C(36), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(24), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmMessage::IsSocketValid@upstream/defold/engine/dlib/src/dmsdk/dlib/message.h:143:415" },
  { UINT16_C(37), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(25), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmMutex::TryLock@upstream/defold/engine/dlib/src/dmsdk/dlib/mutex.h:78:433" },
  { UINT16_C(38), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(26), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRender::GetConstantName@upstream/defold/engine/render/src/dmsdk/render/render.h:497:1840" },
  { UINT16_C(39), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_I32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(26), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRender::GetConstantType@upstream/defold/engine/render/src/dmsdk/render/render.h:529:1844" },
  { UINT16_C(40), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_U32 }, { UINT16_C(27), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRender::GetMaterialSamplerNameHash@upstream/defold/engine/render/src/dmsdk/render/render.h:739:1867" },
  { UINT16_C(41), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_U64 }, { UINT16_C(27), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRender::GetMaterialSamplerUnit@upstream/defold/engine/render/src/dmsdk/render/render.h:747:1868" },
  { UINT16_C(42), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(27), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRender::GetMaterialTagListKey@upstream/defold/engine/render/src/dmsdk/render/render.h:455:1835" },
  { UINT16_C(43), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_I32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(27), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRender::GetMaterialVertexSpace@upstream/defold/engine/render/src/dmsdk/render/render.h:126:1810" },
  { UINT16_C(44), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(28), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRender::GetNamedConstantCount@upstream/defold/engine/render/src/dmsdk/render/render.h:642:1856" },
  { UINT16_C(45), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(29), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmResource::GetNameHash@upstream/defold/engine/resource/src/dmsdk/resource/resource_gen.hpp:246:2011" },
  { UINT16_C(46), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(4), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmResource::GetNameHash@upstream/defold/engine/resource/src/dmsdk/resource/resource.hpp:325:1994" },
  { UINT16_C(47), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(29), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmResource::GetResourceSize@upstream/defold/engine/resource/src/dmsdk/resource/resource_gen.hpp:282:2017" },
  { UINT16_C(48), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::GetAnimation@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:176:2050" },
  { UINT16_C(49), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::GetBoneCount@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:212:2067" },
  { UINT16_C(50), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_F32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_BOOL }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::GetCursor@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:202:2057" },
  { UINT16_C(51), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::GetEnabled@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:210:2065" },
  { UINT16_C(52), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::GetMaxBoneCount@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:213:2068" },
  { UINT16_C(53), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::GetModel@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:200:2056" },
  { UINT16_C(54), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_F32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::GetPlaybackRate@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:204:2059" },
  { UINT16_C(55), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::GetVertexCount@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:197:2054" },
  { UINT16_C(56), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::HasPoseMatrixCacheAnimatedPose@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:215:2069" },
  { UINT16_C(57), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::IsValid@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:211:2066" },
  { UINT16_C(58), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_U64 }, { UINT16_C(30), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmRig::ResetIKTarget@upstream/defold/engine/rig/src/dmsdk/rig/rig.h:208:2063" },
  { UINT16_C(59), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_I32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(31), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:dmSocket::GetFD@upstream/defold/engine/dlib/src/dmsdk/dlib/socket.h:264:556" },
  { UINT16_C(60), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(1), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:FontCollectionGetFontCount@upstream/defold/engine/font/src/dmsdk/font/fontcollection.h:73:827" },
  { UINT16_C(61), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_F32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_F32 }, { UINT16_C(0), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:FontGetAscent@upstream/defold/engine/font/src/dmsdk/font/font.h:201:811" },
  { UINT16_C(62), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_F32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_F32 }, { UINT16_C(0), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:FontGetDescent@upstream/defold/engine/font/src/dmsdk/font/font.h:210:812" },
  { UINT16_C(63), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_U32 }, { UINT16_C(0), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:FontGetGlyphIndex@upstream/defold/engine/font/src/dmsdk/font/font.h:239:815" },
  { UINT16_C(64), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_F32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_F32 }, { UINT16_C(0), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:FontGetLineGap@upstream/defold/engine/font/src/dmsdk/font/font.h:219:813" },
  { UINT16_C(65), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(0), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:FontGetPathHash@upstream/defold/engine/font/src/dmsdk/font/font.h:182:809" },
  { UINT16_C(66), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(0), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:FontGetResourceSize@upstream/defold/engine/font/src/dmsdk/font/font.h:227:814" },
  { UINT16_C(67), UINT8_C(2), UINT8_C(DEHERM_DMSDK_BORROWED_F32), { DEHERM_DMSDK_BORROWED_HANDLE, DEHERM_DMSDK_BORROWED_F32 }, { UINT16_C(0), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:FontGetScaleFromSize@upstream/defold/engine/font/src/dmsdk/font/font.h:192:810" },
  { UINT16_C(68), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(2), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:JobSystemGetWorkerCount@upstream/defold/engine/dlib/src/dmsdk/dlib/jobsystem.h:185:373" },
  { UINT16_C(69), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(3), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:ResourceDescriptorGetNameHash@upstream/defold/engine/resource/src/dmsdk/resource/resource.h:393:1912" },
  { UINT16_C(70), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(3), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:ResourceDescriptorGetResourceSize@upstream/defold/engine/resource/src/dmsdk/resource/resource.h:437:1918" },
  { UINT16_C(71), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U64), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(4), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:ResourceTypeGetNameHash@upstream/defold/engine/resource/src/dmsdk/resource/resource.h:558:1932" },
  { UINT16_C(72), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(4), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:ResourceTypeGetPreloadSize@upstream/defold/engine/resource/src/dmsdk/resource/resource.h:597:1940" },
  { UINT16_C(73), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_BOOL), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(4), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:ResourceTypeIsStreaming@upstream/defold/engine/resource/src/dmsdk/resource/resource.h:596:1939" },
  { UINT16_C(74), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(5), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:TextLayoutGetDecorationCount@upstream/defold/engine/font/src/dmsdk/font/text_layout.h:445:859" },
  { UINT16_C(75), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(5), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:TextLayoutGetGlyphCount@upstream/defold/engine/font/src/dmsdk/font/text_layout.h:398:853" },
  { UINT16_C(76), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(5), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:TextLayoutGetLineCount@upstream/defold/engine/font/src/dmsdk/font/text_layout.h:414:855" },
  { UINT16_C(77), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(5), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:TextLayoutGetObjectCount@upstream/defold/engine/font/src/dmsdk/font/text_layout.h:459:861" },
  { UINT16_C(78), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(5), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:TextLayoutGetParagraphCount@upstream/defold/engine/font/src/dmsdk/font/text_layout.h:430:857" },
  { UINT16_C(79), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_F32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(6), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:WindowGetDisplayScaleFactor@upstream/defold/engine/platform/src/dmsdk/platform/window.h:308:1791" },
  { UINT16_C(80), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(6), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:WindowGetHeight@upstream/defold/engine/platform/src/dmsdk/platform/window.h:293:1789" },
  { UINT16_C(81), UINT8_C(1), UINT8_C(DEHERM_DMSDK_BORROWED_U32), { DEHERM_DMSDK_BORROWED_HANDLE, 0 }, { UINT16_C(6), DEHERM_DMSDK_BORROWED_NO_HANDLE_KIND }, "dmsdk:WindowGetWidth@upstream/defold/engine/platform/src/dmsdk/platform/window.h:286:1788" }
};
const DehermDmSdkBorrowedHandleKind kHandleKinds[] = {
  { UINT16_C(0), "HFont", "opaque" },
  { UINT16_C(1), "HFontCollection", "opaque" },
  { UINT16_C(2), "HJobContext", "opaque" },
  { UINT16_C(3), "HResourceDescriptor", "opaque" },
  { UINT16_C(4), "HResourceType", "opaque" },
  { UINT16_C(5), "HTextLayout", "opaque" },
  { UINT16_C(6), "HWindow", "opaque" },
  { UINT16_C(7), "dmBuffer::HBuffer", "u32" },
  { UINT16_C(8), "dmConnectionPool::HConnection", "u32" },
  { UINT16_C(9), "dmConnectionPool::HPool", "opaque" },
  { UINT16_C(10), "dmGameObject::HCollection", "opaque" },
  { UINT16_C(11), "dmGameObject::HComponentType", "opaque" },
  { UINT16_C(12), "dmGameObject::HInstance", "opaque" },
  { UINT16_C(13), "dmGameObject::HPropertyOptions", "opaque" },
  { UINT16_C(14), "dmGameSystem::HComponentRenderConstants", "opaque" },
  { UINT16_C(15), "dmGameSystem::HFactoryComponent", "opaque" },
  { UINT16_C(16), "dmGameSystem::HFactoryWorld", "opaque" },
  { UINT16_C(17), "dmGraphics::HContext", "opaque" },
  { UINT16_C(18), "dmGraphics::HRenderTarget", "u64" },
  { UINT16_C(19), "dmGraphics::HTexture", "u64" },
  { UINT16_C(20), "dmGraphics::HVertexDeclaration", "opaque" },
  { UINT16_C(21), "dmGui::HNode", "u32" },
  { UINT16_C(22), "dmGui::HScene", "opaque" },
  { UINT16_C(23), "dmImage::HImage", "opaque" },
  { UINT16_C(24), "dmMessage::HSocket", "u64" },
  { UINT16_C(25), "dmMutex::HMutex", "opaque" },
  { UINT16_C(26), "dmRender::HConstant", "opaque" },
  { UINT16_C(27), "dmRender::HMaterial", "opaque" },
  { UINT16_C(28), "dmRender::HNamedConstantBuffer", "opaque" },
  { UINT16_C(29), "dmResource::HDescriptor", "opaque" },
  { UINT16_C(30), "dmRig::HRigInstance", "opaque" },
  { UINT16_C(31), "dmSocket::Socket", "i32" }
};
DehermDmSdkBorrowedProvider gProvider = {};
}
extern "C" {
uint32_t deherm_dmsdk_borrowed_count(void) { return UINT32_C(82); }
const DehermDmSdkBorrowedDescriptor* deherm_dmsdk_borrowed_descriptors(void) { return kDescriptors; }
uint32_t deherm_dmsdk_borrowed_handle_kind_count(void) { return UINT32_C(32); }
const DehermDmSdkBorrowedHandleKind* deherm_dmsdk_borrowed_handle_kinds(void) { return kHandleKinds; }
DehermDmSdkBorrowedStatus deherm_dmsdk_borrowed_set_provider(const DehermDmSdkBorrowedProvider* provider) {
  if (provider == nullptr) { memset(&gProvider, 0, sizeof(gProvider)); return DEHERM_DMSDK_BORROWED_OK; }
  if (provider->abi_version != DEHERM_DMSDK_BORROWED_PROVIDER_ABI || provider->is_current_thread == nullptr || provider->validate_handle == nullptr || provider->invoke == nullptr) return DEHERM_DMSDK_BORROWED_INVALID_PROVIDER;
  gProvider = *provider;
  return DEHERM_DMSDK_BORROWED_OK;
}
DehermDmSdkBorrowedStatus deherm_dmsdk_borrowed_dispatch(uint16_t id, const uint64_t* arguments, uint32_t argument_count, uint64_t* out_result) {
  if (id >= deherm_dmsdk_borrowed_count()) return DEHERM_DMSDK_BORROWED_UNKNOWN_ID;
  const DehermDmSdkBorrowedDescriptor& descriptor = kDescriptors[id];
  if (argument_count != descriptor.argument_count) return DEHERM_DMSDK_BORROWED_WRONG_ARITY;
  if (out_result == nullptr || (argument_count != 0 && arguments == nullptr)) return DEHERM_DMSDK_BORROWED_NULL_STORAGE;
  if (gProvider.invoke == nullptr) return DEHERM_DMSDK_BORROWED_PROVIDER_MISSING;
  if (gProvider.is_current_thread(gProvider.context) == 0) return DEHERM_DMSDK_BORROWED_WRONG_THREAD;
  for (uint32_t index = 0; index < argument_count; ++index) {
    if (descriptor.argument_kinds[index] == DEHERM_DMSDK_BORROWED_HANDLE && (arguments[index] == 0 || gProvider.validate_handle(gProvider.context, descriptor.handle_kinds[index], arguments[index]) == 0)) return DEHERM_DMSDK_BORROWED_INVALID_HANDLE;
  }
  return gProvider.invoke(gProvider.context, id, arguments, argument_count, out_result);
}
}
