// Generated by scripts/generate-native-module-providers.mjs. Do not edit.
#include <defold_hermes/generated_native_module_jsi.hpp>
#if !defined(DM_PLATFORM_HTML5)
#include <defold_hermes/native_module_provider.h>
#include <array>
#include <cmath>
#include <cstring>
#include <string>
namespace defold_hermes { namespace jsi = facebook::jsi; namespace {
struct ByteView { uint8_t* data; size_t length; };
uint32_t requireU32(jsi::Runtime& r, const jsi::Value& v, const char* name) {
  if (!v.isNumber()) throw jsi::JSError(r, std::string(name) + " must be a u32"); const double n = v.asNumber();
  if (!std::isfinite(n) || std::trunc(n) != n || n < 0.0 || n > 4294967295.0) throw jsi::JSError(r, std::string(name) + " must be a u32");
  return static_cast<uint32_t>(n);
}
ByteView requireBytes(jsi::Runtime& r, const jsi::Value& v, const char* name) {
  if (!v.isObject()) throw jsi::JSError(r, std::string(name) + " must be a Uint8Array"); auto o = v.asObject(r);
  if (!o.isUint8Array(r)) throw jsi::JSError(r, std::string(name) + " must be a Uint8Array");
  auto a = o.getUint8Array(r); auto b = a.buffer(r); if (b.detached(r)) throw jsi::JSError(r, std::string(name) + " is detached");
  const size_t offset = a.byteOffset(r), length = a.byteLength(r);
  if (offset > b.size(r) || length > b.size(r) - offset) throw jsi::JSError(r, std::string(name) + " has an invalid byte range");
  return {b.data(r) + offset, length};
}
}
void installGeneratedNativeModuleProviders(jsi::Runtime& runtime, jsi::Object& modules) {
  const size_t count = deherm_native_module_provider_count_v1();
  for (size_t p = 0; p < count; ++p) {
    DehermNativeModuleProviderV1 provider{};
    if (deherm_native_module_copy_provider_v1(p, &provider) != DEHERM_NATIVE_MODULE_REGISTRY_OK) throw jsi::JSError(runtime, "native registry changed during install");
    if (std::strcmp(provider.module_name, "__resolve") == 0 || modules.hasProperty(runtime, provider.module_name))
      throw jsi::JSError(runtime, std::string("native module collides with an installed module: ") + provider.module_name);
    jsi::Object module(runtime);
    module.setProperty(runtime, "__dehermNativeModuleAbiVersionV1", static_cast<double>(provider.module_abi_version));
    for (uint32_t m = 0; m < provider.method_count; ++m) { const auto method = provider.methods[m];
      module.setProperty(runtime, method.name, jsi::Function::createFromHostFunction(runtime, jsi::PropNameID::forAscii(runtime, method.name), method.argument_count,
        [provider, method](jsi::Runtime& r, const jsi::Value&, const jsi::Value* values, size_t actual) {
          if (actual != method.argument_count) throw jsi::JSError(r, std::string(provider.module_name) + "." + method.name + " received the wrong argument count");
          std::array<DehermNativeModuleArgumentV1, DEHERM_NATIVE_MODULE_MAX_ARGUMENTS> args{};
          std::array<std::string, DEHERM_NATIVE_MODULE_MAX_ARGUMENTS> strings{};
          for (uint32_t i = 0; i < method.argument_count; ++i) { auto& out = args[i]; out.kind = method.argument_kinds[i];
            switch (out.kind) {
              case DEHERM_NATIVE_MODULE_ARGUMENT_U32: out.u32 = requireU32(r, values[i], method.name); break;
              case DEHERM_NATIVE_MODULE_ARGUMENT_UTF8:
                if (!values[i].isString()) throw jsi::JSError(r, std::string(method.name) + " requires a string");
                strings[i] = values[i].asString(r).utf8(r); out.bytes = reinterpret_cast<const uint8_t*>(strings[i].data()); out.length = strings[i].size(); break;
              case DEHERM_NATIVE_MODULE_ARGUMENT_BYTES: { const auto bytes = requireBytes(r, values[i], method.name); out.bytes = bytes.data; out.length = bytes.length; break; }
              case DEHERM_NATIVE_MODULE_ARGUMENT_MUTABLE_BYTES: { const auto bytes = requireBytes(r, values[i], method.name); out.mutable_bytes = bytes.data; out.length = bytes.length; break; }
              case DEHERM_NATIVE_MODULE_ARGUMENT_BOOL:
                if (!values[i].isBool()) throw jsi::JSError(r, std::string(method.name) + " requires a boolean"); out.u32 = values[i].getBool() ? 1u : 0u; break;
              default: throw jsi::JSError(r, "invalid native argument descriptor");
            }
          }
          DehermNativeModuleResultV1 result{}; const int32_t status = provider.invoke(provider.context, method.id, args.data(), actual, &result);
          if (method.result_kind == DEHERM_NATIVE_MODULE_RESULT_STATUS) return jsi::Value(static_cast<double>(status));
          if (status != 0) throw jsi::JSError(r, std::string(provider.module_name) + "." + method.name + " failed with status " + std::to_string(status));
          return jsi::Value(static_cast<double>(result.u32));
        }));
    }
    modules.setProperty(runtime, provider.module_name, std::move(module));
  }
  modules.setProperty(runtime, "__resolve", jsi::Function::createFromHostFunction(
      runtime, jsi::PropNameID::forAscii(runtime, "__resolve"), 1,
      [](jsi::Runtime& runtime, const jsi::Value&, const jsi::Value* values, size_t count) {
        if (count != 2 || !values[0].isString()) throw jsi::JSError(runtime, "native module resolver requires a module name and ABI version");
        const std::string name = values[0].asString(runtime).utf8(runtime);
        const uint32_t abi = requireU32(runtime, values[1], "module ABI version");
        if (!abi) throw jsi::JSError(runtime, "native module ABI version must be positive");
        DehermNativeModuleProviderV1 provider{};
        if (deherm_native_module_resolve_v1(name.c_str(), abi, &provider) != DEHERM_NATIVE_MODULE_REGISTRY_OK)
          return jsi::Value::undefined();
        auto installed = runtime.global().getProperty(runtime, "__defoldModulesV1");
        if (installed.isObject() && installed.asObject(runtime).hasProperty(runtime, name.c_str()))
          throw jsi::JSError(runtime, std::string("native module collides with an installed module: ") + name);
        jsi::Object refreshed(runtime);
        installGeneratedNativeModuleProviders(runtime, refreshed);
        if (!refreshed.hasProperty(runtime, name.c_str())) return jsi::Value::undefined();
        return refreshed.getProperty(runtime, name.c_str());
      }));
}
}  // namespace defold_hermes
#endif
