// Generated by scripts/generate-dmsdk-scalar-thunks.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_scalar.h>
#include <dmsdk/dlib/log.h>

extern "C" {

void deherm_dmsdk_dm_log_log_finalize_v(void)
{
    dmLog::LogFinalize();
}

void deherm_dmsdk_dm_log_finalize_v(void)
{
    dmLogFinalize();
}

} // extern "C"
