// Generated by scripts/generate-script-fixed-tuples.mjs. Do not edit.
#include <defold_hermes/generated_script_fixed_tuples.hpp>
#include <cmath>
#include <cstdio>

namespace defold_hermes::fixed_tuple { namespace {
constexpr Operation kOperations[] = {
  {0, 0x0127f3cbu, "script:bullet3d.constraint.get_anchors", "bullet3d.constraint", "get_anchors", Context::kGlobal, 0, 0, 1, 1, 2},
  {1, 0x03109b88u, "script:bullet3d.constraint.get_hinge_motor", "bullet3d.constraint", "get_hinge_motor", Context::kGlobal, 1, 2, 1, 1, 3},
  {2, 0x04753021u, "script:bullet3d.constraint.get_cone_twist_limits", "bullet3d.constraint", "get_cone_twist_limits", Context::kGlobal, 2, 5, 1, 1, 3},
  {3, 0x25708427u, "script:bullet3d.constraint.get_hinge_limits", "bullet3d.constraint", "get_hinge_limits", Context::kGlobal, 3, 8, 1, 1, 2},
  {4, 0x2d956755u, "script:bullet3d.shape.get_local_transform", "bullet3d.shape", "get_local_transform", Context::kGlobal, 4, 10, 1, 1, 2},
  {5, 0x2fe0fffbu, "script:collectionproxy.set_collection", "collectionproxy", "set_collection", Context::kScriptInstance, 5, 12, 0, 2, 2},
  {6, 0x513bd984u, "script:bullet3d.constraint.get_slider_motor", "bullet3d.constraint", "get_slider_motor", Context::kGlobal, 7, 14, 2, 2, 3},
  {7, 0x55520562u, "script:gui.get_type", "gui", "get_type", Context::kGuiScriptInstance, 9, 17, 1, 1, 2},
  {8, 0x55619c24u, "script:bullet3d.rigid_body.get_damping", "bullet3d.rigid_body", "get_damping", Context::kGlobal, 10, 19, 1, 1, 2},
  {9, 0x797d3f36u, "script:bullet3d.constraint.get_6dof_motor", "bullet3d.constraint", "get_6dof_motor", Context::kGlobal, 11, 21, 2, 2, 4},
  {10, 0x7f5eb33eu, "script:bullet3d.constraint.get_limit", "bullet3d.constraint", "get_limit", Context::kGlobal, 13, 25, 2, 2, 2},
  {11, 0x80ab2ee8u, "script:tilemap.get_bounds", "tilemap", "get_bounds", Context::kScriptInstance, 15, 27, 1, 1, 4},
  {12, 0x8abce1d3u, "script:bullet3d.collision_object.get_world_transform", "bullet3d.collision_object", "get_world_transform", Context::kGlobal, 16, 31, 1, 1, 2},
  {13, 0x9d103820u, "script:sound.get_rms", "sound", "get_rms", Context::kScriptInstance, 17, 33, 2, 2, 2},
  {14, 0x9d6efd31u, "script:vmath.quat_to_euler", "vmath", "quat_to_euler", Context::kGlobal, 19, 35, 1, 1, 3},
  {15, 0xa241b215u, "script:sound.get_peak", "sound", "get_peak", Context::kScriptInstance, 20, 38, 2, 2, 2},
  {16, 0xa8cda9fbu, "script:gui.new_texture", "gui", "new_texture", Context::kGuiScriptInstance, 22, 40, 6, 6, 2},
  {17, 0xae915cbcu, "script:bullet3d.constraint.get_frame_a", "bullet3d.constraint", "get_frame_a", Context::kGlobal, 28, 42, 1, 1, 2},
  {18, 0xb1916175u, "script:bullet3d.constraint.get_frame_b", "bullet3d.constraint", "get_frame_b", Context::kGlobal, 29, 44, 1, 1, 2},
  {19, 0xb915411eu, "script:bullet3d.constraint.get_pivots", "bullet3d.constraint", "get_pivots", Context::kGlobal, 30, 46, 1, 1, 2},
  {20, 0xc4ec6ea3u, "script:bullet3d.constraint.get_angles", "bullet3d.constraint", "get_angles", Context::kGlobal, 31, 48, 1, 1, 2},
  {21, 0xca333d93u, "script:bullet3d.constraint.get_slider_limits", "bullet3d.constraint", "get_slider_limits", Context::kGlobal, 32, 50, 1, 1, 4},
  {22, 0xd052ca5au, "script:bullet3d.constraint.get_axes", "bullet3d.constraint", "get_axes", Context::kGlobal, 33, 54, 1, 1, 2},
  {23, 0xeb7b27deu, "script:window.get_size", "window", "get_size", Context::kGlobal, 34, 56, 0, 0, 2},
};
constexpr uint16_t kArgumentCodecs[] = { 256, 256, 256, 256, 256, 48, 17, 256, 16, 128, 256, 256, 4, 256, 4, 48, 256, 48, 8, 2048, 48, 8, 48, 8, 8, 20, 16, 2, 256, 256, 256, 256, 256, 256 };
constexpr uint16_t kResultCodecs[] = { 512, 512, 2, 8, 8, 8, 8, 8, 8, 8, 512, 2048, 2, 4, 2, 8, 8, 4, 9, 8, 8, 2, 8, 8, 8, 8, 8, 4, 4, 4, 4, 512, 2048, 8, 8, 8, 8, 8, 8, 8, 2, 5, 512, 2048, 512, 2048, 512, 512, 8, 8, 8, 8, 8, 8, 512, 512, 4, 4 };
bool fail(char* error, size_t capacity, const char* message) noexcept { if (error && capacity) std::snprintf(error, capacity, "%s", message); return false; }
uint16_t valueMask(const ScriptValue& value) noexcept {
  switch (value.tag) {
    case ScriptValueTag::kNull: case ScriptValueTag::kUndefined: return kNil;
    case ScriptValueTag::kBoolean: return kBoolean;
    case ScriptValueTag::kNumber: return kInteger | kNumber;
    case ScriptValueTag::kString: return kString;
    case ScriptValueTag::kHandle: if (value.handleKind == ScriptHandleKind::kHash) return kHash; if (value.handleKind == ScriptHandleKind::kUrl) return kUrl; if (value.handleKind == ScriptHandleKind::kGuiNode) return kGuiNode; if (value.handleKind == ScriptHandleKind::kLuaUserdata) return kLuaUserdata; return 0;
    case ScriptValueTag::kDefoldValue: if (value.defoldKind == ScriptDefoldValueKind::kVector3) return kVector3; if (value.defoldKind == ScriptDefoldValueKind::kVector4) return kVector4; if (value.defoldKind == ScriptDefoldValueKind::kQuaternion) return kQuaternion; return 0;
    default: return 0;
  }
}
}
const Operation* find(uint32_t stableId) noexcept { size_t first=0,count=kBindingCount; while(count){size_t step=count/2,index=first+step;if(kOperations[index].stableId<stableId){first=index+1;count-=step+1;}else count=step;} return first<kBindingCount&&kOperations[first].stableId==stableId?&kOperations[first]:nullptr; }
const uint16_t* argumentCodecs() noexcept { return kArgumentCodecs; }
const uint16_t* resultCodecs() noexcept { return kResultCodecs; }
DispatchStatus dispatch(ScriptCallFrame* frame, char* error, size_t capacity, const LuaApi* api) noexcept {
  if (!frame) { fail(error,capacity,"Fixed tuple call frame is null"); return DispatchStatus::kError; }
  const Operation* operation=find(frame->stableId); if(!operation) return DispatchStatus::kMissing; frame->resultCount=0;
  if(frame->argumentCount<operation->requiredArgumentCount||frame->argumentCount>operation->maximumArgumentCount||(frame->argumentCount&&!frame->arguments)){fail(error,capacity,"Fixed tuple argument count does not match descriptor");return DispatchStatus::kError;}
  for(uint32_t index=0;index<frame->argumentCount;++index){const ScriptValue& value=frame->arguments[index];const uint16_t mask=valueMask(value);if(!(mask&kArgumentCodecs[operation->argumentOffset+index])){fail(error,capacity,"Fixed tuple argument tag does not match positional codec");return DispatchStatus::kError;}if(value.tag==ScriptValueTag::kNumber&&(kArgumentCodecs[operation->argumentOffset+index]&kInteger)&&!(kArgumentCodecs[operation->argumentOffset+index]&kNumber)&&(!std::isfinite(value.number)||std::trunc(value.number)!=value.number)){fail(error,capacity,"Fixed tuple integer argument is not exact");return DispatchStatus::kError;}}
  if(!frame->results||frame->resultCapacity<operation->resultCount){fail(error,capacity,"Fixed tuple result storage is exhausted");return DispatchStatus::kError;}
  if(!api||!api->invoke){fail(error,capacity,"Fixed tuple Lua backend is unavailable");return DispatchStatus::kError;}
  return api->invoke(api->context,*operation,kArgumentCodecs,kResultCodecs,frame,error,capacity);
}
}
