// Generated by scripts/generate-dmsdk-enum-value-bindings.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_enum_value.h>
#ifndef DLIB_LOG_DOMAIN
#define DLIB_LOG_DOMAIN "deherm"
#endif
#include <dmsdk/sound/sound.h>
extern "C" {
int32_t deherm_dmsdk_enum_dm_sound_set_group_mute_u64_bool(uint64_t group, uint8_t mute)
{
    return static_cast<int32_t>(dmSound::SetGroupMute(group, mute != 0));
}

int32_t deherm_dmsdk_enum_dm_sound_toggle_group_mute_u64(uint64_t group)
{
    return static_cast<int32_t>(dmSound::ToggleGroupMute(group));
}
}
