// Generated by scripts/generate-scalar-lua-dispatch.mjs. Do not edit.
#include <defold_hermes/scalar_lua_dispatch.hpp>

namespace defold_hermes::lua_bridge::scalar::generated {
namespace {
constexpr uint32_t kStableIds[] = {
  0x00c436b1u,  // script:render.set_blend_func
  0x09a2a376u,  // script:sys.set_connectivity_host
  0x0ae5daf8u,  // script:render.disable_state
  0x0c48cff9u,  // script:profiler.dump_frame
  0x0e1bc679u,  // script:sys.get_config_boolean
  0x11151ff4u,  // script:render.get_height
  0x12793ad8u,  // script:sys.reboot
  0x12c4226cu,  // script:zlib.deflate
  0x173a3da5u,  // script:sys.exit
  0x1c5a6bebu,  // script:html5.run
  0x1e442ce5u,  // script:profiler.scope_begin
  0x210007b3u,  // script:bit.lshift
  0x227c0135u,  // script:bit.tobit
  0x242d741au,  // script:sys.set_render_enable
  0x2465b83fu,  // script:sys.get_connectivity
  0x2b033b37u,  // script:render.set_blend_equation_separate
  0x30fe6227u,  // script:render.get_window_height
  0x3254bd35u,  // script:profiler.enable_ui
  0x32ba58c3u,  // script:render.set_polygon_offset
  0x35cc0bd8u,  // script:socket.sleep
  0x3d3fcc18u,  // script:sound.is_phone_call_active
  0x3e992374u,  // script:window.set_mouse_lock
  0x3ed17a96u,  // script:socket.gettime
  0x3f93a0cdu,  // script:gui.hide_keyboard
  0x4365429bu,  // script:window.get_dim_mode
  0x44a6f990u,  // script:bit.bswap
  0x47238256u,  // script:crash.set_user_field
  0x4a34737cu,  // script:bit.arshift
  0x4ba696b1u,  // script:crash.get_signum
  0x4c783f64u,  // script:sys.get_config_int
  0x5180dd47u,  // script:socket.dns.gethostname
  0x52438b87u,  // script:render.set_color_mask
  0x54bffeddu,  // script:sys.exists
  0x566ec96fu,  // script:profiler.get_memory_usage
  0x58706259u,  // script:render.set_stencil_op
  0x589b402du,  // script:bit.rshift
  0x5dffec87u,  // script:sys.set_vsync_swap_interval
  0x5f73722au,  // script:sys.get_config_number
  0x65523ac8u,  // script:render.set_stencil_func
  0x6d3f85d7u,  // script:render.set_depth_func
  0x703300f2u,  // script:window.set_size
  0x7331494du,  // script:gui.set_safe_area_mode
  0x76629341u,  // script:gui.get_height
  0x794a216au,  // script:sound.is_music_playing
  0x7a16e7ceu,  // script:gui.get_width
  0x7d990000u,  // script:gui.reset_nodes
  0x7edd8a45u,  // script:crash.load_previous
  0x7f7ee579u,  // script:crash.write_dump
  0x8034f652u,  // script:window.get_display_scale
  0x80951fb0u,  // script:render.get_window_width
  0x816e8f15u,  // script:render.set_viewport
  0x843aa738u,  // script:profiler.set_ui_mode
  0x8a50693cu,  // script:crash.get_sys_field
  0x8be686f3u,  // script:profiler.recorded_frame_count
  0x8f7704ceu,  // script:crash.set_file_path
  0x90e85d4eu,  // script:render.disable_material
  0x91a2aff9u,  // script:render.set_depth_mask
  0x947961cfu,  // script:window.set_dim_mode
  0x947ed793u,  // script:bit.tohex
  0x9b852886u,  // script:gui.show_keyboard
  0x9bff33dcu,  // script:liveupdate.is_built_with_excluded_files
  0x9f921fe0u,  // script:window.set_position
  0xa1f62afeu,  // script:render.set_stencil_mask
  0xa3a208ceu,  // script:sys.get_config_string
  0xa9b4706bu,  // script:sys.set_engine_throttle
  0xb11c7968u,  // script:sys.get_host_path
  0xb3f97b1du,  // script:render.get_width
  0xb553b97au,  // script:profiler.enable
  0xb64e7ab0u,  // script:sys.set_update_frequency
  0xb7c3fd1du,  // script:profiler.set_ui_vsync_wait_visible
  0xbe25b237u,  // script:render.enable_state
  0xbe7485e5u,  // script:profiler.scope_end
  0xbf207d2fu,  // script:render.set_blend_func_separate
  0xc38f8455u,  // script:crash.get_extra_data
  0xc759f872u,  // script:crash.get_user_field
  0xc7d4de88u,  // script:profiler.set_ui_view_mode
  0xd0a157c8u,  // script:zlib.inflate
  0xd17589b8u,  // script:sys.get_save_file
  0xd5c0075eu,  // script:bit.ror
  0xdb85cd83u,  // script:window.set_title
  0xde842539u,  // script:gui.set_render_order
  0xdfc0171cu,  // script:bit.rol
  0xe0d9d138u,  // script:bit.bnot
  0xe1755625u,  // script:render.set_cull_face
  0xe3ebc9fau,  // script:gui.reset_keyboard
  0xe61bb95cu,  // script:crash.release
  0xeabefba5u,  // script:profiler.log_text
  0xeb1eb1b2u,  // script:profiler.get_cpu_usage
  0xee38482cu,  // script:sys.get_application_path
  0xf0911340u,  // script:window.get_mouse_lock
};
constexpr const char* kCanonicalIds[] = {
  "script:render.set_blend_func",
  "script:sys.set_connectivity_host",
  "script:render.disable_state",
  "script:profiler.dump_frame",
  "script:sys.get_config_boolean",
  "script:render.get_height",
  "script:sys.reboot",
  "script:zlib.deflate",
  "script:sys.exit",
  "script:html5.run",
  "script:profiler.scope_begin",
  "script:bit.lshift",
  "script:bit.tobit",
  "script:sys.set_render_enable",
  "script:sys.get_connectivity",
  "script:render.set_blend_equation_separate",
  "script:render.get_window_height",
  "script:profiler.enable_ui",
  "script:render.set_polygon_offset",
  "script:socket.sleep",
  "script:sound.is_phone_call_active",
  "script:window.set_mouse_lock",
  "script:socket.gettime",
  "script:gui.hide_keyboard",
  "script:window.get_dim_mode",
  "script:bit.bswap",
  "script:crash.set_user_field",
  "script:bit.arshift",
  "script:crash.get_signum",
  "script:sys.get_config_int",
  "script:socket.dns.gethostname",
  "script:render.set_color_mask",
  "script:sys.exists",
  "script:profiler.get_memory_usage",
  "script:render.set_stencil_op",
  "script:bit.rshift",
  "script:sys.set_vsync_swap_interval",
  "script:sys.get_config_number",
  "script:render.set_stencil_func",
  "script:render.set_depth_func",
  "script:window.set_size",
  "script:gui.set_safe_area_mode",
  "script:gui.get_height",
  "script:sound.is_music_playing",
  "script:gui.get_width",
  "script:gui.reset_nodes",
  "script:crash.load_previous",
  "script:crash.write_dump",
  "script:window.get_display_scale",
  "script:render.get_window_width",
  "script:render.set_viewport",
  "script:profiler.set_ui_mode",
  "script:crash.get_sys_field",
  "script:profiler.recorded_frame_count",
  "script:crash.set_file_path",
  "script:render.disable_material",
  "script:render.set_depth_mask",
  "script:window.set_dim_mode",
  "script:bit.tohex",
  "script:gui.show_keyboard",
  "script:liveupdate.is_built_with_excluded_files",
  "script:window.set_position",
  "script:render.set_stencil_mask",
  "script:sys.get_config_string",
  "script:sys.set_engine_throttle",
  "script:sys.get_host_path",
  "script:render.get_width",
  "script:profiler.enable",
  "script:sys.set_update_frequency",
  "script:profiler.set_ui_vsync_wait_visible",
  "script:render.enable_state",
  "script:profiler.scope_end",
  "script:render.set_blend_func_separate",
  "script:crash.get_extra_data",
  "script:crash.get_user_field",
  "script:profiler.set_ui_view_mode",
  "script:zlib.inflate",
  "script:sys.get_save_file",
  "script:bit.ror",
  "script:window.set_title",
  "script:gui.set_render_order",
  "script:bit.rol",
  "script:bit.bnot",
  "script:render.set_cull_face",
  "script:gui.reset_keyboard",
  "script:crash.release",
  "script:profiler.log_text",
  "script:profiler.get_cpu_usage",
  "script:sys.get_application_path",
  "script:window.get_mouse_lock",
};
constexpr const char* kModulePaths[] = {
  "render",
  "sys",
  "render",
  "profiler",
  "sys",
  "render",
  "sys",
  "zlib",
  "sys",
  "html5",
  "profiler",
  "bit",
  "bit",
  "sys",
  "sys",
  "render",
  "render",
  "profiler",
  "render",
  "socket",
  "sound",
  "window",
  "socket",
  "gui",
  "window",
  "bit",
  "crash",
  "bit",
  "crash",
  "sys",
  "socket.dns",
  "render",
  "sys",
  "profiler",
  "render",
  "bit",
  "sys",
  "sys",
  "render",
  "render",
  "window",
  "gui",
  "gui",
  "sound",
  "gui",
  "gui",
  "crash",
  "crash",
  "window",
  "render",
  "render",
  "profiler",
  "crash",
  "profiler",
  "crash",
  "render",
  "render",
  "window",
  "bit",
  "gui",
  "liveupdate",
  "window",
  "render",
  "sys",
  "sys",
  "sys",
  "render",
  "profiler",
  "sys",
  "profiler",
  "render",
  "profiler",
  "render",
  "crash",
  "crash",
  "profiler",
  "zlib",
  "sys",
  "bit",
  "window",
  "gui",
  "bit",
  "bit",
  "render",
  "gui",
  "crash",
  "profiler",
  "profiler",
  "sys",
  "window",
};
constexpr const char* kMembers[] = {
  "set_blend_func",
  "set_connectivity_host",
  "disable_state",
  "dump_frame",
  "get_config_boolean",
  "get_height",
  "reboot",
  "deflate",
  "exit",
  "run",
  "scope_begin",
  "lshift",
  "tobit",
  "set_render_enabled",
  "get_connectivity",
  "set_blend_equation_separate",
  "get_window_height",
  "enable_ui",
  "set_polygon_offset",
  "sleep",
  "is_phone_call_active",
  "set_mouse_lock",
  "gettime",
  "hide_keyboard",
  "get_dim_mode",
  "bswap",
  "set_user_field",
  "arshift",
  "get_signum",
  "get_config_int",
  "gethostname",
  "set_color_mask",
  "exists",
  "get_memory_usage",
  "set_stencil_op",
  "rshift",
  "set_vsync_swap_interval",
  "get_config_number",
  "set_stencil_func",
  "set_depth_func",
  "set_size",
  "set_safe_area_mode",
  "get_height",
  "is_music_playing",
  "get_width",
  "reset_nodes",
  "load_previous",
  "write_dump",
  "get_display_scale",
  "get_window_width",
  "set_viewport",
  "set_ui_mode",
  "get_sys_field",
  "recorded_frame_count",
  "set_file_path",
  "disable_material",
  "set_depth_mask",
  "set_dim_mode",
  "tohex",
  "show_keyboard",
  "is_built_with_excluded_files",
  "set_position",
  "set_stencil_mask",
  "get_config_string",
  "set_engine_throttle",
  "get_host_path",
  "get_width",
  "enable",
  "set_update_frequency",
  "set_ui_vsync_wait_visible",
  "enable_state",
  "scope_end",
  "set_blend_func_separate",
  "get_extra_data",
  "get_user_field",
  "set_ui_view_mode",
  "inflate",
  "get_save_file",
  "ror",
  "set_title",
  "set_render_order",
  "rol",
  "bnot",
  "set_cull_face",
  "reset_keyboard",
  "release",
  "log_text",
  "get_cpu_usage",
  "get_application_path",
  "get_mouse_lock",
};
constexpr uint16_t kArgumentOffsets[] = {
  0, 2, 3, 4, 4, 6, 6, 12, 13, 14, 15, 16, 18, 19, 20, 20, 22, 22, 23, 25, 26, 26, 27, 27, 27, 27, 28, 30, 32, 33, 35, 35, 39, 40, 40, 43, 45, 46, 48, 51, 52, 54, 55, 55, 55, 55, 55, 55, 55, 55, 55, 59, 60, 62, 62, 63, 63, 64, 65, 67, 69, 69, 71, 72, 74, 76, 77, 77, 78, 79, 80, 81, 81, 85, 86, 88, 89, 90, 92, 94, 95, 96, 98, 99, 100, 100, 101, 102, 102, 102, 102
};
constexpr ScalarCodec kArgumentCodecs[] = {
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kString,
  ScalarCodec::kInteger,
  ScalarCodec::kString,
  ScalarCodec::kBoolean,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kNumber,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kBoolean,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kBoolean,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kBoolean,
  ScalarCodec::kNumber,
  ScalarCodec::kInteger,
  ScalarCodec::kString,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kString,
  ScalarCodec::kNumber,
  ScalarCodec::kBoolean,
  ScalarCodec::kBoolean,
  ScalarCodec::kBoolean,
  ScalarCodec::kBoolean,
  ScalarCodec::kString,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kString,
  ScalarCodec::kNumber,
  ScalarCodec::kInteger,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kNumber,
  ScalarCodec::kInteger,
  ScalarCodec::kString,
  ScalarCodec::kBoolean,
  ScalarCodec::kInteger,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kInteger,
  ScalarCodec::kBoolean,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kNumber,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kBoolean,
  ScalarCodec::kNumber,
  ScalarCodec::kString,
  ScalarCodec::kBoolean,
  ScalarCodec::kNumber,
  ScalarCodec::kBoolean,
  ScalarCodec::kInteger,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kInteger,
  ScalarCodec::kInteger,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kString,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kInteger,
  ScalarCodec::kNumber,
  ScalarCodec::kString,
};
constexpr uint8_t kArgumentOptional[] = {
  0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
constexpr uint8_t kRequiredArgumentCounts[] = {
  2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 0, 2, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 2, 2, 1, 1, 0, 4, 1, 0, 3, 2, 1, 1, 3, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1, 2, 0, 1, 0, 1, 1, 1, 2, 0, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 4, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0, 0
};
constexpr uint8_t kMaximumArgumentCounts[] = {
  2, 1, 1, 0, 2, 0, 6, 1, 1, 1, 1, 2, 1, 1, 0, 2, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 2, 2, 1, 2, 0, 4, 1, 0, 3, 2, 1, 2, 3, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1, 2, 0, 1, 0, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0, 1, 1, 1, 1, 0, 4, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0, 0
};
constexpr ScalarCodec kResultCodecs[] = {
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kBoolean,
  ScalarCodec::kInteger,
  ScalarCodec::kNone,
  ScalarCodec::kString,
  ScalarCodec::kNone,
  ScalarCodec::kString,
  ScalarCodec::kNone,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kInteger,
  ScalarCodec::kNone,
  ScalarCodec::kInteger,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kBoolean,
  ScalarCodec::kNone,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kInteger,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kString,
  ScalarCodec::kNone,
  ScalarCodec::kBoolean,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNumber,
  ScalarCodec::kBoolean,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kNumber,
  ScalarCodec::kInteger,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kString,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kString,
  ScalarCodec::kNone,
  ScalarCodec::kBoolean,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kString,
  ScalarCodec::kNone,
  ScalarCodec::kString,
  ScalarCodec::kInteger,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kNone,
  ScalarCodec::kString,
  ScalarCodec::kString,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNumber,
  ScalarCodec::kNumber,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNone,
  ScalarCodec::kNumber,
  ScalarCodec::kString,
  ScalarCodec::kBoolean,
};
constexpr uint8_t kResultNullable[] = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
constexpr ScalarBindingTables kTables{
  kBindingCount, kArgumentCodecCount, kStableIds, kCanonicalIds, kModulePaths, kMembers,
  kArgumentOffsets, kArgumentCodecs, kArgumentOptional, kRequiredArgumentCounts,
  kMaximumArgumentCounts, kResultCodecs, kResultNullable
};
}  // namespace

const ScalarBindingTables& tables() noexcept { return kTables; }

}  // namespace defold_hermes::lua_bridge::scalar::generated
