// Generated by scripts/generate-dmsdk-base64-span-bindings.mjs. Do not edit.
#include <defold_hermes/generated_dmsdk_base64_span.h>
#include <dmsdk/dlib/crypt.h>
extern "C" {
uint8_t deherm_dmsdk_base64_span_dm_crypt_base64_decode(const uint8_t* input, uint32_t input_length, uint8_t* output, uint32_t* inout_output_length)
{
  if(inout_output_length==nullptr||(input_length!=0&&input==nullptr)||(*inout_output_length!=0&&output==nullptr))return UINT8_C(0); return dmCrypt::Base64Decode(input, input_length, output, inout_output_length) ? UINT8_C(1) : UINT8_C(0);
}
uint8_t deherm_dmsdk_base64_span_dm_crypt_base64_encode(const uint8_t* input, uint32_t input_length, uint8_t* output, uint32_t* inout_output_length)
{
  if(inout_output_length==nullptr||(input_length!=0&&input==nullptr)||(*inout_output_length!=0&&output==nullptr))return UINT8_C(0); return dmCrypt::Base64Encode(input, input_length, output, inout_output_length) ? UINT8_C(1) : UINT8_C(0);
} }
