// Generated by scripts/generate-script-universal-value-bindings.mjs. Do not edit.
var LibraryDefoldHermesScriptUniversalValue = {
  $DEFOLD_HERMES_SCRIPT_UNIVERSAL__deps: [
    'deherm_script_universal_dispatch', 'deherm_script_universal_release',
    '$stackSave', '$stackAlloc', '$stackRestore', '$UTF8ToString', '$stringToUTF8', '$lengthBytesUTF8'
  ],
  $DEFOLD_HERMES_SCRIPT_UNIVERSAL: {
    depth: 0,
    maximumDepth: 8,
    maximumArguments: 32,
    maximumResults: 3,
    maximumEntries: 256,
    maximumValues: 547,
    maximumStringBytes: 65536,
    valueStride: 48,
    entryStride: 8,
    finalizers: null,
    normalizeString: function(value) {
      var result = null;
      for (var index = 0; index < value.length; ++index) {
        var code = value.charCodeAt(index);
        if (code >= 0xd800 && code <= 0xdbff) {
          var next = index + 1 < value.length ? value.charCodeAt(index + 1) : 0;
          if (next >= 0xdc00 && next <= 0xdfff) { if (result !== null) result += value[index] + value[index + 1]; ++index; continue; }
          if (result === null) result = value.slice(0, index);
          result += '\ufffd';
        } else if (code >= 0xdc00 && code <= 0xdfff) {
          if (result === null) result = value.slice(0, index);
          result += '\ufffd';
        } else if (result !== null) result += value[index];
      }
      return result === null ? value : result;
    },
    readU64: function(pointer) {
      return BigInt(HEAPU32[pointer >> 2]) | (BigInt(HEAPU32[(pointer >> 2) + 1]) << BigInt(32));
    },
    writeU64: function(pointer, value) {
      HEAPU32[pointer >> 2] = Number(value & 0xffffffffn);
      HEAPU32[(pointer >> 2) + 1] = Number((value >> BigInt(32)) & BigInt('0xffffffff'));
    },
    releaseToken: function(token) {
      if (!token || token.released) return;
      token.released = true;
      var checkpoint = stackSave();
      try {
        var value = stackAlloc(48);
        HEAPU8.fill(0, value, value + 48);
        HEAPU8[value] = 5;
        HEAPU8[value + 1] = token.kind;
        HEAPU8[value + 3] = token.auxiliary;
        HEAPU32[(value + 28) >> 2] = token.runtime;
        this.writeU64(value + 16, token.payload);
        _deherm_script_universal_release(value);
      } finally { stackRestore(checkpoint); }
    },
    makeHandle: function(kind, auxiliary, runtime, payload) {
      var bridge = this;
      var token = {kind: kind, auxiliary: auxiliary, runtime: runtime, payload: payload, released: false};
      var handle = {
        __dehermHandleV1: true,
        kind: kind,
        semanticKind: auxiliary,
        runtime: runtime,
        payload: payload,
        dispose: function() {
          bridge.releaseToken(token);
          if (bridge.finalizers) bridge.finalizers.unregister(handle);
        }
      };
      if (typeof FinalizationRegistry === 'function') {
        if (!this.finalizers) this.finalizers = new FinalizationRegistry(function(held) {
          DEFOLD_HERMES_SCRIPT_UNIVERSAL.releaseToken(held);
        });
        this.finalizers.register(handle, token, handle);
      }
      return Object.freeze(handle);
    },
    call: function(stableId, args) {
      if (!Number.isInteger(stableId) || stableId < 0 || stableId > 0xffffffff) throw new TypeError('Universal stable ID must be a u32');
      if (!Array.isArray(args) || args.length > this.maximumArguments) throw new TypeError('Universal call arguments violate the generated bound');
      if (this.depth >= 16) throw new RangeError('Universal browser bridge reentrancy depth is exhausted');
      ++this.depth;
      var checkpoint = stackSave();
      var bridge = this;
      try {
        var values = stackAlloc(this.maximumValues * 48);
        var entries = stackAlloc(this.maximumEntries * 8);
        var strings = stackAlloc(this.maximumStringBytes + 1);
        var floats = stackAlloc(16 * 16 * 4);
        var urls = stackAlloc(32 * 32);
        var roots = stackAlloc(this.maximumArguments * 4);
        var outValues = stackAlloc(this.maximumValues * 48);
        var outEntries = stackAlloc(this.maximumEntries * 8);
        var outStrings = stackAlloc(this.maximumStringBytes + 1);
        var outFloats = stackAlloc(16 * 16 * 4);
        var outUrls = stackAlloc(32 * 32);
        var resultRoots = stackAlloc(this.maximumResults * 4);
        var counts = stackAlloc(6 * 4);
        var error = stackAlloc(512);
        var state = {value: 0, entry: 0, string: 0, float: 0, url: 0, ancestors: []};
        function reserveValue() {
          if (state.value >= bridge.maximumValues) throw new RangeError('Universal browser value arena is exhausted');
          var index = state.value++;
          HEAPU8.fill(0, values + index * 48, values + (index + 1) * 48);
          return index;
        }
        function writeValue(value, depth) {
          if (depth > bridge.maximumDepth) throw new RangeError('Universal browser value graph exceeds the depth bound');
          var index = reserveValue();
          var pointer = values + index * 48;
          if (value === undefined) HEAPU8[pointer] = 0;
          else if (value === null) HEAPU8[pointer] = 1;
          else if (typeof value === 'boolean') { HEAPU8[pointer] = 2; HEAPF64[(pointer + 8) >> 3] = value ? 1 : 0; }
          else if (typeof value === 'number') { HEAPU8[pointer] = 3; HEAPF64[(pointer + 8) >> 3] = value; }
          else if (typeof value === 'bigint') {
            if (value < BigInt(0) || value > BigInt('0xffffffffffffffff')) throw new RangeError('Universal hash is outside u64');
            HEAPU8[pointer] = 5; HEAPU8[pointer + 1] = 1; bridge.writeU64(pointer + 16, value);
          } else if (typeof value === 'string') {
            value = bridge.normalizeString(value);
            var length = lengthBytesUTF8(value);
            if (length > bridge.maximumStringBytes - state.string) throw new RangeError('Universal browser string arena is exhausted');
            stringToUTF8(value, strings + state.string, length + 1);
            HEAPU8[pointer] = 4;
            HEAPU32[(pointer + 4) >> 2] = length;
            HEAPU32[(pointer + 24) >> 2] = state.string;
            state.string += length;
          } else if (typeof value === 'object') {
            if (value.__dehermHandleV1 === true) {
              if (!Number.isInteger(value.kind) || value.kind < 1 || value.kind > 5 || !Number.isInteger(value.runtime) || value.runtime < 0 || typeof value.payload !== 'bigint') throw new TypeError('Universal handle is malformed');
              HEAPU8[pointer] = 5; HEAPU8[pointer + 1] = value.kind; HEAPU8[pointer + 3] = value.semanticKind || 0;
              HEAPU32[(pointer + 28) >> 2] = value.runtime; bridge.writeU64(pointer + 16, value.payload);
            } else if (value.__dehermUrlV1 === true) {
              if (state.url >= 32) throw new RangeError('Universal browser URL arena is exhausted');
              var urlPointer = urls + state.url * 32;
              var lanes = [value.socket, value.reserved, value.path, value.fragment];
              for (var lane = 0; lane < 4; ++lane) {
                if (typeof lanes[lane] !== 'bigint' || lanes[lane] < BigInt(0) || lanes[lane] > BigInt('0xffffffffffffffff')) throw new TypeError('Universal URL lane is not u64');
                bridge.writeU64(urlPointer + lane * 8, lanes[lane]);
              }
              HEAPU8[pointer] = 5; HEAPU8[pointer + 1] = 2; HEAPU32[(pointer + 24) >> 2] = state.url++;
            } else if (typeof value.__dehermValueKind === 'string') {
              var kind = value.__dehermValueKind;
              HEAPU8[pointer] = 8;
              if (kind === 'vector3') HEAPU8[pointer + 2] = 1;
              else if (kind === 'vector4') HEAPU8[pointer + 2] = 2;
              else if (kind === 'quaternion') HEAPU8[pointer + 2] = 3;
              else if (kind === 'matrix4') {
                if (!Array.isArray(value.elements) || value.elements.length !== 16 || state.float + 16 > 256) throw new TypeError('Universal Matrix4 is malformed or exhausts scratch');
                HEAPU8[pointer + 2] = 4; HEAPU32[(pointer + 4) >> 2] = 16; HEAPU32[(pointer + 24) >> 2] = state.float;
                for (var matrixLane = 0; matrixLane < 16; ++matrixLane) {
                  if (typeof value.elements[matrixLane] !== 'number') throw new TypeError('Universal Matrix4 lane is not numeric');
                  HEAPF32[(floats >> 2) + state.float++] = value.elements[matrixLane];
                }
                return index;
              } else throw new TypeError('Universal Defold value kind is unknown');
              var names = ['x', 'y', 'z', 'w'];
              var count = kind === 'vector3' ? 3 : 4;
              for (var component = 0; component < count; ++component) {
                if (typeof value[names[component]] !== 'number') throw new TypeError('Universal Defold value lane is not numeric');
                HEAPF32[((pointer + 32) >> 2) + component] = value[names[component]];
              }
            } else {
              if (state.ancestors.indexOf(value) !== -1) throw new TypeError('Universal browser value graph contains a cycle');
              if (depth >= bridge.maximumDepth) throw new RangeError('Universal browser table exceeds the depth bound');
              state.ancestors.push(value);
              var tableKind = Array.isArray(value) ? 1 : value instanceof Map ? 3 : 2;
              var count = tableKind === 1 ? value.length : tableKind === 3 ? value.size : 0;
              if (tableKind === 2) for (var countKey in value) if (Object.prototype.hasOwnProperty.call(value, countKey)) ++count;
              if (count > bridge.maximumEntries - state.entry) throw new RangeError('Universal browser entry arena is exhausted');
              var start = state.entry; state.entry += count;
              HEAPU8[pointer] = 7; HEAPU8[pointer + 3] = tableKind;
              HEAPU32[(pointer + 4) >> 2] = count; HEAPU32[(pointer + 24) >> 2] = start;
              var item = 0;
              function append(key, child) {
                if (item >= count) throw new TypeError('Universal browser table changed while encoding');
                var entryPointer = entries + (start + item++) * 8;
                HEAPU32[entryPointer >> 2] = writeValue(key, depth + 1);
                HEAPU32[(entryPointer + 4) >> 2] = writeValue(child, depth + 1);
              }
              if (tableKind === 1) for (var arrayIndex = 0; arrayIndex < count; ++arrayIndex) append(arrayIndex + 1, value[arrayIndex]);
              else if (tableKind === 3) value.forEach(function(child, key) { append(key, child); });
              else for (var key in value) if (Object.prototype.hasOwnProperty.call(value, key)) append(key, value[key]);
              state.ancestors.pop();
              if (item !== count) throw new TypeError('Universal browser table changed while encoding');
            }
          } else throw new TypeError('Universal browser value kind is unsupported');
          return index;
        }
        for (var argument = 0; argument < args.length; ++argument) HEAPU32[(roots >> 2) + argument] = writeValue(args[argument], 0);
        HEAPU32.fill(0, counts >> 2, (counts >> 2) + 6);
        var status = _deherm_script_universal_dispatch(
          stableId, values, state.value, entries, state.entry, strings, state.string,
          floats, state.float, urls, state.url, roots, args.length,
          outValues, this.maximumValues, counts,
          outEntries, this.maximumEntries, counts + 4,
          outStrings, this.maximumStringBytes, counts + 8,
          outFloats, 256, counts + 12,
          outUrls, 32, counts + 16,
          resultRoots, this.maximumResults, counts + 20,
          error, 512);
        if (status !== 0) throw new Error(UTF8ToString(error));
        var outputValueCount = HEAPU32[counts >> 2];
        var outputEntryCount = HEAPU32[(counts + 4) >> 2];
        var outputStringCount = HEAPU32[(counts + 8) >> 2];
        var outputFloatCount = HEAPU32[(counts + 12) >> 2];
        var outputUrlCount = HEAPU32[(counts + 16) >> 2];
        var outputResultCount = HEAPU32[(counts + 20) >> 2];
        var decoding = [];
        function decode(index, depth) {
          if (index >= outputValueCount || depth > bridge.maximumDepth) throw new Error('Universal browser output graph is invalid');
          if (decoding.indexOf(index) !== -1) throw new Error('Universal browser output graph contains a cycle');
          var pointer = outValues + index * 48;
          var tag = HEAPU8[pointer];
          if (tag === 0) return undefined;
          if (tag === 1) return null;
          if (tag === 2) return HEAPF64[(pointer + 8) >> 3] !== 0;
          if (tag === 3) return HEAPF64[(pointer + 8) >> 3];
          if (tag === 4) {
            var length = HEAPU32[(pointer + 4) >> 2], offset = HEAPU32[(pointer + 24) >> 2];
            if (offset > outputStringCount || length > outputStringCount - offset) throw new Error('Universal browser output string span is invalid');
            return UTF8ToString(outStrings + offset, length);
          }
          if (tag === 5) {
            var kind = HEAPU8[pointer + 1], auxiliary = HEAPU8[pointer + 3];
            if (kind === 1) return bridge.readU64(pointer + 16);
            if (kind === 2) {
              var urlIndex = HEAPU32[(pointer + 24) >> 2];
              if (urlIndex >= outputUrlCount) throw new Error('Universal browser output URL index is invalid');
              var urlPointer = outUrls + urlIndex * 32;
              return Object.freeze({__dehermUrlV1:true, socket:bridge.readU64(urlPointer), reserved:bridge.readU64(urlPointer + 8), path:bridge.readU64(urlPointer + 16), fragment:bridge.readU64(urlPointer + 24)});
            }
            return bridge.makeHandle(kind, auxiliary, HEAPU32[(pointer + 28) >> 2], bridge.readU64(pointer + 16));
          }
          if (tag === 8) {
            var defoldKind = HEAPU8[pointer + 2];
            if (defoldKind === 4) {
              var floatOffset = HEAPU32[(pointer + 24) >> 2];
              if (floatOffset > outputFloatCount || 16 > outputFloatCount - floatOffset) throw new Error('Universal browser output Matrix4 span is invalid');
              var elements = new Array(16);
              for (var lane = 0; lane < 16; ++lane) elements[lane] = HEAPF32[(outFloats >> 2) + floatOffset + lane];
              return {__dehermValueKind:'matrix4', elements:elements};
            }
            var result = {__dehermValueKind:defoldKind === 1 ? 'vector3' : defoldKind === 2 ? 'vector4' : 'quaternion'};
            var names = ['x', 'y', 'z', 'w'];
            for (var component = 0; component < (defoldKind === 1 ? 3 : 4); ++component) result[names[component]] = HEAPF32[((pointer + 32) >> 2) + component];
            return result;
          }
          if (tag === 7) {
            if (depth >= bridge.maximumDepth) throw new Error('Universal browser output table exceeds depth');
            var tableKind = HEAPU8[pointer + 3], count = HEAPU32[(pointer + 4) >> 2], start = HEAPU32[(pointer + 24) >> 2];
            if (start > outputEntryCount || count > outputEntryCount - start) throw new Error('Universal browser output table span is invalid');
            decoding.push(index);
            var table = tableKind === 1 ? new Array(count) : tableKind === 3 ? new Map() : Object.create(null);
            for (var item = 0; item < count; ++item) {
              var entryPointer = outEntries + (start + item) * 8;
              var key = decode(HEAPU32[entryPointer >> 2], depth + 1);
              var child = decode(HEAPU32[(entryPointer + 4) >> 2], depth + 1);
              if (tableKind === 1) {
                if (key !== item + 1) throw new Error('Universal browser output sequence is not dense');
                table[item] = child;
              } else if (tableKind === 3) table.set(key, child);
              else { if (typeof key !== 'string') throw new Error('Universal browser output record key is not a string'); table[key] = child; }
            }
            decoding.pop();
            return table;
          }
          throw new Error('Universal browser output tag is unsupported');
        }
        var decoded = new Array(outputResultCount);
        try {
          for (var resultIndex = 0; resultIndex < outputResultCount; ++resultIndex) decoded[resultIndex] = decode(HEAPU32[(resultRoots >> 2) + resultIndex], 0);
        } catch (decodeError) {
          for (var outputIndex = 0; outputIndex < outputValueCount; ++outputIndex) {
            var outputPointer = outValues + outputIndex * 48;
            var outputKind = HEAPU8[outputPointer + 1];
            if (HEAPU8[outputPointer] === 5 && outputKind >= 3 && outputKind <= 5) _deherm_script_universal_release(outputPointer);
          }
          throw decodeError;
        }
        return outputResultCount === 0 ? undefined : outputResultCount === 1 ? decoded[0] : decoded;
      } finally {
        stackRestore(checkpoint);
        --this.depth;
      }
    },
    install: function() { return {target:'html5-browser-host', call:this.call.bind(this)}; }
  }
};
autoAddDeps(LibraryDefoldHermesScriptUniversalValue, '$DEFOLD_HERMES_SCRIPT_UNIVERSAL');
addToLibrary(LibraryDefoldHermesScriptUniversalValue);
