// Generated by scripts/generate-dmsdk-scratch-scalar-out-bindings.mjs. Do not edit.
var LibraryDefoldHermesDmSdkScratchScalarOut={
  $DEFOLD_HERMES_DMSDK_SCRATCH_SCALAR_OUT__deps:['deherm_dmsdk_scratch_dispatch'],
  $DEFOLD_HERMES_DMSDK_SCRATCH_SCALAR_OUT:{
    abi:Object.freeze({slotBytes:8,maxParameters:4,resultBytes:8,storage:'caller-owned',reentrancy:'rejected'}),
    handleKinds:Object.freeze([{"id":0,"name":"HTextLayout","representation":"opaque"},{"id":1,"name":"dmBuffer::HBuffer","representation":"u32"},{"id":2,"name":"dmGameObject::HInstance","representation":"opaque"},{"id":3,"name":"dmGameObject::HPropertyOptions","representation":"opaque"},{"id":4,"name":"dmHID::HContext","representation":"opaque"},{"id":5,"name":"dmHID::HGamepad","representation":"opaque"}]),
    descriptors:Object.freeze([
      {id:0,resultKind:"enum",parameterKinds:Object.freeze(["handle","u32"]),directions:Object.freeze(["value","inout"]),handleKinds:Object.freeze(["dmBuffer::HBuffer",null]),declarationId:"dmsdk:dmBuffer::GetCount@upstream/defold/engine/dlib/src/dmsdk/dlib/buffer.h:340:97"},
      {id:1,resultKind:"enum",parameterKinds:Object.freeze(["handle","u64","enum","u32"]),directions:Object.freeze(["value","value","inout","inout"]),handleKinds:Object.freeze(["dmBuffer::HBuffer",null,null,null]),declarationId:"dmsdk:dmBuffer::GetStreamType@upstream/defold/engine/dlib/src/dmsdk/dlib/buffer.h:353:98"},
      {id:2,resultKind:"enum",parameterKinds:Object.freeze(["handle","u32"]),directions:Object.freeze(["value","inout"]),handleKinds:Object.freeze(["dmBuffer::HBuffer",null]),declarationId:"dmsdk:dmBuffer::GetContentVersion@upstream/defold/engine/dlib/src/dmsdk/dlib/buffer.h:392:102"},
      {id:3,resultKind:"void",parameterKinds:Object.freeze(["handle","f32","f32"]),directions:Object.freeze(["value","inout","inout"]),handleKinds:Object.freeze(["HTextLayout",null,null]),declarationId:"dmsdk:TextLayoutGetBounds@upstream/defold/engine/font/src/dmsdk/font/text_layout.h:527:867"},
      {id:4,resultKind:"enum",parameterKinds:Object.freeze(["handle","u16","u64"]),directions:Object.freeze(["value","value","inout"]),handleKinds:Object.freeze(["dmGameObject::HInstance",null,null]),declarationId:"dmsdk:dmGameObject::GetComponentId@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:673:1013"},
      {id:5,resultKind:"enum",parameterKinds:Object.freeze(["handle","u32","i32"]),directions:Object.freeze(["value","value","out"]),handleKinds:Object.freeze(["dmGameObject::HPropertyOptions",null,null]),declarationId:"dmsdk:dmGameObject::GetPropertyOptionsIndex@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:917:1041"},
      {id:6,resultKind:"enum",parameterKinds:Object.freeze(["handle","u32","u64"]),directions:Object.freeze(["value","value","out"]),handleKinds:Object.freeze(["dmGameObject::HPropertyOptions",null,null]),declarationId:"dmsdk:dmGameObject::GetPropertyOptionsKey@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:927:1042"},
      {id:7,resultKind:"enum",parameterKinds:Object.freeze(["handle","u64","u64","u64"]),directions:Object.freeze(["value","value","value","out"]),handleKinds:Object.freeze(["dmGameObject::HInstance",null,null,null]),declarationId:"dmsdk:dmGameObject::GetPropertyAsHash@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:938:1043"},
      {id:8,resultKind:"enum",parameterKinds:Object.freeze(["handle","u64","u64","f32"]),directions:Object.freeze(["value","value","value","out"]),handleKinds:Object.freeze(["dmGameObject::HInstance",null,null,null]),declarationId:"dmsdk:dmGameObject::GetPropertyAsFloat@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:949:1044"},
      {id:9,resultKind:"enum",parameterKinds:Object.freeze(["handle","u64","u64","bool"]),directions:Object.freeze(["value","value","value","out"]),handleKinds:Object.freeze(["dmGameObject::HInstance",null,null,null]),declarationId:"dmsdk:dmGameObject::GetPropertyAsBool@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:993:1048"},
      {id:10,resultKind:"bool",parameterKinds:Object.freeze(["handle","handle","u32"]),directions:Object.freeze(["value","value","out"]),handleKinds:Object.freeze(["dmHID::HContext","dmHID::HGamepad",null]),declarationId:"dmsdk:dmHID::GetGamepadUserId@upstream/defold/engine/hid/src/dmsdk/hid/hid.h:619:1616"}
    ]),
    callRaw:function(id,slotsPointer,parameterCount,resultPointer){return _deherm_dmsdk_scratch_dispatch(id,slotsPointer,parameterCount,resultPointer);}
  }
};
autoAddDeps(LibraryDefoldHermesDmSdkScratchScalarOut,'$DEFOLD_HERMES_DMSDK_SCRATCH_SCALAR_OUT');
addToLibrary(LibraryDefoldHermesDmSdkScratchScalarOut);
