import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

function projectSlug(value) {
  const slug = String(value)
    .normalize("NFKD")
    .replace(/[^A-Za-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return slug || "deherm-game";
}

function projectTitle(value) {
  const title = String(value).trim().replace(/[\r\n]+/g, " ");
  return title || "My déherm Game";
}

function templateFiles({ name, packageVersion }) {
  const title = projectTitle(name);
  const packageName = projectSlug(title);
  const dependency = packageVersion === "0.0.0" ? "latest" : `^${packageVersion}`;
  return new Map([
    ["game.project", `[project]\ntitle = ${title}\nversion = 0.1.0\n\n[bootstrap]\nmain_collection = /main/main.collectionc\n\n[display]\nwidth = 960\nheight = 540\nhigh_dpi = 1\n\n[script]\nshared_state = 0\n`],
    ["main/main.collection", `name: "main"\ninstances {\n  id: "controller"\n  prototype: "/main/controller.go"\n}\n`],
    ["main/controller.go", `components {\n  id: "script"\n  component: "/src/main.script"\n}\n`],
    ["src/main.script.ts", `import { defineComponent } from "@deherm/project";\n\nexport default defineComponent({\n  init(): void {\n    console.log("${title.replaceAll("\\", "\\\\").replaceAll('"', '\\"')} is running with déherm");\n  },\n\n  update(_self, _dt: number): void {\n    // Game logic lives here. This file generates /src/main.script.\n  },\n});\n`],
    ["package.json", `${JSON.stringify({
      name: packageName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "deherm dev",
        generate: "deherm generate",
        typecheck: "deherm typecheck",
        verify: "deherm verify-generated"
      },
      devDependencies: { "@ts-defold/deherm": dependency }
    }, null, 2)}\n`],
    [".gitignore", ".deherm/\n.internal/\nbuild/\nnode_modules/\n"],
    ["README.md", `# ${title}\n\nGenerated by \`deherm create\`.\n\n\`\`\`sh\npnpm install\npnpm dev\n\`\`\`\n`]
  ]);
}

export async function createDefoldProject(options = {}) {
  const target = path.resolve(options.directory ?? "deherm-game");
  await mkdir(target, { recursive: true });
  const existing = await readdir(target);
  if (existing.length) {
    throw new Error(`Refusing to scaffold into non-empty directory ${target}`);
  }
  const name = projectTitle(options.name ?? path.basename(target));
  const files = templateFiles({ name, packageVersion: options.packageVersion ?? "0.0.0" });
  for (const [relative, source] of files) {
    const output = path.join(target, relative);
    await mkdir(path.dirname(output), { recursive: true });
    await writeFile(output, source, { flag: "wx" });
  }
  return { projectRoot: target, name, files: [...files.keys()] };
}
