import { strict as assert } from "node:assert";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  createTypeRenderer,
  dmSdkRuntimeOverloads,
  generateRuntime,
  generateTypes
} from "../../../compiler/src/sdk/dmsdk-sdk.mjs";

export {
  createTypeRenderer,
  dmSdkRuntimeOverloads,
  generateRuntime,
  generateTypes
};

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../..");
const inventoryPath = path.join(root, "packages", "bindings", "generated", "defold-sdk-inventory.json");
const irPath = path.join(root, "packages", "bindings", "generated", "defold-sdk-ir.json");
const documentationPath = path.join(root, "packages", "bindings", "generated", "defold-dmsdk-sdk-documentation.json");
const generatedRoot = path.join(root, "packages", "sdk", "src", "generated", "dmsdk");
const check = process.argv.includes("--check");
const banner = "// Generated by packages/compiler/src/sdk/dmsdk-sdk.mjs. Do not edit.";

function compareCodeUnits(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

const callableKinds = new Set(["function", "method", "constructor", "destructor", "function-template"]);

function strategies(declaration) {
  if (!callableKinds.has(declaration.kind)) return ["type-metadata"];
  const reasons = new Set(declaration.policyReasons ?? []);
  const result = [];
  if (reasons.has("callback")) result.push("callback-registry");
  if (reasons.has("pointer/ownership")) result.push("explicit-pointer-ownership");
  if (reasons.has("reference/lifetime")) result.push("borrowed-reference-lifetime");
  if (reasons.has("array/span")) result.push("generated-span-layout");
  if (reasons.has("template") || declaration.kind.includes("template")) result.push("template-specialization-adapter");
  if (reasons.has("named-or-wide-type")) result.push("named-type-or-wide-integer-adapter");
  if (declaration.kind === "method") result.push("opaque-this-handle");
  if (declaration.kind === "constructor") result.push("owned-handle-constructor");
  if (declaration.kind === "destructor") result.push("owned-handle-finalizer");
  if (!result.length) result.push("direct-c-abi");
  return result;
}

function documentation(value, indent = "") {
  if (!value) return [];
  const clean = value.replace(/<[^>]+>/g, " ").replace(/\s+\n/g, "\n").replaceAll("*/", "* /").trim();
  if (!clean) return [];
  return [`${indent}/**`, ...clean.split(/\r?\n/).map((line) => `${indent} * ${line.trim()}`), `${indent} */`];
}

function deprecationNotice(...values) {
  for (const value of values.flat(Infinity)) {
    if (typeof value !== "string") continue;
    const line = value.split(/\r?\n/u).map((item) => item.trim()).find((item) => /\bdeprecated\b/iu.test(item));
    if (line) return line;
  }
  return undefined;
}

function declarationDocumentation(declaration, { includeDescription = true } = {}) {
  const notes = (declaration.notes ?? []).filter((note) => note !== declaration.deprecated);
  return [
    includeDescription ? declaration.description : "",
    notes.length ? `@remarks ${notes.join("\n\n")}` : "",
    declaration.deprecated ? `@deprecated ${declaration.deprecated}` : ""
  ].filter(Boolean).join("\n\n");
}

function docsByHeader(archive) {
  const decoder = new TextDecoder();
  const result = new Map();
  for (const [name, bytes] of Object.entries(archive)) {
    if (!name.startsWith("doc/dmsdk-") || !name.endsWith("_doc.json")) continue;
    let parsed;
    try { parsed = JSON.parse(decoder.decode(bytes)); } catch { continue; }
    const elements = new Map();
    for (const element of parsed.elements ?? []) {
      if (!element?.name) continue;
      const list = elements.get(element.name) ?? [];
      list.push(element);
      elements.set(element.name, list);
    }
    result.set(name, elements);
  }
  return result;
}

function headerDocName(header) {
  const marker = "/dmsdk/";
  const index = header.lastIndexOf(marker);
  if (index < 0) return undefined;
  return `doc/dmsdk-${header.slice(index + marker.length).replaceAll("/", "-")}_doc.json`;
}

function attachDocumentation(inventory, docs) {
  return inventory.declarations.map((declaration) => {
    const headerDocs = docs.get(headerDocName(declaration.header));
    if (!headerDocs) return declaration;
    const shortName = declaration.name.split("::").at(-1).replace(/^~/, "").replace(/<.*>$/, "");
    const element = headerDocs.get(declaration.name)?.[0] ?? headerDocs.get(shortName)?.[0];
    if (!element) return declaration;
    const parameterDocs = new Map((element.parameters ?? []).map((item) => [item.name, item.doc ?? ""]));
    const deprecated = deprecationNotice(element.description, element.brief, element.notes ?? []);
    return {
      ...declaration,
      description: element.description || element.brief || "",
      ...((element.notes ?? []).length ? { notes: [...element.notes] } : {}),
      ...(deprecated ? { deprecated } : {}),
      parameters: (declaration.parameters ?? []).map((item) => ({ ...item, description: parameterDocs.get(item.name) ?? "" })),
      returnDescription: (element.returnvalues ?? []).map((item) => item.doc).filter(Boolean).join("; ")
    };
  });
}

function enrich(inventory) {
  const declarations = inventory.declarations.map((declaration, index) => {
    const normalized = declaration.kind === "enum"
      ? { ...declaration, members: resolvedEnumMembers(declaration) }
      : declaration;
    return {
      ...normalized,
      id: `dmsdk:${normalized.name}@${normalized.header}:${normalized.line ?? 0}:${index}`,
      disposition: normalized.access === "private" || normalized.access === "protected"
        ? "intentionally-hidden-non-public"
        : callableKinds.has(normalized.kind) ? "generated-raw-call" : "generated-type-metadata",
      abiStrategies: strategies(normalized)
    };
  });
  const typeSupportDeclarations = (inventory.typeSupportDeclarations ?? []).map((declaration, index) => ({
    ...declaration,
    id: `dmsdk-support:${declaration.name}@${declaration.header}:${declaration.line ?? 0}:${index}`,
    disposition: "signature-type-support",
    abiStrategies: ["type-metadata"],
  }));
  return {
    schemaVersion: 1,
    defoldRevision: inventory.defoldRevision,
    parseEnvironment: inventory.parseEnvironment,
    headerCount: inventory.headerCount,
    parsedHeaderCount: inventory.parsedHeaderCount,
    failedHeaderCount: inventory.failedHeaderCount,
    diagnosticHeaderCount: inventory.diagnosticHeaderCount,
    declarationCount: declarations.length,
    typeSurfaceUnresolvedCount: undefined,
    runtimeImplementedCount: 0,
    runtimeUnimplementedCount: declarations.filter((item) => callableKinds.has(item.kind) && item.disposition === "generated-raw-call").length,
    declarations,
    typeSupportDeclarations,
  };
}

function resolvedEnumMembers(declaration) {
  let previous = -1;
  return (declaration.members ?? []).map((member) => {
    const value = member.value === undefined ? previous + 1 : member.value;
    assert.ok(Number.isSafeInteger(value), `${declaration.name}.${member.name} has no exact integer enum value`);
    previous = value;
    return { name: member.name, value };
  });
}

async function output(file, contents) {
  const normalized = contents.endsWith("\n") ? contents : `${contents}\n`;
  if (check) {
    let current;
    try { current = await readFile(file, "utf8"); } catch { current = undefined; }
    assert.equal(current, normalized, `${path.relative(root, file)} is stale; run npm run generate:dmsdk-sdk`);
    return;
  }
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, normalized);
}

export async function runDmSdkGenerator() {
  const { unzipSync } = await import("fflate");
  const inventory = JSON.parse(await readFile(inventoryPath, "utf8"));
  const referenceArchive = unzipSync(new Uint8Array(await readFile(path.join(root, "upstream", "ref-doc.zip"))));
  const ir = enrich({ ...inventory, declarations: attachDocumentation(inventory, docsByHeader(referenceArchive)) });
  const renderer = createTypeRenderer(ir);
  const typesSource = generateTypes(ir, renderer);
  const runtimeSource = generateRuntime(ir, renderer);
  ir.unresolvedTypes = [...renderer.unresolved]
    .sort(([left], [right]) => compareCodeUnits(left, right))
    .map(([name, contexts]) => ({ name, contexts: [...contexts].sort() }));
  ir.opaqueTypes = [...renderer.opaque]
    .sort(([left], [right]) => compareCodeUnits(left, right))
    .map(([name, item]) => ({ name, reason: item.reason, contexts: [...item.contexts].sort() }));
  ir.typeSurfaceUnresolvedCount = ir.unresolvedTypes.length;
  // Notes and deprecation tags are documentation inputs for generated
  // TypeScript. They are deliberately excluded from the runtime IR so prose
  // changes do not invalidate ABI classifications or executable evidence.
  const runtimeIr = {
    ...ir,
    declarations: ir.declarations.map(({ deprecated: _deprecated, notes: _notes, ...declaration }) => declaration)
  };
  const sdkDocumentation = {
    schemaVersion: 1,
    kind: "deherm.dmsdk-sdk-documentation",
    defoldRevision: ir.defoldRevision,
    declarations: ir.declarations
      .filter(({ deprecated, notes }) => deprecated || notes?.length)
      .map(({ id, deprecated, notes }) => ({
        id,
        ...(notes?.length ? { notes } : {}),
        ...(deprecated ? { deprecated } : {})
      }))
      .sort((left, right) => compareCodeUnits(left.id, right.id))
  };
  await output(irPath, JSON.stringify(runtimeIr, null, 2));
  await output(documentationPath, JSON.stringify(sdkDocumentation, null, 2));
  await output(path.join(generatedRoot, "types.ts"), typesSource);
  await output(path.join(generatedRoot, "runtime.ts"), runtimeSource);
  await output(
    path.join(generatedRoot, "index.ts"),
    `${banner}\nexport * from "./types";\nexport * from "./runtime";\nexport * from "./scalar";\nexport * from "./enum-value";\nexport * from "./universal";\n`,
  );
  console.log(
    `${check ? "checked" : "generated"} ${ir.declarationCount} dmSDK declarations, ` +
    `${Object.keys(inventory.countsByKind).length} kinds, ${ir.typeSurfaceUnresolvedCount} type-surface unresolved, ` +
    `${ir.runtimeUnimplementedCount} runtime bindings pending`,
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await runDmSdkGenerator();
