// Generated by scripts/generate-dmsdk-universal-bindings.mjs. Do not edit.
#pragma once
#define DEHERM_TEST_TO_NETWORK_ID 234
#define DEHERM_TEST_TO_HOST_ID 229
#define DEHERM_TEST_DMSDK_CATALOG_SHA256 "73a681ee952a7f026e019af3cf0ea89e650db2cd5292aef00f62d7637520add2"
