// Generated by @deherm/compiler dmSDK usage materializer. Do not edit.
#include <defold_hermes/generated_dmsdk_universal.h>
#include <dmsdk/dlib/endian.hpp>
#include <memory>
#include <new>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <type_traits>
[[maybe_unused]] static int deherm_dmsdk_address_fits(uint64_t value){return sizeof(uintptr_t)>=sizeof(uint64_t)||value<=UINTPTR_MAX;}
[[maybe_unused]] static int64_t deherm_dmsdk_unpack_i64(uint64_t bits){int64_t value;memcpy(&value,&bits,sizeof(value));return value;}
[[maybe_unused]] static double deherm_dmsdk_unpack_f64(uint64_t bits){double value;memcpy(&value,&bits,sizeof(value));return value;}

extern "C" DehermDmSdkUniversalStatus deherm_test_to_network(const DehermDmSdkUniversalValue* arguments,uint32_t argument_count,DehermDmSdkUniversalValue* result){
 if(argument_count != UINT32_C(1)) return DEHERM_DMSDK_UNIVERSAL_WRONG_ARITY;
 if((argument_count&&!arguments)||!result) return DEHERM_DMSDK_UNIVERSAL_INVALID_STORAGE;
 if(!(arguments[0].tag == DEHERM_DMSDK_UNIVERSAL_U64 && arguments[0].payload <= UINT32_MAX)) return DEHERM_DMSDK_UNIVERSAL_TYPE_MISMATCH;
 auto value = dmEndian::ToNetwork(static_cast<uint32_t>(arguments[0].payload)); result->payload = static_cast<uint64_t>(value); result->tag = DEHERM_DMSDK_UNIVERSAL_U64;
 return DEHERM_DMSDK_UNIVERSAL_OK;
}
extern "C" DehermDmSdkUniversalStatus deherm_test_to_host(const DehermDmSdkUniversalValue* arguments,uint32_t argument_count,DehermDmSdkUniversalValue* result){
 if(argument_count != UINT32_C(1)) return DEHERM_DMSDK_UNIVERSAL_WRONG_ARITY;
 if((argument_count&&!arguments)||!result) return DEHERM_DMSDK_UNIVERSAL_INVALID_STORAGE;
 if(!(arguments[0].tag == DEHERM_DMSDK_UNIVERSAL_U64 && arguments[0].payload <= UINT32_MAX)) return DEHERM_DMSDK_UNIVERSAL_TYPE_MISMATCH;
 auto value = dmEndian::ToHost(static_cast<uint32_t>(arguments[0].payload)); result->payload = static_cast<uint64_t>(value); result->tag = DEHERM_DMSDK_UNIVERSAL_U64;
 return DEHERM_DMSDK_UNIVERSAL_OK;
}
static DehermDmSdkUniversalStatus deherm_dmsdk_test_provider(void*,const DehermDmSdkUniversalDescriptor* descriptor,const DehermDmSdkUniversalValue* arguments,uint32_t argument_count,DehermDmSdkUniversalValue* result){ if(!descriptor)return DEHERM_DMSDK_UNIVERSAL_PROVIDER_ERROR; switch(descriptor->id){
case UINT32_C(234): return deherm_test_to_network(arguments,argument_count,result);
case UINT32_C(229): return deherm_test_to_host(arguments,argument_count,result);
default:return DEHERM_DMSDK_UNIVERSAL_PROVIDER_ERROR;}}
extern "C" void deherm_dmsdk_test_provider_install(void){deherm_dmsdk_universal_install_provider(deherm_dmsdk_test_provider,nullptr);}
