// Generated by @deherm/compiler dmSDK generated-adapter exact corpus. Do not edit.
#ifndef DLIB_LOG_DOMAIN
#define DLIB_LOG_DOMAIN "deherm"
#endif
#include <defold_hermes/generated_dmsdk_arena_cstring.h>
#include <defold_hermes/generated_dmsdk_astc_probe.h>
#include <defold_hermes/generated_dmsdk_astc_probe_runtime.h>
#include <defold_hermes/generated_dmsdk_base64_span.h>
#include <defold_hermes/generated_dmsdk_base64_span_runtime.h>
#include <defold_hermes/generated_dmsdk_cstring_value.h>
#include <defold_hermes/generated_dmsdk_enum_value.h>
#include <defold_hermes/generated_dmsdk_enum_value_runtime.h>
#include <defold_hermes/generated_dmsdk_fixed_digest.h>
#include <defold_hermes/generated_dmsdk_fixed_digest_runtime.h>
#include <defold_hermes/generated_dmsdk_hash_span.h>
#include <defold_hermes/generated_dmsdk_hash_span_runtime.h>
#include <defold_hermes/generated_dmsdk_hash_state.h>
#include <defold_hermes/generated_dmsdk_named_scalar_runtime.h>
#include <defold_hermes/generated_dmsdk_scalar.h>
#include <defold_hermes/generated_dmsdk_scalar_runtime.h>
#include <defold_hermes/generated_dmsdk_xtea_span.h>
#include <defold_hermes/generated_dmsdk_xtea_span_runtime.h>
#include <dmsdk/dlib/buffer.h>
#include <dmsdk/dlib/crypt.h>
#include <dmsdk/dlib/dstrings.h>
#include <dmsdk/dlib/endian.h>
#include <dmsdk/dlib/endian.hpp>
#include <dmsdk/dlib/hash.h>
#include <dmsdk/dlib/image.h>
#include <dmsdk/dlib/log.h>
#include <dmsdk/dlib/profile.h>
#include <dmsdk/dlib/socket.h>
#include <dmsdk/dlib/sys.h>
#include <dmsdk/dlib/thread.h>
#include <dmsdk/dlib/time.h>
#include <dmsdk/dlib/trig_lookup.h>
#include <dmsdk/dlib/uri.h>
#include <dmsdk/dlib/utf8.h>
#include <dmsdk/gameobject/gameobject.h>
#include <dmsdk/graphics/graphics.h>
#include <dmsdk/resource/resource.h>
#include <dmsdk/resource/resource.hpp>
#include <dmsdk/sound/sound.h>
#include <stdint.h>
#include <string.h>
namespace {uint32_t g_calls[11][32]{};uint32_t g_failures[11][32]{};[[maybe_unused]] bool g_arena_uri_failure=false;[[maybe_unused]] uint64_t pack_f32(float value){uint32_t bits=0;memcpy(&bits,&value,sizeof(bits));return bits;}[[maybe_unused]] uint64_t pack_f64(double value){uint64_t bits=0;memcpy(&bits,&value,sizeof(bits));return bits;}}
const char * dmBuffer::GetResultString(dmBuffer::Result a0){++g_calls[7][0];if(a0!=static_cast<dmBuffer::Result>(0))++g_failures[7][0];return "result_0";}
extern "C" uint32_t deherm_dmsdk_enum_dm_buffer_get_size_for_value_type_i32(int32_t a0){++g_calls[1][0];if(a0!=static_cast<int32_t>(0))++g_failures[1][0];return static_cast<uint32_t>(20736);}
const char * dmBuffer::GetValueTypeString(dmBuffer::ValueType a0){++g_calls[7][1];if(a0!=static_cast<dmBuffer::ValueType>(1))++g_failures[7][1];return "result_1";}
extern "C" uint8_t deherm_dmsdk_base64_span_dm_crypt_base64_decode(const uint8_t* input,uint32_t length,uint8_t* output,uint32_t* inout){++g_calls[4][0];if(!input||length!=UINT32_C(4)||input[0]!=UINT8_C(81)||!output||!inout||*inout!=UINT32_C(32))++g_failures[4][0];if(output&&inout){output[0]=UINT8_C(129);output[1]=UINT8_C(145);*inout=UINT32_C(2);}return UINT8_C(1);}
extern "C" uint8_t deherm_dmsdk_base64_span_dm_crypt_base64_encode(const uint8_t* input,uint32_t length,uint8_t* output,uint32_t* inout){++g_calls[4][1];if(!input||length!=UINT32_C(5)||input[0]!=UINT8_C(66)||!output||!inout||*inout!=UINT32_C(32))++g_failures[4][1];if(output&&inout){output[0]=UINT8_C(130);output[1]=UINT8_C(146);*inout=UINT32_C(2);}return UINT8_C(1);}
extern "C" uint8_t deherm_dmsdk_xtea_span_dm_crypt_decrypt(uint8_t* data,uint32_t length,const uint8_t* key,uint32_t key_length){++g_calls[5][0];if(!data||length!=UINT32_C(9)||data[0]!=UINT8_C(65)||!key||key_length!=UINT32_C(3)||key[0]!=UINT8_C(97))++g_failures[5][0];if(data)data[0]=UINT8_C(161);return UINT8_C(1);}
extern "C" uint8_t deherm_dmsdk_xtea_span_dm_crypt_encrypt(uint8_t* data,uint32_t length,const uint8_t* key,uint32_t key_length){++g_calls[5][1];if(!data||length!=UINT32_C(10)||data[0]!=UINT8_C(66)||!key||key_length!=UINT32_C(4)||key[0]!=UINT8_C(98))++g_failures[5][1];if(data)data[0]=UINT8_C(162);return UINT8_C(1);}
extern "C" uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_md5(const uint8_t* input,uint32_t length,uint8_t* output,uint32_t capacity){++g_calls[2][0];if(!input||length!=UINT32_C(5)||capacity<UINT32_C(16))++g_failures[2][0];for(uint32_t i=0;i<UINT32_C(16);++i)output[i]=static_cast<uint8_t>(UINT8_C(112)+i);return UINT8_C(1);}
extern "C" uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_sha1(const uint8_t* input,uint32_t length,uint8_t* output,uint32_t capacity){++g_calls[2][1];if(!input||length!=UINT32_C(6)||capacity<UINT32_C(20))++g_failures[2][1];for(uint32_t i=0;i<UINT32_C(20);++i)output[i]=static_cast<uint8_t>(UINT8_C(113)+i);return UINT8_C(1);}
extern "C" uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_sha256(const uint8_t* input,uint32_t length,uint8_t* output,uint32_t capacity){++g_calls[2][2];if(!input||length!=UINT32_C(7)||capacity<UINT32_C(32))++g_failures[2][2];for(uint32_t i=0;i<UINT32_C(32);++i)output[i]=static_cast<uint8_t>(UINT8_C(114)+i);return UINT8_C(1);}
extern "C" uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_sha512(const uint8_t* input,uint32_t length,uint8_t* output,uint32_t capacity){++g_calls[2][3];if(!input||length!=UINT32_C(8)||capacity<UINT32_C(64))++g_failures[2][3];for(uint32_t i=0;i<UINT32_C(64);++i)output[i]=static_cast<uint8_t>(UINT8_C(115)+i);return UINT8_C(1);}
extern "C" uint16_t deherm_dmsdk_dm_endian_byte_swap_u16(uint16_t a0){++g_calls[0][0];if(a0!=static_cast<uint16_t>(4352))++g_failures[0][0];return static_cast<uint16_t>(20736);}
extern "C" uint32_t deherm_dmsdk_dm_endian_byte_swap_u32(uint32_t a0){++g_calls[0][1];if(a0!=static_cast<uint32_t>(4369))++g_failures[0][1];return static_cast<uint32_t>(20753);}
extern "C" uint64_t deherm_dmsdk_dm_endian_byte_swap_u64(uint64_t a0){++g_calls[0][2];if(a0!=static_cast<uint64_t>(UINT64_C(4294971682)))++g_failures[0][2];return static_cast<uint64_t>(UINT64_C(4294988066));}
extern "C" uint32_t deherm_dmsdk_dm_endian_to_host_u32(uint32_t a0){++g_calls[0][3];if(a0!=static_cast<uint32_t>(4403))++g_failures[0][3];return static_cast<uint32_t>(20787);}
extern "C" uint64_t deherm_dmsdk_dm_endian_to_host_u64(uint64_t a0){++g_calls[0][4];if(a0!=static_cast<uint64_t>(UINT64_C(4294971716)))++g_failures[0][4];return static_cast<uint64_t>(UINT64_C(4294988100));}
extern "C" uint16_t deherm_dmsdk_dm_endian_to_host_u16(uint16_t a0){++g_calls[0][5];if(a0!=static_cast<uint16_t>(4437))++g_failures[0][5];return static_cast<uint16_t>(20821);}
extern "C" uint64_t deherm_dmsdk_dm_endian_to_network_u64(uint64_t a0){++g_calls[0][6];if(a0!=static_cast<uint64_t>(UINT64_C(4294971750)))++g_failures[0][6];return static_cast<uint64_t>(UINT64_C(4294988134));}
extern "C" uint16_t deherm_dmsdk_dm_endian_to_network_u16(uint16_t a0){++g_calls[0][7];if(a0!=static_cast<uint16_t>(4471))++g_failures[0][7];return static_cast<uint16_t>(20855);}
extern "C" uint32_t deherm_dmsdk_dm_endian_to_network_u32(uint32_t a0){++g_calls[0][8];if(a0!=static_cast<uint32_t>(4488))++g_failures[0][8];return static_cast<uint32_t>(20872);}
namespace dmGameObject{dmhash_t CreateInstanceId(){++g_calls[10][0];return static_cast<dmhash_t>(UINT64_C(4294988032));}}
extern "C" int32_t deherm_dmsdk_enum_dm_graphics_get_installed_adapter_family_v(){++g_calls[1][1];return static_cast<int32_t>(2);}
const char * dmGraphics::GetTextureFormatLiteral(dmGraphics::TextureFormat a0){++g_calls[7][2];if(a0!=static_cast<dmGraphics::TextureFormat>(2))++g_failures[7][2];return "result_2";}
const char * dmGraphics::GetTextureTypeLiteral(dmGraphics::TextureType a0){++g_calls[7][3];if(a0!=static_cast<dmGraphics::TextureType>(3))++g_failures[7][3];return "result_3";}
extern "C" uint8_t deherm_dmsdk_hash_span_dm_hash_buffer32(const uint8_t* input,uint32_t length,uint32_t* output){++g_calls[3][0];if(!input||length!=UINT32_C(7)||input[0]!=UINT8_C(48)||!output)++g_failures[3][0];*output=UINT32_C(1694498816);return UINT8_C(1);}
extern "C" uint8_t deherm_dmsdk_hash_span_dm_hash_buffer64(const uint8_t* input,uint32_t length,uint64_t* output){++g_calls[3][1];if(!input||length!=UINT32_C(8)||input[0]!=UINT8_C(49)||!output)++g_failures[3][1];*output=UINT64_C(7277816997830722000);return UINT8_C(1);}
void dmHashClone32(HashState32* d,const HashState32* s,bool reverse){++g_calls[9][0];d->m_Hash=s->m_Hash+(reverse?7:1);d->m_Tail=s->m_Tail;d->m_Count=s->m_Count;d->m_Size=s->m_Size;d->m_ReverseHashEntryIndex=0;}
void dmHashClone64(HashState64* d,const HashState64* s,bool reverse){++g_calls[9][1];d->m_Hash=s->m_Hash+(reverse?9:1);d->m_Tail=s->m_Tail;d->m_Count=s->m_Count;d->m_Size=s->m_Size;d->m_ReverseHashEntryIndex=0;}
uint32_t dmHashFinal32(HashState32* s){++g_calls[9][2];return s->m_Hash;}
uint64_t dmHashFinal64(HashState64* s){++g_calls[9][3];return s->m_Hash;}
void dmHashInit32(HashState32* s,bool reverse){++g_calls[9][4];s->m_Hash=reverse?32:3;s->m_Tail=0;s->m_Count=0;s->m_Size=0;s->m_ReverseHashEntryIndex=0;}
void dmHashInit64(HashState64* s,bool reverse){++g_calls[9][5];s->m_Hash=reverse?64:6;s->m_Tail=0;s->m_Count=0;s->m_Size=0;s->m_ReverseHashEntryIndex=0;}
void dmHashRelease32(HashState32*){++g_calls[9][6];}
void dmHashRelease64(HashState64*){++g_calls[9][7];}
uint32_t dmHashString32(const char* a0){++g_calls[7][4];if(a0==nullptr||strcmp(a0,"exact_4_0")!=0)++g_failures[7][4];return static_cast<uint32_t>(20804);}
uint64_t dmHashString64(const char* a0){++g_calls[7][5];if(a0==nullptr||strcmp(a0,"exact_5_0")!=0)++g_failures[7][5];return static_cast<uint64_t>(UINT64_C(4294988117));}
void dmHashUpdateBuffer32(HashState32* s,const void* input,uint32_t length){++g_calls[9][8];const auto* bytes=static_cast<const uint8_t*>(input);for(uint32_t i=0;i<length;++i)s->m_Hash+=bytes[i];}
void dmHashUpdateBuffer64(HashState64* s,const void* input,uint32_t length){++g_calls[9][9];const auto* bytes=static_cast<const uint8_t*>(input);for(uint32_t i=0;i<length;++i)s->m_Hash+=bytes[i];}
extern "C" uint8_t deherm_dmsdk_astc_probe_dm_image_get_astc_block_size(const uint8_t* input,uint32_t length,DehermDmSdkAstcProbeResult* output){++g_calls[6][0];if(!input||length!=UINT32_C(16)||input[0]!=UINT8_C(81)||!output)++g_failures[6][0];if(output){output->width=UINT32_C(101);output->height=UINT32_C(201);output->depth=UINT32_C(301);}return UINT8_C(1);}
extern "C" uint8_t deherm_dmsdk_astc_probe_dm_image_get_astc_dimensions(const uint8_t* input,uint32_t length,DehermDmSdkAstcProbeResult* output){++g_calls[6][1];if(!input||length!=UINT32_C(17)||input[0]!=UINT8_C(82)||!output)++g_failures[6][1];if(output){output->width=UINT32_C(102);output->height=UINT32_C(202);output->depth=UINT32_C(302);}return UINT8_C(1);}
extern "C" void deherm_dmsdk_enum_dm_log_setlevel_i32(int32_t a0){++g_calls[1][2];if(a0!=static_cast<int32_t>(2))++g_failures[1][2];}
extern "C" int32_t deherm_dmsdk_enum_dm_log_get_level_v(){++g_calls[1][3];return static_cast<int32_t>(4);}
extern "C" void deherm_dmsdk_enum_dm_log_set_level_i32(int32_t a0){++g_calls[1][4];if(a0!=static_cast<int32_t>(4))++g_failures[1][4];}
uint32_t dmResource::GetCanonicalPath(const char* value,char* output,uint32_t capacity){++g_calls[8][0];if(!value||strcmp(value,"arena_0")!=0||!output||capacity!=UINT32_C(64))++g_failures[8][0];if(output&&capacity){const char* value="result_0";const size_t length=strlen(value);const size_t copied=length<capacity-1?length:capacity-1;memcpy(output,value,copied);output[copied]='\0';}return UINT32_C(500);}
const char * dmResource::GetExtFromPath(const char* a0){++g_calls[7][6];if(a0==nullptr||strcmp(a0,"exact_6_0")!=0)++g_failures[7][6];return "result_6";}
const char * dmSocket::ResultToString(dmSocket::Result a0){++g_calls[7][7];if(a0!=static_cast<dmSocket::Result>(-7))++g_failures[7][7];return "result_7";}
namespace dmSound{bool IsGroupMuted(dmhash_t a0){++g_calls[10][1];if(a0!=static_cast<dmhash_t>(UINT64_C(4294971665)))++g_failures[10][1];return static_cast<bool>(UINT8_C(1));}}
extern "C" int32_t deherm_dmsdk_enum_dm_sound_set_group_mute_u64_bool(uint64_t a0,uint8_t a1){++g_calls[1][5];if(a0!=static_cast<uint64_t>(UINT64_C(4294971733)))++g_failures[1][5];if(a1!=static_cast<uint8_t>(UINT8_C(1)))++g_failures[1][5];return static_cast<int32_t>(-5);}
extern "C" int32_t deherm_dmsdk_enum_dm_sound_toggle_group_mute_u64(uint64_t a0){++g_calls[1][6];if(a0!=static_cast<uint64_t>(UINT64_C(4294971750)))++g_failures[1][6];return static_cast<int32_t>(-6);}
int dmStrCaseCmp(const char* a0,const char* a1){++g_calls[7][8];if(a0==nullptr||strcmp(a0,"exact_8_0")!=0)++g_failures[7][8];if(a1==nullptr||strcmp(a1,"exact_8_1")!=0)++g_failures[7][8];return static_cast<int>(20872);}
void dmStrError(char* output,size_t capacity,int error){++g_calls[8][1];if(!output||capacity!=size_t(64)||error!=101)++g_failures[8][1];if(output&&capacity){const char* value="result_1";const size_t length=strlen(value);const size_t copied=length<capacity-1?length:capacity-1;memcpy(output,value,copied);output[copied]='\0';}}
size_t dmStrTrim(char* output,size_t capacity,const char* value){++g_calls[8][2];if(!value||strcmp(value,"arena_2")!=0||!output||capacity!=size_t(64))++g_failures[8][2];if(output&&capacity){const char* value="result_2";const size_t length=strlen(value);const size_t copied=length<capacity-1?length:capacity-1;memcpy(output,value,copied);output[copied]='\0';}return size_t(502);}
bool dmSys::Exists(const char* a0){++g_calls[7][9];if(a0==nullptr||strcmp(a0,"exact_9_0")!=0)++g_failures[7][9];return static_cast<bool>(UINT8_C(1));}
dmSys::Result dmSys::Rename(const char* a0,const char* a1){++g_calls[7][10];if(a0==nullptr||strcmp(a0,"exact_10_0")!=0)++g_failures[7][10];if(a1==nullptr||strcmp(a1,"exact_10_1")!=0)++g_failures[7][10];return static_cast<dmSys::Result>(-11);}
dmSys::Result dmSys::Unlink(const char* a0){++g_calls[7][11];if(a0==nullptr||strcmp(a0,"exact_11_0")!=0)++g_failures[7][11];return static_cast<dmSys::Result>(-12);}
namespace dmThread{TlsKey AllocTls(){++g_calls[10][2];return static_cast<TlsKey>(UINT64_C(4294988066));}}
namespace dmThread{void Detach(Thread a0){++g_calls[10][3];if(a0!=static_cast<Thread>(UINT64_C(4294971699)))++g_failures[10][3];}}
namespace dmThread{void FreeTls(TlsKey a0){++g_calls[10][4];if(a0!=static_cast<TlsKey>(UINT64_C(4294971716)))++g_failures[10][4];}}
namespace dmThread{Thread GetCurrentThread(){++g_calls[10][5];return static_cast<Thread>(UINT64_C(4294988117));}}
namespace dmThread{void Join(Thread a0){++g_calls[10][6];if(a0!=static_cast<Thread>(UINT64_C(4294971750)))++g_failures[10][6];}}
extern "C" uint64_t deherm_dmsdk_dm_time_get_monotonic_time_v(){++g_calls[0][9];return static_cast<uint64_t>(UINT64_C(4294988185));}
extern "C" uint64_t deherm_dmsdk_dm_time_get_time_v(){++g_calls[0][10];return static_cast<uint64_t>(UINT64_C(4294988202));}
extern "C" void deherm_dmsdk_dm_time_sleep_u32(uint32_t a0){++g_calls[0][11];if(a0!=static_cast<uint32_t>(4539))++g_failures[0][11];}
extern "C" float deherm_dmsdk_dm_trig_lookup_cos_f32(float a0){++g_calls[0][12];if(a0!=static_cast<float>(112.25f))++g_failures[0][12];return static_cast<float>(112.75f);}
extern "C" float deherm_dmsdk_dm_trig_lookup_sin_f32(float a0){++g_calls[0][13];if(a0!=static_cast<float>(113.25f))++g_failures[0][13];return static_cast<float>(113.75f);}
dmURI::Result dmURI::Encode(const char* value,char* output,uint32_t capacity,uint32_t* written){++g_calls[8][3];if(!value||strcmp(value,"arena_3")!=0||!output||capacity!=UINT32_C(64)||!written)++g_failures[8][3];if(output&&capacity){const char* value="result_3";const size_t length=strlen(value);const size_t copied=length<capacity-1?length:capacity-1;memcpy(output,value,copied);output[copied]='\0';}if(written)*written=UINT32_C(9);return g_arena_uri_failure?dmURI::RESULT_TOO_SMALL_BUFFER:dmURI::RESULT_OK;}
extern "C" uint8_t deherm_dmsdk_dm_utf8_is_breaking_u32(uint32_t a0){++g_calls[0][14];if(a0!=static_cast<uint32_t>(4590))++g_failures[0][14];return static_cast<uint8_t>(UINT8_C(1));}
extern "C" uint8_t deherm_dmsdk_dm_utf8_is_white_space_u32(uint32_t a0){++g_calls[0][15];if(a0!=static_cast<uint32_t>(4607))++g_failures[0][15];return static_cast<uint8_t>(UINT8_C(1));}
uint32_t dmUtf8::StrLen(const char* a0){++g_calls[7][12];if(a0==nullptr||strcmp(a0,"exact_12_0")!=0)++g_failures[7][12];return static_cast<uint32_t>(20940);}
extern "C" uint16_t deherm_dmsdk_endian_swap16_u16(uint16_t a0){++g_calls[0][16];if(a0!=static_cast<uint16_t>(4624))++g_failures[0][16];return static_cast<uint16_t>(21008);}
extern "C" uint32_t deherm_dmsdk_endian_swap32_u32(uint32_t a0){++g_calls[0][17];if(a0!=static_cast<uint32_t>(4641))++g_failures[0][17];return static_cast<uint32_t>(21025);}
extern "C" uint64_t deherm_dmsdk_endian_swap64_u64(uint64_t a0){++g_calls[0][18];if(a0!=static_cast<uint64_t>(UINT64_C(4294971954)))++g_failures[0][18];return static_cast<uint64_t>(UINT64_C(4294988338));}
extern "C" uint16_t deherm_dmsdk_endian_to_host16_u16(uint16_t a0){++g_calls[0][19];if(a0!=static_cast<uint16_t>(4675))++g_failures[0][19];return static_cast<uint16_t>(21059);}
extern "C" uint32_t deherm_dmsdk_endian_to_host32_u32(uint32_t a0){++g_calls[0][20];if(a0!=static_cast<uint32_t>(4692))++g_failures[0][20];return static_cast<uint32_t>(21076);}
extern "C" uint64_t deherm_dmsdk_endian_to_host64_u64(uint64_t a0){++g_calls[0][21];if(a0!=static_cast<uint64_t>(UINT64_C(4294972005)))++g_failures[0][21];return static_cast<uint64_t>(UINT64_C(4294988389));}
extern "C" uint16_t deherm_dmsdk_endian_to_network16_u16(uint16_t a0){++g_calls[0][22];if(a0!=static_cast<uint16_t>(4726))++g_failures[0][22];return static_cast<uint16_t>(21110);}
extern "C" uint32_t deherm_dmsdk_endian_to_network32_u32(uint32_t a0){++g_calls[0][23];if(a0!=static_cast<uint32_t>(4743))++g_failures[0][23];return static_cast<uint32_t>(21127);}
extern "C" uint64_t deherm_dmsdk_endian_to_network64_u64(uint64_t a0){++g_calls[0][24];if(a0!=static_cast<uint64_t>(UINT64_C(4294972056)))++g_failures[0][24];return static_cast<uint64_t>(UINT64_C(4294988440));}
extern "C" uint8_t deherm_dmsdk_profile_is_initialized_v(){++g_calls[0][25];return static_cast<uint8_t>(UINT8_C(1));}
void ProfilePropertyAddF32(ProfileIdx a0,float a1){++g_calls[10][7];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971767)))++g_failures[10][7];if(a1!=static_cast<float>(107.25f))++g_failures[10][7];}
void ProfilePropertyAddF64(ProfileIdx a0,double a1){++g_calls[10][8];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971784)))++g_failures[10][8];if(a1!=static_cast<double>(108.375))++g_failures[10][8];}
void ProfilePropertyAddS32(ProfileIdx a0,int32_t a1){++g_calls[10][9];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971801)))++g_failures[10][9];if(a1!=static_cast<int32_t>(4506))++g_failures[10][9];}
void ProfilePropertyAddS64(ProfileIdx a0,int64_t a1){++g_calls[10][10];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971818)))++g_failures[10][10];if(a1!=static_cast<int64_t>(4523))++g_failures[10][10];}
void ProfilePropertyAddU32(ProfileIdx a0,uint32_t a1){++g_calls[10][11];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971835)))++g_failures[10][11];if(a1!=static_cast<uint32_t>(4540))++g_failures[10][11];}
void ProfilePropertyAddU64(ProfileIdx a0,uint64_t a1){++g_calls[10][12];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971852)))++g_failures[10][12];if(a1!=static_cast<uint64_t>(UINT64_C(4294971853)))++g_failures[10][12];}
void ProfilePropertySetBool(ProfileIdx a0,int a1){++g_calls[10][13];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971869)))++g_failures[10][13];if(a1!=static_cast<int>(4574))++g_failures[10][13];}
void ProfilePropertySetF32(ProfileIdx a0,float a1){++g_calls[10][14];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971886)))++g_failures[10][14];if(a1!=static_cast<float>(114.25f))++g_failures[10][14];}
void ProfilePropertySetF64(ProfileIdx a0,double a1){++g_calls[10][15];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971903)))++g_failures[10][15];if(a1!=static_cast<double>(115.375))++g_failures[10][15];}
void ProfilePropertySetS32(ProfileIdx a0,int32_t a1){++g_calls[10][16];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971920)))++g_failures[10][16];if(a1!=static_cast<int32_t>(4625))++g_failures[10][16];}
void ProfilePropertySetS64(ProfileIdx a0,int64_t a1){++g_calls[10][17];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971937)))++g_failures[10][17];if(a1!=static_cast<int64_t>(4642))++g_failures[10][17];}
void ProfilePropertySetU32(ProfileIdx a0,uint32_t a1){++g_calls[10][18];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971954)))++g_failures[10][18];if(a1!=static_cast<uint32_t>(4659))++g_failures[10][18];}
void ProfilePropertySetU64(ProfileIdx a0,uint64_t a1){++g_calls[10][19];if(a0!=static_cast<ProfileIdx>(UINT64_C(4294971971)))++g_failures[10][19];if(a1!=static_cast<uint64_t>(UINT64_C(4294971972)))++g_failures[10][19];}
uint32_t ResourceGetCanonicalPath(const char* value,char* output,uint32_t capacity){++g_calls[8][4];if(!value||strcmp(value,"arena_4")!=0||!output||capacity!=UINT32_C(64))++g_failures[8][4];if(output&&capacity){const char* value="result_4";const size_t length=strlen(value);const size_t copied=length<capacity-1?length:capacity-1;memcpy(output,value,copied);output[copied]='\0';}return UINT32_C(504);}
const char * ResourceGetExtFromPath(const char* a0){++g_calls[7][13];if(a0==nullptr||strcmp(a0,"exact_13_0")!=0)++g_failures[7][13];return "result_13";}
struct DehermDmSdkAdapterExactVector{uint32_t recipe_id;uint16_t adapter_id;const char* family;const char* sha256;};
static const DehermDmSdkAdapterExactVector kVectors[]={
 {UINT32_C(176),UINT16_C(0),"cstringValue","d4fa99f479df7f7d87ad6b38537e876539662012249bb8c6c8e5adfdb75acde5"},
 {UINT32_C(177),UINT16_C(0),"enumValue","267953b407b5929a0d1bf10ae04a0b58b0cb8c624c44c6fe9394fc6333be6f99"},
 {UINT32_C(180),UINT16_C(1),"cstringValue","73e02f80b073230d01d226192ff112ef6b62b43a055766b2b9a445f0a0c9a042"},
 {UINT32_C(204),UINT16_C(0),"base64Span","b1b333aea5c670f0a214136fbe7e9733b5a441ee6a9fc5e46dbea9c0348eed24"},
 {UINT32_C(205),UINT16_C(1),"base64Span","ab7b2c35eafab09bf32fe580f89db5df6f1d14558eeb78df2e951b68e85a9491"},
 {UINT32_C(206),UINT16_C(0),"xteaSpan","61ecc9c452eb916692534854b2d571a92aa962b867723a5bed57480939f1e0e4"},
 {UINT32_C(207),UINT16_C(1),"xteaSpan","2c5c6699d7cf0df9fca09a0e550f9adef49482a7649922afc11be03d753813dd"},
 {UINT32_C(208),UINT16_C(0),"fixedDigest","c75c0f00642021c3c49f51f9050c1dd87553f9b4cb1e7ec90b25e42069fb8fcb"},
 {UINT32_C(209),UINT16_C(1),"fixedDigest","4407182131d8709cfb37e4af0f67523d9f3fa12305e38d964043e00bb6efd555"},
 {UINT32_C(210),UINT16_C(2),"fixedDigest","cc8517a2a74ee0e8437e4418e4b7e6fc29c09cf551e0232178ba094fdcde5806"},
 {UINT32_C(211),UINT16_C(3),"fixedDigest","1e872e8196a18f1bb6cc88bd2d474b7c286c71a188385ad43ffb8e6d76bff0b7"},
 {UINT32_C(226),UINT16_C(0),"scalar","876d29154997c0be0ebc84a24aa0a668917394a6b3b0b448921a355ed6aac037"},
 {UINT32_C(227),UINT16_C(1),"scalar","b624732e3309b0f84fb3b36c0c594d443cf9d0f21987fb0e2f558709bbdfa086"},
 {UINT32_C(228),UINT16_C(2),"scalar","90f99e00d31a7144d6183a831a461c1c2515794ed074d2fbcad7d48a09021e56"},
 {UINT32_C(229),UINT16_C(3),"scalar","dd062471ab992db7ca7bd72e3557ac65690d2068bb0b4b8bd17d6e5bbbb7e8c1"},
 {UINT32_C(230),UINT16_C(4),"scalar","e51e36c9034b610791852ca299b0545f7f8091195d405e2daf79392b5eea8ffa"},
 {UINT32_C(231),UINT16_C(5),"scalar","306d7277c4daa9f763ab5846fd5d658eacbe9b87bc1066d30404845dc002fa5d"},
 {UINT32_C(232),UINT16_C(6),"scalar","ab99f41d2dccde87055363e9426c2f4ea5e2fa41f27c3f5748a3fcb4486013e8"},
 {UINT32_C(233),UINT16_C(7),"scalar","d1e77e9284cf77d22eb4b0039bdb4b094e5fa0b8d7f05df77fb7fc6754abc212"},
 {UINT32_C(234),UINT16_C(8),"scalar","c4a9cfee09c3702c33277a2e7a496b303f3005f3beaefe5e751a61d1ba159944"},
 {UINT32_C(299),UINT16_C(0),"namedScalar","c4f34e9a5844202b78d993cb2f10e4f4b405310896f02f007cb4238b62a60d45"},
 {UINT32_C(510),UINT16_C(1),"enumValue","f521962f6e1b9a63d1276dc5cd5f190a508b253fe3431610c1408ad7f27025f6"},
 {UINT32_C(541),UINT16_C(2),"cstringValue","4216f1f23fa08797a92e265b41b66421e612eb5a0d1d8a6809aa6e81c279bb01"},
 {UINT32_C(548),UINT16_C(3),"cstringValue","587a287a640901a6d5db6066be6fab44bf1bb3e67f55e8b04222f3c1c48d68ba"},
 {UINT32_C(650),UINT16_C(0),"hashSpan","0c124d38c7930736dd542b21f5e238c89af154f4a633e99a2a3867c4c89d2f13"},
 {UINT32_C(651),UINT16_C(1),"hashSpan","85723942de5f00cabfb5e9827d3b29ba1b52c4e2071f1cb5016e650ed398bcf4"},
 {UINT32_C(652),UINT16_C(0),"hashState","b84c0bf9a6f2fc20f35b65ed96162f1094c690418f696ed94ebd60aa0f91afed"},
 {UINT32_C(653),UINT16_C(1),"hashState","abaa4db6d995c32230a80016b2ca74a53a0742443302f9e82f5aefc1777fe425"},
 {UINT32_C(654),UINT16_C(2),"hashState","b16659974f9aa8668917dad8ee20597be8ad32eca10696b3bdf159ea328e5d15"},
 {UINT32_C(655),UINT16_C(3),"hashState","351d5c0d31aeeaff5f00fd79ce58a1674246c9b29b62b0bab94f832e04c56456"},
 {UINT32_C(656),UINT16_C(4),"hashState","b9e8ca840b6f8fe8b64ff8e72c338ad8c8bb1a629f3c2cc256dc83325e5605a1"},
 {UINT32_C(657),UINT16_C(5),"hashState","7bc72226e4fe0de0f30a6fe523b09092306df7dacb79fa919afcc20ff1b5483d"},
 {UINT32_C(658),UINT16_C(6),"hashState","fb71c3cb0c187ecf236a8acf956128fa3ac03b6e563e90eaf3ace8a290db1006"},
 {UINT32_C(659),UINT16_C(7),"hashState","fb51bad5c0dde87ad8e737b3232f9cb51814b5ff30a52b16324afa22b4c1dffb"},
 {UINT32_C(666),UINT16_C(4),"cstringValue","dd3603434eed0885e755c7d42783e0213ac6aef0f782d7a92b7abee5e866d33c"},
 {UINT32_C(667),UINT16_C(5),"cstringValue","e678583725808c9c31a2fba449b5b54ee8e437aeac1f00fedbb230f8e72f7b38"},
 {UINT32_C(692),UINT16_C(8),"hashState","a88d11a708910a39f5f5b5930de47aeec84c806b07cec4feffc78000e0aa571b"},
 {UINT32_C(693),UINT16_C(9),"hashState","157010e41590d669f4d2390ce9585d5cebe52f19dc5017f2fe17c33f55032679"},
 {UINT32_C(717),UINT16_C(0),"astcProbe","6ca0a9c195bd4290989c24bdb536553427c7010bdc74cff8838ddb6eef43d6e3"},
 {UINT32_C(718),UINT16_C(1),"astcProbe","7a7e0673714e53c44de51e5d3e396c642d35c82f591875026205917a7cef6107"},
 {UINT32_C(735),UINT16_C(2),"enumValue","41ab559b13c9e89b16d5168617a8f59bffc6eb4b098acc9cc433c8c56341384c"},
 {UINT32_C(738),UINT16_C(3),"enumValue","c6f3f1d0a8359f816d6511cb70709bb4b82e8871fcde5edff197df8cf1cab80a"},
 {UINT32_C(741),UINT16_C(4),"enumValue","3f0545194ddc2a48c01a6454c74771f9fff4dc8066d9f37a06eb0bbdec3f3944"},
 {UINT32_C(843),UINT16_C(0),"arenaCString","fb1df32e8ccf631949896ec4e292d667af42c8a2791c442a77bf026e71bf218c"},
 {UINT32_C(847),UINT16_C(6),"cstringValue","a990c477b414b0e38a40e679f1ab2f925a36ebb9a2864bb99bac5e3348da00e6"},
 {UINT32_C(994),UINT16_C(7),"cstringValue","a9e90c77718d7c7885a547255848b4ddc1707ddd4f5d9aa9b19debc143ef32f9"},
 {UINT32_C(1010),UINT16_C(1),"namedScalar","44b1459bb90912917cd1eb5f13b1a157af9f695514e367910cc6cad8a5101394"},
 {UINT32_C(1011),UINT16_C(5),"enumValue","18d2907eb834fbf12aed0b25aed141090b5b9d82e2bfb5122e2d37d6f49a7144"},
 {UINT32_C(1012),UINT16_C(6),"enumValue","693934471fe4a687f70a0ebdc291baf2b6fd8c0d7acd29f44f0583ec38007815"},
 {UINT32_C(1024),UINT16_C(8),"cstringValue","9a81d19ee8281032a3a5e155a1b0ee743ebd7101d344270453b653c2b82b4dbe"},
 {UINT32_C(1025),UINT16_C(1),"arenaCString","74940ceff022885a96ad0847b02a8e9e034a54e4432b4a70ec803734a6214be9"},
 {UINT32_C(1029),UINT16_C(2),"arenaCString","024c6a1a6b515c2313d5869423c8890c98644f30b9c7b05dd766ba417e81d27e"},
 {UINT32_C(1030),UINT16_C(9),"cstringValue","863641983526ddc1db4494abb3e1219de0b5df43c58b43101781c7f6aa0cb994"},
 {UINT32_C(1031),UINT16_C(10),"cstringValue","8c04d20537f91bf6a46f37507ba2130de8261720557a75b0e6caecd7af0e54fc"},
 {UINT32_C(1035),UINT16_C(11),"cstringValue","5d5a8f4f511c531bd501fe1c12b591d506730e59691a2f8917242e883c0690f4"},
 {UINT32_C(1036),UINT16_C(2),"namedScalar","b9f7bebd1c1731ea54ed04580088c6643dd3497cf63739914970c47a7f8ce116"},
 {UINT32_C(1037),UINT16_C(3),"namedScalar","b069f79e9cf265c7a4fa4dc59373923c4b36f7ee224104d4c66a74617a976a4c"},
 {UINT32_C(1038),UINT16_C(4),"namedScalar","98acab0b847405a686f9bbd851cf47408123cb5e0598894ca09803ea4e475e67"},
 {UINT32_C(1039),UINT16_C(5),"namedScalar","29689f0ab4c1e2c7a3e5a76701e559d42bc4c41924edad322eb37aa254016c71"},
 {UINT32_C(1041),UINT16_C(6),"namedScalar","a7056e1f2da9b944e6ad462dd04fb6eb8e3c1b037f62b60ffc7f4d7bcbdc3ea3"},
 {UINT32_C(1045),UINT16_C(9),"scalar","def2766ddb9a434cce6c4c930423e0735baa606fae92bac6f15e75353d0bcc04"},
 {UINT32_C(1046),UINT16_C(10),"scalar","160bfc68af4eb63e2949f1d9de2b0d40c77ccb09fb61333319a62ef4b1ab9d04"},
 {UINT32_C(1047),UINT16_C(11),"scalar","74f89dd521470b108aa784dbbe9fcf193148754454c8e3f26031b1e625bae65f"},
 {UINT32_C(1074),UINT16_C(12),"scalar","306b5d36da5506b3da3ce0926d93f1bea4aa684b4d187e6bd95007a1b6f16f2a"},
 {UINT32_C(1075),UINT16_C(13),"scalar","468280aa68dcf0a72a2f8c309d00b9a90e593a41f696e55f8b35117ba297bd56"},
 {UINT32_C(1077),UINT16_C(3),"arenaCString","e53d569825102d7b2523e36b745eed0c8d5c1050253144379522abc914bd02e0"},
 {UINT32_C(1079),UINT16_C(14),"scalar","8c3b33d4b91a22fc3b82499174c335ea0a3d02fe3d932ef48373467fb1498a80"},
 {UINT32_C(1080),UINT16_C(15),"scalar","1e625e05fcef7d085881d2edb95366f356619e214f53cf950c6312562de31baa"},
 {UINT32_C(1082),UINT16_C(12),"cstringValue","14315dea8a4fb6c6ed0c24b92ce97b116471ab27ca156fe77b9a9274dc1f57ec"},
 {UINT32_C(1128),UINT16_C(16),"scalar","276bb7c8b3747c0e6088298bf7306d5910aea8a13398a0bdccd598d84f31ac9d"},
 {UINT32_C(1129),UINT16_C(17),"scalar","2588c48a58818dffe22caa632009ece9aae9c40dcfa280b50283f08c2e4da03e"},
 {UINT32_C(1130),UINT16_C(18),"scalar","a7d14df7a50159018a24f76accebf7e0ad15f91e3e64fe914fd7ea5141e2adef"},
 {UINT32_C(1131),UINT16_C(19),"scalar","314fdd87920300a1dc2f7e329848489a5525a84982fe3f9cbc73a8eb3ff349e9"},
 {UINT32_C(1132),UINT16_C(20),"scalar","4fdc16de909b791f7c2e207bee289b254e395f3062c2665a75e24fa6ea6635b8"},
 {UINT32_C(1133),UINT16_C(21),"scalar","16b7ac65af833594d20dbe6a076eb54dc600c7116a00b4b231f312f1aaf37e7f"},
 {UINT32_C(1134),UINT16_C(22),"scalar","d6ac4e48d9a44e4241d89933596aae4df49502730b589b458bc528cdc07a4fa2"},
 {UINT32_C(1135),UINT16_C(23),"scalar","d460d4a00500d5beb77d343bd895045a2f6bc6babf9826ef7f800e33cc477c12"},
 {UINT32_C(1136),UINT16_C(24),"scalar","2a0e153dfbc7def25bbdd82ac949c95f46df2ee8817490ae1518c7ea00605ecc"},
 {UINT32_C(1244),UINT16_C(25),"scalar","fe6eae7277a39dd18a430d7ccad1950a5d04d458846c0a9a8d407ea040d8c7fc"},
 {UINT32_C(1247),UINT16_C(7),"namedScalar","b7b7d15b402e9c0842919010b21081c6658fd6eb2788faedf58c5ddd992fe3ef"},
 {UINT32_C(1248),UINT16_C(8),"namedScalar","dadd86f92cebe3ac050d54c253f1504de3f61c58eefe08b0e21ec9b5d0ef3193"},
 {UINT32_C(1249),UINT16_C(9),"namedScalar","451dc827f7c74406011dbe764e8cb2ce263963cd61589731556a7b1ab8ceffc3"},
 {UINT32_C(1250),UINT16_C(10),"namedScalar","52278d1bda25e626a3d2ce2bb04116f42c5c17de16fa792a1de35e82c4733579"},
 {UINT32_C(1251),UINT16_C(11),"namedScalar","2e03c0c531d8ba688755d2ef1f2940773bc580cf3c63fbc9965e0bdf3e487f80"},
 {UINT32_C(1252),UINT16_C(12),"namedScalar","32f9895d70929f622afd05b62e98f97b9fd64a4eca5f7d5817225f548435a1a7"},
 {UINT32_C(1253),UINT16_C(13),"namedScalar","081ee8a00df5e6d8641361b6ebc9182127eb38999fe16330a57ec373b0a93a83"},
 {UINT32_C(1254),UINT16_C(14),"namedScalar","743a2b268d37f6efe1fbf1619b793e472f428035fcf03e7cf46c8fe7371e2faf"},
 {UINT32_C(1255),UINT16_C(15),"namedScalar","7460755f8d8c5c3ef63f9af2a822d26085bb653329ce5fa6c8d68e280a72d08f"},
 {UINT32_C(1256),UINT16_C(16),"namedScalar","f2239292c03a43847cbe74558d94feee42dbc8eebb33d663fe894d78fee622a2"},
 {UINT32_C(1257),UINT16_C(17),"namedScalar","3744bafc6b68d7808c735f1a9f1e1adc25d4bf59aa231b6ee47fd6ef4562916c"},
 {UINT32_C(1258),UINT16_C(18),"namedScalar","c1f8cc42ec9a57f4755977993aea6e5847d4a6223f282b81bc5c55212cd9b6d9"},
 {UINT32_C(1259),UINT16_C(19),"namedScalar","7abf94e0045fefeca949f37ef0e7a18f50d735e9b7bc436e9f9ed747c34d27ad"},
 {UINT32_C(1292),UINT16_C(4),"arenaCString","43894fc07be20d37f89b43d3f4ed0b0b19ffa9d93d87910d2e41227cbe8d8a2d"},
 {UINT32_C(1295),UINT16_C(13),"cstringValue","977c9558875f63c1b0257bc26b84ca358ea2a1319ee2557c083d9fb066700198"}
};
extern "C" uint32_t deherm_dmsdk_generated_adapter_exact_vector_count(void){return UINT32_C(94);}
extern "C" const DehermDmSdkAdapterExactVector* deherm_dmsdk_generated_adapter_exact_vectors(void){return kVectors;}
extern "C" int deherm_dmsdk_run_generated_adapter_exact_verification(void){
if(deherm_dmsdk_arena_cstring_count()!=UINT32_C(5))return 1;
if(deherm_dmsdk_arena_cstring_descriptors()[UINT16_C(0)].id!=UINT16_C(0))return 2;
if(strcmp(deherm_dmsdk_arena_cstring_descriptors()[UINT16_C(0)].declaration_id,"dmsdk:dmResource::GetCanonicalPath@upstream/defold/engine/resource/src/dmsdk/resource/resource.hpp:151:1970")!=0)return 3;
if(deherm_dmsdk_arena_cstring_descriptors()[UINT16_C(1)].id!=UINT16_C(1))return 4;
if(strcmp(deherm_dmsdk_arena_cstring_descriptors()[UINT16_C(1)].declaration_id,"dmsdk:dmStrError@upstream/defold/engine/dlib/src/dmsdk/dlib/dstrings.h:174:184")!=0)return 5;
if(deherm_dmsdk_arena_cstring_descriptors()[UINT16_C(2)].id!=UINT16_C(2))return 6;
if(strcmp(deherm_dmsdk_arena_cstring_descriptors()[UINT16_C(2)].declaration_id,"dmsdk:dmStrTrim@upstream/defold/engine/dlib/src/dmsdk/dlib/dstrings.h:137:182")!=0)return 7;
if(deherm_dmsdk_arena_cstring_descriptors()[UINT16_C(3)].id!=UINT16_C(3))return 8;
if(strcmp(deherm_dmsdk_arena_cstring_descriptors()[UINT16_C(3)].declaration_id,"dmsdk:dmURI::Encode@upstream/defold/engine/dlib/src/dmsdk/dlib/uri.h:96:655")!=0)return 9;
if(deherm_dmsdk_arena_cstring_descriptors()[UINT16_C(4)].id!=UINT16_C(4))return 10;
if(strcmp(deherm_dmsdk_arena_cstring_descriptors()[UINT16_C(4)].declaration_id,"dmsdk:ResourceGetCanonicalPath@upstream/defold/engine/resource/src/dmsdk/resource/resource.h:324:1907")!=0)return 11;
if(deherm_dmsdk_scalar_count()!=UINT32_C(26))return 12;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(0)].id!=UINT16_C(0))return 13;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(0)].declaration_id,"dmsdk:dmEndian::ByteSwap@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.hpp:36:194")!=0)return 14;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(1)].id!=UINT16_C(1))return 15;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(1)].declaration_id,"dmsdk:dmEndian::ByteSwap@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.hpp:46:195")!=0)return 16;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(2)].id!=UINT16_C(2))return 17;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(2)].declaration_id,"dmsdk:dmEndian::ByteSwap@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.hpp:56:196")!=0)return 18;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(3)].id!=UINT16_C(3))return 19;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(3)].declaration_id,"dmsdk:dmEndian::ToHost@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.hpp:104:200")!=0)return 20;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(4)].id!=UINT16_C(4))return 21;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(4)].declaration_id,"dmsdk:dmEndian::ToHost@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.hpp:128:202")!=0)return 22;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(5)].id!=UINT16_C(5))return 23;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(5)].declaration_id,"dmsdk:dmEndian::ToHost@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.hpp:80:198")!=0)return 24;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(6)].id!=UINT16_C(6))return 25;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(6)].declaration_id,"dmsdk:dmEndian::ToNetwork@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.hpp:116:201")!=0)return 26;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(7)].id!=UINT16_C(7))return 27;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(7)].declaration_id,"dmsdk:dmEndian::ToNetwork@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.hpp:68:197")!=0)return 28;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(8)].id!=UINT16_C(8))return 29;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(8)].declaration_id,"dmsdk:dmEndian::ToNetwork@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.hpp:92:199")!=0)return 30;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(9)].id!=UINT16_C(9))return 31;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(9)].declaration_id,"dmsdk:dmTime::GetMonotonicTime@upstream/defold/engine/dlib/src/dmsdk/dlib/time.h:56:615")!=0)return 32;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(10)].id!=UINT16_C(10))return 33;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(10)].declaration_id,"dmsdk:dmTime::GetTime@upstream/defold/engine/dlib/src/dmsdk/dlib/time.h:38:614")!=0)return 34;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(11)].id!=UINT16_C(11))return 35;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(11)].declaration_id,"dmsdk:dmTime::Sleep@upstream/defold/engine/dlib/src/dmsdk/dlib/time.h:64:616")!=0)return 36;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(12)].id!=UINT16_C(12))return 37;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(12)].declaration_id,"dmsdk:dmTrigLookup::Cos@upstream/defold/engine/dlib/src/dmsdk/dlib/trig_lookup.h:54:646")!=0)return 38;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(13)].id!=UINT16_C(13))return 39;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(13)].declaration_id,"dmsdk:dmTrigLookup::Sin@upstream/defold/engine/dlib/src/dmsdk/dlib/trig_lookup.h:76:647")!=0)return 40;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(14)].id!=UINT16_C(14))return 41;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(14)].declaration_id,"dmsdk:dmUtf8::IsBreaking@upstream/defold/engine/dlib/src/dmsdk/dlib/utf8.h:103:668")!=0)return 42;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(15)].id!=UINT16_C(15))return 43;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(15)].declaration_id,"dmsdk:dmUtf8::IsWhiteSpace@upstream/defold/engine/dlib/src/dmsdk/dlib/utf8.h:86:667")!=0)return 44;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(16)].id!=UINT16_C(16))return 45;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(16)].declaration_id,"dmsdk:EndianSwap16@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.h:65:185")!=0)return 46;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(17)].id!=UINT16_C(17))return 47;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(17)].declaration_id,"dmsdk:EndianSwap32@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.h:81:186")!=0)return 48;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(18)].id!=UINT16_C(18))return 49;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(18)].declaration_id,"dmsdk:EndianSwap64@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.h:100:187")!=0)return 50;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(19)].id!=UINT16_C(19))return 51;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(19)].declaration_id,"dmsdk:EndianToHost16@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.h:141:189")!=0)return 52;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(20)].id!=UINT16_C(20))return 53;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(20)].declaration_id,"dmsdk:EndianToHost32@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.h:169:191")!=0)return 54;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(21)].id!=UINT16_C(21))return 55;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(21)].declaration_id,"dmsdk:EndianToHost64@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.h:197:193")!=0)return 56;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(22)].id!=UINT16_C(22))return 57;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(22)].declaration_id,"dmsdk:EndianToNetwork16@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.h:125:188")!=0)return 58;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(23)].id!=UINT16_C(23))return 59;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(23)].declaration_id,"dmsdk:EndianToNetwork32@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.h:153:190")!=0)return 60;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(24)].id!=UINT16_C(24))return 61;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(24)].declaration_id,"dmsdk:EndianToNetwork64@upstream/defold/engine/dlib/src/dmsdk/dlib/endian.h:181:192")!=0)return 62;
if(deherm_dmsdk_scalar_descriptors()[UINT16_C(25)].id!=UINT16_C(25))return 63;
if(strcmp(deherm_dmsdk_scalar_descriptors()[UINT16_C(25)].declaration_id,"dmsdk:ProfileIsInitialized@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:340:531")!=0)return 64;
if(deherm_dmsdk_enum_count()!=UINT32_C(7))return 65;
if(deherm_dmsdk_enum_descriptors()[UINT16_C(0)].id!=UINT16_C(0))return 66;
if(strcmp(deherm_dmsdk_enum_descriptors()[UINT16_C(0)].declaration_id,"dmsdk:dmBuffer::GetSizeForValueType@upstream/defold/engine/dlib/src/dmsdk/dlib/buffer.h:363:99")!=0)return 67;
if(deherm_dmsdk_enum_descriptors()[UINT16_C(1)].id!=UINT16_C(1))return 68;
if(strcmp(deherm_dmsdk_enum_descriptors()[UINT16_C(1)].declaration_id,"dmsdk:dmGraphics::GetInstalledAdapterFamily@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1159:1398")!=0)return 69;
if(deherm_dmsdk_enum_descriptors()[UINT16_C(2)].id!=UINT16_C(2))return 70;
if(strcmp(deherm_dmsdk_enum_descriptors()[UINT16_C(2)].declaration_id,"dmsdk:dmLog::Setlevel@upstream/defold/engine/dlib/src/dmsdk/dlib/log.h:339:397")!=0)return 71;
if(deherm_dmsdk_enum_descriptors()[UINT16_C(3)].id!=UINT16_C(3))return 72;
if(strcmp(deherm_dmsdk_enum_descriptors()[UINT16_C(3)].declaration_id,"dmsdk:dmLogGetLevel@upstream/defold/engine/dlib/src/dmsdk/dlib/log.h:310:391")!=0)return 73;
if(deherm_dmsdk_enum_descriptors()[UINT16_C(4)].id!=UINT16_C(4))return 74;
if(strcmp(deherm_dmsdk_enum_descriptors()[UINT16_C(4)].declaration_id,"dmsdk:dmLogSetLevel@upstream/defold/engine/dlib/src/dmsdk/dlib/log.h:300:390")!=0)return 75;
if(deherm_dmsdk_enum_descriptors()[UINT16_C(5)].id!=UINT16_C(5))return 76;
if(strcmp(deherm_dmsdk_enum_descriptors()[UINT16_C(5)].declaration_id,"dmsdk:dmSound::SetGroupMute@upstream/defold/engine/sound/src/dmsdk/sound/sound.h:92:2138")!=0)return 77;
if(deherm_dmsdk_enum_descriptors()[UINT16_C(6)].id!=UINT16_C(6))return 78;
if(strcmp(deherm_dmsdk_enum_descriptors()[UINT16_C(6)].declaration_id,"dmsdk:dmSound::ToggleGroupMute@upstream/defold/engine/sound/src/dmsdk/sound/sound.h:101:2139")!=0)return 79;
if(deherm_dmsdk_fixed_digest_count()!=UINT32_C(4))return 80;
if(deherm_dmsdk_fixed_digest_descriptors()[UINT16_C(0)].id!=UINT16_C(0))return 81;
if(strcmp(deherm_dmsdk_fixed_digest_descriptors()[UINT16_C(0)].declaration_id,"dmsdk:dmCrypt::HashMd5@upstream/defold/engine/dlib/src/dmsdk/dlib/crypt.h:108:160")!=0)return 82;
if(deherm_dmsdk_fixed_digest_descriptors()[UINT16_C(1)].id!=UINT16_C(1))return 83;
if(strcmp(deherm_dmsdk_fixed_digest_descriptors()[UINT16_C(1)].declaration_id,"dmsdk:dmCrypt::HashSha1@upstream/defold/engine/dlib/src/dmsdk/dlib/crypt.h:84:157")!=0)return 84;
if(deherm_dmsdk_fixed_digest_descriptors()[UINT16_C(2)].id!=UINT16_C(2))return 85;
if(strcmp(deherm_dmsdk_fixed_digest_descriptors()[UINT16_C(2)].declaration_id,"dmsdk:dmCrypt::HashSha256@upstream/defold/engine/dlib/src/dmsdk/dlib/crypt.h:92:158")!=0)return 86;
if(deherm_dmsdk_fixed_digest_descriptors()[UINT16_C(3)].id!=UINT16_C(3))return 87;
if(strcmp(deherm_dmsdk_fixed_digest_descriptors()[UINT16_C(3)].declaration_id,"dmsdk:dmCrypt::HashSha512@upstream/defold/engine/dlib/src/dmsdk/dlib/crypt.h:100:159")!=0)return 88;
if(deherm_dmsdk_hash_span_count()!=UINT32_C(2))return 89;
if(deherm_dmsdk_hash_span_descriptors()[UINT16_C(0)].id!=UINT16_C(0))return 90;
if(strcmp(deherm_dmsdk_hash_span_descriptors()[UINT16_C(0)].declaration_id,"dmsdk:dmHashBuffer32@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:69:212")!=0)return 91;
if(deherm_dmsdk_hash_span_descriptors()[UINT16_C(1)].id!=UINT16_C(1))return 92;
if(strcmp(deherm_dmsdk_hash_span_descriptors()[UINT16_C(1)].declaration_id,"dmsdk:dmHashBuffer64@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:79:213")!=0)return 93;
if(deherm_dmsdk_hash_state_count()!=UINT32_C(10))return 94;
if(deherm_dmsdk_hash_state_descriptors()[UINT16_C(0)].id!=UINT16_C(0))return 95;
if(strcmp(deherm_dmsdk_hash_state_descriptors()[UINT16_C(0)].declaration_id,"dmsdk:dmHashClone32@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:214:233")!=0)return 96;
if(deherm_dmsdk_hash_state_descriptors()[UINT16_C(1)].id!=UINT16_C(1))return 97;
if(strcmp(deherm_dmsdk_hash_state_descriptors()[UINT16_C(1)].declaration_id,"dmsdk:dmHashClone64@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:256:238")!=0)return 98;
if(deherm_dmsdk_hash_state_descriptors()[UINT16_C(2)].id!=UINT16_C(2))return 99;
if(strcmp(deherm_dmsdk_hash_state_descriptors()[UINT16_C(2)].declaration_id,"dmsdk:dmHashFinal32@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:231:235")!=0)return 100;
if(deherm_dmsdk_hash_state_descriptors()[UINT16_C(3)].id!=UINT16_C(3))return 101;
if(strcmp(deherm_dmsdk_hash_state_descriptors()[UINT16_C(3)].declaration_id,"dmsdk:dmHashFinal64@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:273:240")!=0)return 102;
if(deherm_dmsdk_hash_state_descriptors()[UINT16_C(4)].id!=UINT16_C(4))return 103;
if(strcmp(deherm_dmsdk_hash_state_descriptors()[UINT16_C(4)].declaration_id,"dmsdk:dmHashInit32@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:204:232")!=0)return 104;
if(deherm_dmsdk_hash_state_descriptors()[UINT16_C(5)].id!=UINT16_C(5))return 105;
if(strcmp(deherm_dmsdk_hash_state_descriptors()[UINT16_C(5)].declaration_id,"dmsdk:dmHashInit64@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:247:237")!=0)return 106;
if(deherm_dmsdk_hash_state_descriptors()[UINT16_C(6)].id!=UINT16_C(6))return 107;
if(strcmp(deherm_dmsdk_hash_state_descriptors()[UINT16_C(6)].declaration_id,"dmsdk:dmHashRelease32@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:239:236")!=0)return 108;
if(deherm_dmsdk_hash_state_descriptors()[UINT16_C(7)].id!=UINT16_C(7))return 109;
if(strcmp(deherm_dmsdk_hash_state_descriptors()[UINT16_C(7)].declaration_id,"dmsdk:dmHashRelease64@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:281:241")!=0)return 110;
if(deherm_dmsdk_hash_state_descriptors()[UINT16_C(8)].id!=UINT16_C(8))return 111;
if(strcmp(deherm_dmsdk_hash_state_descriptors()[UINT16_C(8)].declaration_id,"dmsdk:dmHashUpdateBuffer32@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:223:234")!=0)return 112;
if(deherm_dmsdk_hash_state_descriptors()[UINT16_C(9)].id!=UINT16_C(9))return 113;
if(strcmp(deherm_dmsdk_hash_state_descriptors()[UINT16_C(9)].declaration_id,"dmsdk:dmHashUpdateBuffer64@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:265:239")!=0)return 114;
if(deherm_dmsdk_named_scalar_count()!=UINT32_C(20))return 115;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(0)].id!=UINT16_C(0))return 116;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(0)].declaration_id,"dmsdk:dmGameObject::CreateInstanceId@upstream/defold/engine/gameobject/src/dmsdk/gameobject/gameobject.h:598:1005")!=0)return 117;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(1)].id!=UINT16_C(1))return 118;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(1)].declaration_id,"dmsdk:dmSound::IsGroupMuted@upstream/defold/engine/sound/src/dmsdk/sound/sound.h:108:2140")!=0)return 119;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(2)].id!=UINT16_C(2))return 120;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(2)].declaration_id,"dmsdk:dmThread::AllocTls@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:119:608")!=0)return 121;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(3)].id!=UINT16_C(3))return 122;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(3)].declaration_id,"dmsdk:dmThread::Detach@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:112:607")!=0)return 123;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(4)].id!=UINT16_C(4))return 124;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(4)].declaration_id,"dmsdk:dmThread::FreeTls@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:126:609")!=0)return 125;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(5)].id!=UINT16_C(5))return 126;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(5)].declaration_id,"dmsdk:dmThread::GetCurrentThread@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:148:612")!=0)return 127;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(6)].id!=UINT16_C(6))return 128;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(6)].declaration_id,"dmsdk:dmThread::Join@upstream/defold/engine/dlib/src/dmsdk/dlib/thread.h:102:606")!=0)return 129;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(7)].id!=UINT16_C(7))return 130;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(7)].declaration_id,"dmsdk:ProfilePropertyAddF32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:480")!=0)return 131;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(8)].id!=UINT16_C(8))return 132;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(8)].declaration_id,"dmsdk:ProfilePropertyAddF64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:492")!=0)return 133;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(9)].id!=UINT16_C(9))return 134;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(9)].declaration_id,"dmsdk:ProfilePropertyAddS32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:472")!=0)return 135;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(10)].id!=UINT16_C(10))return 136;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(10)].declaration_id,"dmsdk:ProfilePropertyAddS64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:484")!=0)return 137;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(11)].id!=UINT16_C(11))return 138;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(11)].declaration_id,"dmsdk:ProfilePropertyAddU32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:476")!=0)return 139;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(12)].id!=UINT16_C(12))return 140;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(12)].declaration_id,"dmsdk:ProfilePropertyAddU64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:488")!=0)return 141;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(13)].id!=UINT16_C(13))return 142;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(13)].declaration_id,"dmsdk:ProfilePropertySetBool@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:467")!=0)return 143;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(14)].id!=UINT16_C(14))return 144;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(14)].declaration_id,"dmsdk:ProfilePropertySetF32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:479")!=0)return 145;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(15)].id!=UINT16_C(15))return 146;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(15)].declaration_id,"dmsdk:ProfilePropertySetF64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:491")!=0)return 147;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(16)].id!=UINT16_C(16))return 148;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(16)].declaration_id,"dmsdk:ProfilePropertySetS32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:471")!=0)return 149;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(17)].id!=UINT16_C(17))return 150;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(17)].declaration_id,"dmsdk:ProfilePropertySetS64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:483")!=0)return 151;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(18)].id!=UINT16_C(18))return 152;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(18)].declaration_id,"dmsdk:ProfilePropertySetU32@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:475")!=0)return 153;
if(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(19)].id!=UINT16_C(19))return 154;
if(strcmp(deherm_dmsdk_named_scalar_descriptors()[UINT16_C(19)].declaration_id,"dmsdk:ProfilePropertySetU64@upstream/defold/engine/dlib/src/dmsdk/dlib/profile.h:0:487")!=0)return 155;
if(deherm_dmsdk_base64_span_count()!=UINT32_C(2))return 156;
if(deherm_dmsdk_base64_span_descriptors()[UINT16_C(0)].id!=UINT16_C(0))return 157;
if(strcmp(deherm_dmsdk_base64_span_descriptors()[UINT16_C(0)].declaration_id,"dmsdk:dmCrypt::Base64Decode@upstream/defold/engine/dlib/src/dmsdk/dlib/crypt.h:133:162")!=0)return 158;
if(deherm_dmsdk_base64_span_descriptors()[UINT16_C(1)].id!=UINT16_C(1))return 159;
if(strcmp(deherm_dmsdk_base64_span_descriptors()[UINT16_C(1)].declaration_id,"dmsdk:dmCrypt::Base64Encode@upstream/defold/engine/dlib/src/dmsdk/dlib/crypt.h:120:161")!=0)return 160;
if(deherm_dmsdk_astc_probe_count()!=UINT32_C(2))return 161;
if(deherm_dmsdk_astc_probe_descriptors()[UINT16_C(0)].id!=UINT16_C(0))return 162;
if(strcmp(deherm_dmsdk_astc_probe_descriptors()[UINT16_C(0)].declaration_id,"dmsdk:dmImage::GetAstcBlockSize@upstream/defold/engine/dlib/src/dmsdk/dlib/image.h:133:349")!=0)return 163;
if(deherm_dmsdk_astc_probe_descriptors()[UINT16_C(1)].id!=UINT16_C(1))return 164;
if(strcmp(deherm_dmsdk_astc_probe_descriptors()[UINT16_C(1)].declaration_id,"dmsdk:dmImage::GetAstcDimensions@upstream/defold/engine/dlib/src/dmsdk/dlib/image.h:145:350")!=0)return 165;
if(deherm_dmsdk_cstring_value_count()!=UINT32_C(14))return 166;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(0)].source_id,"dmsdk:dmBuffer::GetResultString@upstream/defold/engine/dlib/src/dmsdk/dlib/buffer.h:373:100")!=0)return 167;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(1)].source_id,"dmsdk:dmBuffer::GetValueTypeString@upstream/defold/engine/dlib/src/dmsdk/dlib/buffer.h:383:101")!=0)return 168;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(2)].source_id,"dmsdk:dmGraphics::GetTextureFormatLiteral@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1388:1420")!=0)return 169;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(3)].source_id,"dmsdk:dmGraphics::GetTextureTypeLiteral@upstream/defold/engine/graphics/src/dmsdk/graphics/graphics.h:1380:1419")!=0)return 170;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(4)].source_id,"dmsdk:dmHashString32@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:88:214")!=0)return 171;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(5)].source_id,"dmsdk:dmHashString64@upstream/defold/engine/dlib/src/dmsdk/dlib/hash.h:97:215")!=0)return 172;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(6)].source_id,"dmsdk:dmResource::GetExtFromPath@upstream/defold/engine/resource/src/dmsdk/resource/resource.hpp:141:1969")!=0)return 173;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(7)].source_id,"dmsdk:dmSocket::ResultToString@upstream/defold/engine/dlib/src/dmsdk/dlib/socket.h:388:568")!=0)return 174;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(8)].source_id,"dmsdk:dmStrCaseCmp@upstream/defold/engine/dlib/src/dmsdk/dlib/dstrings.h:155:183")!=0)return 175;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(9)].source_id,"dmsdk:dmSys::Exists@upstream/defold/engine/dlib/src/dmsdk/dlib/sys.h:117:595")!=0)return 176;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(10)].source_id,"dmsdk:dmSys::Rename@upstream/defold/engine/dlib/src/dmsdk/dlib/sys.h:135:597")!=0)return 177;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(11)].source_id,"dmsdk:dmSys::Unlink@upstream/defold/engine/dlib/src/dmsdk/dlib/sys.h:125:596")!=0)return 178;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(12)].source_id,"dmsdk:dmUtf8::StrLen@upstream/defold/engine/dlib/src/dmsdk/dlib/utf8.h:41:657")!=0)return 179;
if(strcmp(deherm_dmsdk_cstring_value_descriptors()[UINT16_C(13)].source_id,"dmsdk:ResourceGetExtFromPath@upstream/defold/engine/resource/src/dmsdk/resource/resource.h:314:1906")!=0)return 180;
if(deherm_dmsdk_xtea_span_count()!=UINT32_C(2))return 181;
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{nullptr,UINT32_C(0)}};uint64_t scalars[2]={UINT64_C(0)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(0),&scratch,strings,UINT32_C(0),scalars,UINT32_C(1),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 182;if(g_calls[7][0]!=UINT32_C(1)||g_failures[7][0]!=UINT32_C(0))return 182;if(!present||required!=UINT32_C(8)||strcmp(reinterpret_cast<const char*>(output),"result_0")!=0)return 182;}
{uint64_t arguments[2]={UINT64_C(0)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_enum_dispatch(UINT16_C(0),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_ENUM_OK)return 183;if(g_calls[1][0]!=UINT32_C(1)||g_failures[1][0]!=UINT32_C(0))return 183;if(result!=UINT64_C(20736))return 183;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{nullptr,UINT32_C(0)}};uint64_t scalars[2]={UINT64_C(1)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(1),&scratch,strings,UINT32_C(0),scalars,UINT32_C(1),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 184;if(g_calls[7][1]!=UINT32_C(1)||g_failures[7][1]!=UINT32_C(0))return 184;if(!present||required!=UINT32_C(8)||strcmp(reinterpret_cast<const char*>(output),"result_1")!=0)return 184;}
{uint8_t input[5]={'Q','Q','=','='};uint8_t output[32]={};uint32_t written=0;if(deherm_dmsdk_base64_span_dispatch(UINT16_C(0),input,UINT32_C(4),output,UINT32_C(32),&written)!=DEHERM_DMSDK_BASE64_SPAN_OK)return 185;if(g_calls[4][0]!=UINT32_C(1)||g_failures[4][0]!=UINT32_C(0))return 185;if(written!=UINT32_C(2)||output[0]!=UINT8_C(129)||output[1]!=UINT8_C(145))return 185;}
{uint8_t input[5]={66,0x22,0x33,0x44,0x55};uint8_t output[32]={};uint32_t written=0;if(deherm_dmsdk_base64_span_dispatch(UINT16_C(1),input,UINT32_C(5),output,UINT32_C(32),&written)!=DEHERM_DMSDK_BASE64_SPAN_OK)return 186;if(g_calls[4][1]!=UINT32_C(1)||g_failures[4][1]!=UINT32_C(0))return 186;if(written!=UINT32_C(2)||output[0]!=UINT8_C(130)||output[1]!=UINT8_C(146))return 186;}
{uint8_t data[16]={UINT8_C(65)};uint8_t key[8]={UINT8_C(97)};if(deherm_dmsdk_xtea_span_dispatch(UINT16_C(0),data,UINT32_C(9),key,UINT32_C(3))!=DEHERM_DMSDK_XTEA_SPAN_OK)return 187;if(g_calls[5][0]!=UINT32_C(1)||g_failures[5][0]!=UINT32_C(0))return 187;if(data[0]!=UINT8_C(161))return 187;}
{uint8_t data[16]={UINT8_C(66)};uint8_t key[8]={UINT8_C(98)};if(deherm_dmsdk_xtea_span_dispatch(UINT16_C(1),data,UINT32_C(10),key,UINT32_C(4))!=DEHERM_DMSDK_XTEA_SPAN_OK)return 188;if(g_calls[5][1]!=UINT32_C(1)||g_failures[5][1]!=UINT32_C(0))return 188;if(data[0]!=UINT8_C(162))return 188;}
{uint8_t input[16]={UINT8_C(32)};uint8_t output[64]={};uint32_t written=0;if(deherm_dmsdk_fixed_digest_dispatch(UINT16_C(0),input,UINT32_C(5),output,UINT32_C(64),&written)!=DEHERM_DMSDK_FIXED_DIGEST_OK)return 189;if(g_calls[2][0]!=UINT32_C(1)||g_failures[2][0]!=UINT32_C(0))return 189;if(written!=UINT32_C(16))return 189;for(uint32_t i=0;i<written;++i)if(output[i]!=static_cast<uint8_t>(UINT8_C(112)+i))return 189;}
{uint8_t input[16]={UINT8_C(33)};uint8_t output[64]={};uint32_t written=0;if(deherm_dmsdk_fixed_digest_dispatch(UINT16_C(1),input,UINT32_C(6),output,UINT32_C(64),&written)!=DEHERM_DMSDK_FIXED_DIGEST_OK)return 190;if(g_calls[2][1]!=UINT32_C(1)||g_failures[2][1]!=UINT32_C(0))return 190;if(written!=UINT32_C(20))return 190;for(uint32_t i=0;i<written;++i)if(output[i]!=static_cast<uint8_t>(UINT8_C(113)+i))return 190;}
{uint8_t input[16]={UINT8_C(34)};uint8_t output[64]={};uint32_t written=0;if(deherm_dmsdk_fixed_digest_dispatch(UINT16_C(2),input,UINT32_C(7),output,UINT32_C(64),&written)!=DEHERM_DMSDK_FIXED_DIGEST_OK)return 191;if(g_calls[2][2]!=UINT32_C(1)||g_failures[2][2]!=UINT32_C(0))return 191;if(written!=UINT32_C(32))return 191;for(uint32_t i=0;i<written;++i)if(output[i]!=static_cast<uint8_t>(UINT8_C(114)+i))return 191;}
{uint8_t input[16]={UINT8_C(35)};uint8_t output[64]={};uint32_t written=0;if(deherm_dmsdk_fixed_digest_dispatch(UINT16_C(3),input,UINT32_C(8),output,UINT32_C(64),&written)!=DEHERM_DMSDK_FIXED_DIGEST_OK)return 192;if(g_calls[2][3]!=UINT32_C(1)||g_failures[2][3]!=UINT32_C(0))return 192;if(written!=UINT32_C(64))return 192;for(uint32_t i=0;i<written;++i)if(output[i]!=static_cast<uint8_t>(UINT8_C(115)+i))return 192;}
{uint64_t arguments[2]={UINT64_C(4352)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(0),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 193;if(g_calls[0][0]!=UINT32_C(1)||g_failures[0][0]!=UINT32_C(0))return 193;if(result!=UINT64_C(20736))return 193;}
{uint64_t arguments[2]={UINT64_C(4369)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(1),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 194;if(g_calls[0][1]!=UINT32_C(1)||g_failures[0][1]!=UINT32_C(0))return 194;if(result!=UINT64_C(20753))return 194;}
{uint64_t arguments[2]={UINT64_C(4294971682)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(2),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 195;if(g_calls[0][2]!=UINT32_C(1)||g_failures[0][2]!=UINT32_C(0))return 195;if(result!=UINT64_C(4294988066))return 195;}
{uint64_t arguments[2]={UINT64_C(4403)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(3),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 196;if(g_calls[0][3]!=UINT32_C(1)||g_failures[0][3]!=UINT32_C(0))return 196;if(result!=UINT64_C(20787))return 196;}
{uint64_t arguments[2]={UINT64_C(4294971716)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(4),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 197;if(g_calls[0][4]!=UINT32_C(1)||g_failures[0][4]!=UINT32_C(0))return 197;if(result!=UINT64_C(4294988100))return 197;}
{uint64_t arguments[2]={UINT64_C(4437)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(5),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 198;if(g_calls[0][5]!=UINT32_C(1)||g_failures[0][5]!=UINT32_C(0))return 198;if(result!=UINT64_C(20821))return 198;}
{uint64_t arguments[2]={UINT64_C(4294971750)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(6),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 199;if(g_calls[0][6]!=UINT32_C(1)||g_failures[0][6]!=UINT32_C(0))return 199;if(result!=UINT64_C(4294988134))return 199;}
{uint64_t arguments[2]={UINT64_C(4471)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(7),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 200;if(g_calls[0][7]!=UINT32_C(1)||g_failures[0][7]!=UINT32_C(0))return 200;if(result!=UINT64_C(20855))return 200;}
{uint64_t arguments[2]={UINT64_C(4488)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(8),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 201;if(g_calls[0][8]!=UINT32_C(1)||g_failures[0][8]!=UINT32_C(0))return 201;if(result!=UINT64_C(20872))return 201;}
{uint64_t arguments[2]={UINT64_C(0)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(0),arguments,UINT32_C(0),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 202;if(g_calls[10][0]!=UINT32_C(1)||g_failures[10][0]!=UINT32_C(0))return 202;if(result!=UINT64_C(4294988032))return 202;}
{uint64_t arguments[2]={UINT64_C(0)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_enum_dispatch(UINT16_C(1),arguments,UINT32_C(0),&result)!=DEHERM_DMSDK_ENUM_OK)return 203;if(g_calls[1][1]!=UINT32_C(1)||g_failures[1][1]!=UINT32_C(0))return 203;if(result!=UINT64_C(2))return 203;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{nullptr,UINT32_C(0)}};uint64_t scalars[2]={UINT64_C(2)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(2),&scratch,strings,UINT32_C(0),scalars,UINT32_C(1),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 204;if(g_calls[7][2]!=UINT32_C(1)||g_failures[7][2]!=UINT32_C(0))return 204;if(!present||required!=UINT32_C(8)||strcmp(reinterpret_cast<const char*>(output),"result_2")!=0)return 204;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{nullptr,UINT32_C(0)}};uint64_t scalars[2]={UINT64_C(3)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(3),&scratch,strings,UINT32_C(0),scalars,UINT32_C(1),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 205;if(g_calls[7][3]!=UINT32_C(1)||g_failures[7][3]!=UINT32_C(0))return 205;if(!present||required!=UINT32_C(8)||strcmp(reinterpret_cast<const char*>(output),"result_3")!=0)return 205;}
{uint8_t input[16]={UINT8_C(48)};uint64_t output=0;if(deherm_dmsdk_hash_span_dispatch(UINT16_C(0),input,UINT32_C(7),&output)!=DEHERM_DMSDK_HASH_SPAN_OK)return 206;if(g_calls[3][0]!=UINT32_C(1)||g_failures[3][0]!=UINT32_C(0))return 206;if(output!=UINT64_C(1694498816))return 206;}
{uint8_t input[16]={UINT8_C(49)};uint64_t output=0;if(deherm_dmsdk_hash_span_dispatch(UINT16_C(1),input,UINT32_C(8),&output)!=DEHERM_DMSDK_HASH_SPAN_OK)return 207;if(g_calls[3][1]!=UINT32_C(1)||g_failures[3][1]!=UINT32_C(0))return 207;if(output!=UINT64_C(7277816997830722000))return 207;}
{uint64_t source=0,value=0,result=0;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_INIT_32,0,nullptr,0,0,&source)!=DEHERM_DMSDK_HASH_STATE_OK)return 208;const uint32_t before=g_calls[9][0];if(deherm_dmsdk_hash_state_dispatch(UINT16_C(0),source,nullptr,0,1,&value)!=DEHERM_DMSDK_HASH_STATE_OK||value==0||value==source)return 208;if(g_calls[9][0]!=before+UINT32_C(1)||g_failures[9][0]!=UINT32_C(0))return 208;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_FINAL_32,value,nullptr,0,0,&result)!=DEHERM_DMSDK_HASH_STATE_OK||result!=UINT64_C(10))return 208;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_RELEASE_32,source,nullptr,0,0,&result)!=DEHERM_DMSDK_HASH_STATE_OK)return 208;}
{uint64_t source=0,value=0,result=0;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_INIT_64,0,nullptr,0,0,&source)!=DEHERM_DMSDK_HASH_STATE_OK)return 209;const uint32_t before=g_calls[9][1];if(deherm_dmsdk_hash_state_dispatch(UINT16_C(1),source,nullptr,0,1,&value)!=DEHERM_DMSDK_HASH_STATE_OK||value==0||value==source)return 209;if(g_calls[9][1]!=before+UINT32_C(1)||g_failures[9][1]!=UINT32_C(0))return 209;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_FINAL_64,value,nullptr,0,0,&result)!=DEHERM_DMSDK_HASH_STATE_OK||result!=UINT64_C(15))return 209;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_RELEASE_64,source,nullptr,0,0,&result)!=DEHERM_DMSDK_HASH_STATE_OK)return 209;}
{uint64_t state=0,value=0;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_INIT_32,0,nullptr,0,0,&state)!=DEHERM_DMSDK_HASH_STATE_OK)return 210;const uint32_t before=g_calls[9][2];if(deherm_dmsdk_hash_state_dispatch(UINT16_C(2),state,nullptr,0,0,&value)!=DEHERM_DMSDK_HASH_STATE_OK||value!=UINT64_C(3))return 210;if(g_calls[9][2]!=before+UINT32_C(1)||g_failures[9][2]!=UINT32_C(0))return 210;}
{uint64_t state=0,value=0;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_INIT_64,0,nullptr,0,0,&state)!=DEHERM_DMSDK_HASH_STATE_OK)return 211;const uint32_t before=g_calls[9][3];if(deherm_dmsdk_hash_state_dispatch(UINT16_C(3),state,nullptr,0,0,&value)!=DEHERM_DMSDK_HASH_STATE_OK||value!=UINT64_C(6))return 211;if(g_calls[9][3]!=before+UINT32_C(1)||g_failures[9][3]!=UINT32_C(0))return 211;}
{const uint32_t before=g_calls[9][4];uint64_t state=0,value=0;if(deherm_dmsdk_hash_state_dispatch(UINT16_C(4),0,nullptr,0,1,&state)!=DEHERM_DMSDK_HASH_STATE_OK||state==0)return 212;if(g_calls[9][4]!=before+UINT32_C(1)||g_failures[9][4]!=UINT32_C(0))return 212;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_FINAL_32,state,nullptr,0,0,&value)!=DEHERM_DMSDK_HASH_STATE_OK||value!=UINT64_C(32))return 212;}
{const uint32_t before=g_calls[9][5];uint64_t state=0,value=0;if(deherm_dmsdk_hash_state_dispatch(UINT16_C(5),0,nullptr,0,1,&state)!=DEHERM_DMSDK_HASH_STATE_OK||state==0)return 213;if(g_calls[9][5]!=before+UINT32_C(1)||g_failures[9][5]!=UINT32_C(0))return 213;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_FINAL_64,state,nullptr,0,0,&value)!=DEHERM_DMSDK_HASH_STATE_OK||value!=UINT64_C(64))return 213;}
{uint64_t state=0,value=9;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_INIT_32,0,nullptr,0,0,&state)!=DEHERM_DMSDK_HASH_STATE_OK)return 214;const uint32_t before=g_calls[9][6];if(deherm_dmsdk_hash_state_dispatch(UINT16_C(6),state,nullptr,0,0,&value)!=DEHERM_DMSDK_HASH_STATE_OK||value!=0)return 214;if(g_calls[9][6]!=before+UINT32_C(1)||g_failures[9][6]!=UINT32_C(0))return 214;}
{uint64_t state=0,value=9;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_INIT_64,0,nullptr,0,0,&state)!=DEHERM_DMSDK_HASH_STATE_OK)return 215;const uint32_t before=g_calls[9][7];if(deherm_dmsdk_hash_state_dispatch(UINT16_C(7),state,nullptr,0,0,&value)!=DEHERM_DMSDK_HASH_STATE_OK||value!=0)return 215;if(g_calls[9][7]!=before+UINT32_C(1)||g_failures[9][7]!=UINT32_C(0))return 215;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{reinterpret_cast<const uint8_t*>("exact_4_0"),UINT32_C(9)}};uint64_t scalars[2]={UINT64_C(0)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(4),&scratch,strings,UINT32_C(1),scalars,UINT32_C(0),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 216;if(g_calls[7][4]!=UINT32_C(1)||g_failures[7][4]!=UINT32_C(0))return 216;if(result!=UINT64_C(20804))return 216;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{reinterpret_cast<const uint8_t*>("exact_5_0"),UINT32_C(9)}};uint64_t scalars[2]={UINT64_C(0)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(5),&scratch,strings,UINT32_C(1),scalars,UINT32_C(0),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 217;if(g_calls[7][5]!=UINT32_C(1)||g_failures[7][5]!=UINT32_C(0))return 217;if(result!=UINT64_C(4294988117))return 217;}
{uint64_t state=0,value=9,result=0;uint8_t input[4]={1,2,3,4};if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_INIT_32,0,nullptr,0,0,&state)!=DEHERM_DMSDK_HASH_STATE_OK)return 218;const uint32_t before=g_calls[9][8];if(deherm_dmsdk_hash_state_dispatch(UINT16_C(8),state,input,4,0,&value)!=DEHERM_DMSDK_HASH_STATE_OK||value!=0)return 218;if(g_calls[9][8]!=before+UINT32_C(1)||g_failures[9][8]!=UINT32_C(0))return 218;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_FINAL_32,state,nullptr,0,0,&result)!=DEHERM_DMSDK_HASH_STATE_OK||result!=UINT64_C(13))return 218;}
{uint64_t state=0,value=9,result=0;uint8_t input[4]={1,2,3,4};if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_INIT_64,0,nullptr,0,0,&state)!=DEHERM_DMSDK_HASH_STATE_OK)return 219;const uint32_t before=g_calls[9][9];if(deherm_dmsdk_hash_state_dispatch(UINT16_C(9),state,input,4,0,&value)!=DEHERM_DMSDK_HASH_STATE_OK||value!=0)return 219;if(g_calls[9][9]!=before+UINT32_C(1)||g_failures[9][9]!=UINT32_C(0))return 219;if(deherm_dmsdk_hash_state_dispatch(DEHERM_DMSDK_HASH_STATE_FINAL_64,state,nullptr,0,0,&result)!=DEHERM_DMSDK_HASH_STATE_OK||result!=UINT64_C(16))return 219;}
{uint8_t input[17]={UINT8_C(81)};DehermDmSdkAstcProbeResult output{};if(deherm_dmsdk_astc_probe_dispatch(UINT16_C(0),input,UINT32_C(16),&output)!=DEHERM_DMSDK_ASTC_PROBE_OK)return 220;if(g_calls[6][0]!=UINT32_C(1)||g_failures[6][0]!=UINT32_C(0))return 220;if(output.width!=UINT32_C(101)||output.height!=UINT32_C(201)||output.depth!=UINT32_C(301))return 220;}
{uint8_t input[17]={UINT8_C(82)};DehermDmSdkAstcProbeResult output{};if(deherm_dmsdk_astc_probe_dispatch(UINT16_C(1),input,UINT32_C(17),&output)!=DEHERM_DMSDK_ASTC_PROBE_OK)return 221;if(g_calls[6][1]!=UINT32_C(1)||g_failures[6][1]!=UINT32_C(0))return 221;if(output.width!=UINT32_C(102)||output.height!=UINT32_C(202)||output.depth!=UINT32_C(302))return 221;}
{uint64_t arguments[2]={UINT64_C(2)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_enum_dispatch(UINT16_C(2),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_ENUM_OK)return 222;if(g_calls[1][2]!=UINT32_C(1)||g_failures[1][2]!=UINT32_C(0))return 222;if(result!=UINT64_C(0))return 222;}
{uint64_t arguments[2]={UINT64_C(0)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_enum_dispatch(UINT16_C(3),arguments,UINT32_C(0),&result)!=DEHERM_DMSDK_ENUM_OK)return 223;if(g_calls[1][3]!=UINT32_C(1)||g_failures[1][3]!=UINT32_C(0))return 223;if(result!=UINT64_C(4))return 223;}
{uint64_t arguments[2]={UINT64_C(4)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_enum_dispatch(UINT16_C(4),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_ENUM_OK)return 224;if(g_calls[1][4]!=UINT32_C(1)||g_failures[1][4]!=UINT32_C(0))return 224;if(result!=UINT64_C(0))return 224;}
{const uint8_t* input=reinterpret_cast<const uint8_t*>("arena_0");uint8_t output[64]={};DehermDmSdkArenaCStringResult result{};if(deherm_dmsdk_arena_cstring_dispatch(UINT16_C(0),input,UINT32_C(7),UINT64_C(0),reinterpret_cast<char*>(output),UINT32_C(64),&result)!=DEHERM_DMSDK_ARENA_CSTRING_OK)return 225;if(g_calls[8][0]!=UINT32_C(1)||g_failures[8][0]!=UINT32_C(0))return 225;if(strcmp(reinterpret_cast<const char*>(output),"result_0")!=0||result.output_length!=UINT32_C(8)||result.required_length!=UINT32_C(500)||result.native_result!=UINT64_C(500))return 225;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{reinterpret_cast<const uint8_t*>("exact_6_0"),UINT32_C(9)}};uint64_t scalars[2]={UINT64_C(0)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(6),&scratch,strings,UINT32_C(1),scalars,UINT32_C(0),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 226;if(g_calls[7][6]!=UINT32_C(1)||g_failures[7][6]!=UINT32_C(0))return 226;if(!present||required!=UINT32_C(8)||strcmp(reinterpret_cast<const char*>(output),"result_6")!=0)return 226;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{nullptr,UINT32_C(0)}};uint64_t scalars[2]={static_cast<uint64_t>(INT64_C(-7))};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(7),&scratch,strings,UINT32_C(0),scalars,UINT32_C(1),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 227;if(g_calls[7][7]!=UINT32_C(1)||g_failures[7][7]!=UINT32_C(0))return 227;if(!present||required!=UINT32_C(8)||strcmp(reinterpret_cast<const char*>(output),"result_7")!=0)return 227;}
{uint64_t arguments[2]={UINT64_C(4294971665)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(1),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 228;if(g_calls[10][1]!=UINT32_C(1)||g_failures[10][1]!=UINT32_C(0))return 228;if(result!=UINT64_C(1))return 228;}
{uint64_t arguments[2]={UINT64_C(4294971733),UINT64_C(1)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_enum_dispatch(UINT16_C(5),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_ENUM_OK)return 229;if(g_calls[1][5]!=UINT32_C(1)||g_failures[1][5]!=UINT32_C(0))return 229;if(result!=static_cast<uint64_t>(INT64_C(-5)))return 229;}
{uint64_t arguments[2]={UINT64_C(4294971750)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_enum_dispatch(UINT16_C(6),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_ENUM_OK)return 230;if(g_calls[1][6]!=UINT32_C(1)||g_failures[1][6]!=UINT32_C(0))return 230;if(result!=static_cast<uint64_t>(INT64_C(-6)))return 230;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{reinterpret_cast<const uint8_t*>("exact_8_0"),UINT32_C(9)},{reinterpret_cast<const uint8_t*>("exact_8_1"),UINT32_C(9)}};uint64_t scalars[2]={UINT64_C(0)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(8),&scratch,strings,UINT32_C(2),scalars,UINT32_C(0),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 231;if(g_calls[7][8]!=UINT32_C(1)||g_failures[7][8]!=UINT32_C(0))return 231;if(result!=UINT64_C(20872))return 231;}
{const uint8_t* input=nullptr;uint8_t output[64]={};DehermDmSdkArenaCStringResult result{};if(deherm_dmsdk_arena_cstring_dispatch(UINT16_C(1),input,UINT32_C(0),UINT64_C(101),reinterpret_cast<char*>(output),UINT32_C(64),&result)!=DEHERM_DMSDK_ARENA_CSTRING_OK)return 232;if(g_calls[8][1]!=UINT32_C(1)||g_failures[8][1]!=UINT32_C(0))return 232;if(strcmp(reinterpret_cast<const char*>(output),"result_1")!=0||result.output_length!=UINT32_C(8)||result.required_length!=UINT32_C(0)||result.native_result!=UINT64_C(0))return 232;}
{const uint8_t* input=reinterpret_cast<const uint8_t*>("arena_2");uint8_t output[64]={};DehermDmSdkArenaCStringResult result{};if(deherm_dmsdk_arena_cstring_dispatch(UINT16_C(2),input,UINT32_C(7),UINT64_C(0),reinterpret_cast<char*>(output),UINT32_C(64),&result)!=DEHERM_DMSDK_ARENA_CSTRING_OK)return 233;if(g_calls[8][2]!=UINT32_C(1)||g_failures[8][2]!=UINT32_C(0))return 233;if(strcmp(reinterpret_cast<const char*>(output),"result_2")!=0||result.output_length!=UINT32_C(8)||result.required_length!=UINT32_C(502)||result.native_result!=UINT64_C(502))return 233;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{reinterpret_cast<const uint8_t*>("exact_9_0"),UINT32_C(9)}};uint64_t scalars[2]={UINT64_C(0)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(9),&scratch,strings,UINT32_C(1),scalars,UINT32_C(0),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 234;if(g_calls[7][9]!=UINT32_C(1)||g_failures[7][9]!=UINT32_C(0))return 234;if(result!=UINT64_C(1))return 234;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{reinterpret_cast<const uint8_t*>("exact_10_0"),UINT32_C(10)},{reinterpret_cast<const uint8_t*>("exact_10_1"),UINT32_C(10)}};uint64_t scalars[2]={UINT64_C(0)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(10),&scratch,strings,UINT32_C(2),scalars,UINT32_C(0),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 235;if(g_calls[7][10]!=UINT32_C(1)||g_failures[7][10]!=UINT32_C(0))return 235;if(result!=static_cast<uint64_t>(INT64_C(-11)))return 235;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{reinterpret_cast<const uint8_t*>("exact_11_0"),UINT32_C(10)}};uint64_t scalars[2]={UINT64_C(0)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(11),&scratch,strings,UINT32_C(1),scalars,UINT32_C(0),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 236;if(g_calls[7][11]!=UINT32_C(1)||g_failures[7][11]!=UINT32_C(0))return 236;if(result!=static_cast<uint64_t>(INT64_C(-12)))return 236;}
{uint64_t arguments[2]={UINT64_C(0)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(2),arguments,UINT32_C(0),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 237;if(g_calls[10][2]!=UINT32_C(1)||g_failures[10][2]!=UINT32_C(0))return 237;if(result!=UINT64_C(4294988066))return 237;}
{uint64_t arguments[2]={UINT64_C(4294971699)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(3),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 238;if(g_calls[10][3]!=UINT32_C(1)||g_failures[10][3]!=UINT32_C(0))return 238;if(result!=UINT64_C(0))return 238;}
{uint64_t arguments[2]={UINT64_C(4294971716)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(4),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 239;if(g_calls[10][4]!=UINT32_C(1)||g_failures[10][4]!=UINT32_C(0))return 239;if(result!=UINT64_C(0))return 239;}
{uint64_t arguments[2]={UINT64_C(0)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(5),arguments,UINT32_C(0),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 240;if(g_calls[10][5]!=UINT32_C(1)||g_failures[10][5]!=UINT32_C(0))return 240;if(result!=UINT64_C(4294988117))return 240;}
{uint64_t arguments[2]={UINT64_C(4294971750)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(6),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 241;if(g_calls[10][6]!=UINT32_C(1)||g_failures[10][6]!=UINT32_C(0))return 241;if(result!=UINT64_C(0))return 241;}
{uint64_t arguments[2]={UINT64_C(0)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(9),arguments,UINT32_C(0),&result)!=DEHERM_DMSDK_SCALAR_OK)return 242;if(g_calls[0][9]!=UINT32_C(1)||g_failures[0][9]!=UINT32_C(0))return 242;if(result!=UINT64_C(4294988185))return 242;}
{uint64_t arguments[2]={UINT64_C(0)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(10),arguments,UINT32_C(0),&result)!=DEHERM_DMSDK_SCALAR_OK)return 243;if(g_calls[0][10]!=UINT32_C(1)||g_failures[0][10]!=UINT32_C(0))return 243;if(result!=UINT64_C(4294988202))return 243;}
{uint64_t arguments[2]={UINT64_C(4539)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(11),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 244;if(g_calls[0][11]!=UINT32_C(1)||g_failures[0][11]!=UINT32_C(0))return 244;if(result!=UINT64_C(0))return 244;}
{uint64_t arguments[2]={pack_f32(112.25f)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(12),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 245;if(g_calls[0][12]!=UINT32_C(1)||g_failures[0][12]!=UINT32_C(0))return 245;if(result!=pack_f32(112.75f))return 245;}
{uint64_t arguments[2]={pack_f32(113.25f)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(13),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 246;if(g_calls[0][13]!=UINT32_C(1)||g_failures[0][13]!=UINT32_C(0))return 246;if(result!=pack_f32(113.75f))return 246;}
{const uint8_t* input=reinterpret_cast<const uint8_t*>("arena_3");uint8_t output[64]={};DehermDmSdkArenaCStringResult result{};if(deherm_dmsdk_arena_cstring_dispatch(UINT16_C(3),input,UINT32_C(7),UINT64_C(0),reinterpret_cast<char*>(output),UINT32_C(64),&result)!=DEHERM_DMSDK_ARENA_CSTRING_OK)return 247;if(g_calls[8][3]!=UINT32_C(1)||g_failures[8][3]!=UINT32_C(0))return 247;if(strcmp(reinterpret_cast<const char*>(output),"result_3")!=0||result.output_length!=UINT32_C(8)||result.required_length!=UINT32_C(9)||result.native_result!=UINT64_C(0))return 247;}
{uint64_t arguments[2]={UINT64_C(4590)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(14),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 248;if(g_calls[0][14]!=UINT32_C(1)||g_failures[0][14]!=UINT32_C(0))return 248;if(result!=UINT64_C(1))return 248;}
{uint64_t arguments[2]={UINT64_C(4607)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(15),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 249;if(g_calls[0][15]!=UINT32_C(1)||g_failures[0][15]!=UINT32_C(0))return 249;if(result!=UINT64_C(1))return 249;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{reinterpret_cast<const uint8_t*>("exact_12_0"),UINT32_C(10)}};uint64_t scalars[2]={UINT64_C(0)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(12),&scratch,strings,UINT32_C(1),scalars,UINT32_C(0),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 250;if(g_calls[7][12]!=UINT32_C(1)||g_failures[7][12]!=UINT32_C(0))return 250;if(result!=UINT64_C(20940))return 250;}
{uint64_t arguments[2]={UINT64_C(4624)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(16),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 251;if(g_calls[0][16]!=UINT32_C(1)||g_failures[0][16]!=UINT32_C(0))return 251;if(result!=UINT64_C(21008))return 251;}
{uint64_t arguments[2]={UINT64_C(4641)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(17),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 252;if(g_calls[0][17]!=UINT32_C(1)||g_failures[0][17]!=UINT32_C(0))return 252;if(result!=UINT64_C(21025))return 252;}
{uint64_t arguments[2]={UINT64_C(4294971954)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(18),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 253;if(g_calls[0][18]!=UINT32_C(1)||g_failures[0][18]!=UINT32_C(0))return 253;if(result!=UINT64_C(4294988338))return 253;}
{uint64_t arguments[2]={UINT64_C(4675)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(19),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 254;if(g_calls[0][19]!=UINT32_C(1)||g_failures[0][19]!=UINT32_C(0))return 254;if(result!=UINT64_C(21059))return 254;}
{uint64_t arguments[2]={UINT64_C(4692)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(20),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 255;if(g_calls[0][20]!=UINT32_C(1)||g_failures[0][20]!=UINT32_C(0))return 255;if(result!=UINT64_C(21076))return 255;}
{uint64_t arguments[2]={UINT64_C(4294972005)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(21),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 256;if(g_calls[0][21]!=UINT32_C(1)||g_failures[0][21]!=UINT32_C(0))return 256;if(result!=UINT64_C(4294988389))return 256;}
{uint64_t arguments[2]={UINT64_C(4726)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(22),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 257;if(g_calls[0][22]!=UINT32_C(1)||g_failures[0][22]!=UINT32_C(0))return 257;if(result!=UINT64_C(21110))return 257;}
{uint64_t arguments[2]={UINT64_C(4743)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(23),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 258;if(g_calls[0][23]!=UINT32_C(1)||g_failures[0][23]!=UINT32_C(0))return 258;if(result!=UINT64_C(21127))return 258;}
{uint64_t arguments[2]={UINT64_C(4294972056)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(24),arguments,UINT32_C(1),&result)!=DEHERM_DMSDK_SCALAR_OK)return 259;if(g_calls[0][24]!=UINT32_C(1)||g_failures[0][24]!=UINT32_C(0))return 259;if(result!=UINT64_C(4294988440))return 259;}
{uint64_t arguments[2]={UINT64_C(0)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_scalar_dispatch(UINT16_C(25),arguments,UINT32_C(0),&result)!=DEHERM_DMSDK_SCALAR_OK)return 260;if(g_calls[0][25]!=UINT32_C(1)||g_failures[0][25]!=UINT32_C(0))return 260;if(result!=UINT64_C(1))return 260;}
{uint64_t arguments[2]={UINT64_C(4294971767),pack_f32(107.25f)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(7),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 261;if(g_calls[10][7]!=UINT32_C(1)||g_failures[10][7]!=UINT32_C(0))return 261;if(result!=UINT64_C(0))return 261;}
{uint64_t arguments[2]={UINT64_C(4294971784),pack_f64(108.375)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(8),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 262;if(g_calls[10][8]!=UINT32_C(1)||g_failures[10][8]!=UINT32_C(0))return 262;if(result!=UINT64_C(0))return 262;}
{uint64_t arguments[2]={UINT64_C(4294971801),UINT64_C(4506)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(9),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 263;if(g_calls[10][9]!=UINT32_C(1)||g_failures[10][9]!=UINT32_C(0))return 263;if(result!=UINT64_C(0))return 263;}
{uint64_t arguments[2]={UINT64_C(4294971818),UINT64_C(4523)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(10),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 264;if(g_calls[10][10]!=UINT32_C(1)||g_failures[10][10]!=UINT32_C(0))return 264;if(result!=UINT64_C(0))return 264;}
{uint64_t arguments[2]={UINT64_C(4294971835),UINT64_C(4540)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(11),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 265;if(g_calls[10][11]!=UINT32_C(1)||g_failures[10][11]!=UINT32_C(0))return 265;if(result!=UINT64_C(0))return 265;}
{uint64_t arguments[2]={UINT64_C(4294971852),UINT64_C(4294971853)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(12),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 266;if(g_calls[10][12]!=UINT32_C(1)||g_failures[10][12]!=UINT32_C(0))return 266;if(result!=UINT64_C(0))return 266;}
{uint64_t arguments[2]={UINT64_C(4294971869),UINT64_C(4574)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(13),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 267;if(g_calls[10][13]!=UINT32_C(1)||g_failures[10][13]!=UINT32_C(0))return 267;if(result!=UINT64_C(0))return 267;}
{uint64_t arguments[2]={UINT64_C(4294971886),pack_f32(114.25f)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(14),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 268;if(g_calls[10][14]!=UINT32_C(1)||g_failures[10][14]!=UINT32_C(0))return 268;if(result!=UINT64_C(0))return 268;}
{uint64_t arguments[2]={UINT64_C(4294971903),pack_f64(115.375)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(15),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 269;if(g_calls[10][15]!=UINT32_C(1)||g_failures[10][15]!=UINT32_C(0))return 269;if(result!=UINT64_C(0))return 269;}
{uint64_t arguments[2]={UINT64_C(4294971920),UINT64_C(4625)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(16),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 270;if(g_calls[10][16]!=UINT32_C(1)||g_failures[10][16]!=UINT32_C(0))return 270;if(result!=UINT64_C(0))return 270;}
{uint64_t arguments[2]={UINT64_C(4294971937),UINT64_C(4642)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(17),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 271;if(g_calls[10][17]!=UINT32_C(1)||g_failures[10][17]!=UINT32_C(0))return 271;if(result!=UINT64_C(0))return 271;}
{uint64_t arguments[2]={UINT64_C(4294971954),UINT64_C(4659)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(18),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 272;if(g_calls[10][18]!=UINT32_C(1)||g_failures[10][18]!=UINT32_C(0))return 272;if(result!=UINT64_C(0))return 272;}
{uint64_t arguments[2]={UINT64_C(4294971971),UINT64_C(4294971972)};uint64_t result=UINT64_C(0xffff);if(deherm_dmsdk_named_scalar_dispatch(UINT16_C(19),arguments,UINT32_C(2),&result)!=DEHERM_DMSDK_NAMED_SCALAR_OK)return 273;if(g_calls[10][19]!=UINT32_C(1)||g_failures[10][19]!=UINT32_C(0))return 273;if(result!=UINT64_C(0))return 273;}
{const uint8_t* input=reinterpret_cast<const uint8_t*>("arena_4");uint8_t output[64]={};DehermDmSdkArenaCStringResult result{};if(deherm_dmsdk_arena_cstring_dispatch(UINT16_C(4),input,UINT32_C(7),UINT64_C(0),reinterpret_cast<char*>(output),UINT32_C(64),&result)!=DEHERM_DMSDK_ARENA_CSTRING_OK)return 274;if(g_calls[8][4]!=UINT32_C(1)||g_failures[8][4]!=UINT32_C(0))return 274;if(strcmp(reinterpret_cast<const char*>(output),"result_4")!=0||result.output_length!=UINT32_C(8)||result.required_length!=UINT32_C(504)||result.native_result!=UINT64_C(504))return 274;}
{uint8_t scratch_bytes[256]={};DehermDmSdkCStringScratch scratch{scratch_bytes,UINT32_C(256),UINT32_C(0)};DehermDmSdkCStringView strings[2]={{reinterpret_cast<const uint8_t*>("exact_13_0"),UINT32_C(10)}};uint64_t scalars[2]={UINT64_C(0)};uint64_t result=0;uint8_t output[64]={};uint32_t required=0;uint8_t present=0;if(deherm_dmsdk_cstring_value_dispatch(UINT16_C(13),&scratch,strings,UINT32_C(1),scalars,UINT32_C(0),&result,output,UINT32_C(64),&required,&present)!=DEHERM_DMSDK_CSTRING_OK)return 275;if(g_calls[7][13]!=UINT32_C(1)||g_failures[7][13]!=UINT32_C(0))return 275;if(!present||required!=UINT32_C(9)||strcmp(reinterpret_cast<const char*>(output),"result_13")!=0)return 275;}
{char output[64];memset(output,'x',sizeof(output));DehermDmSdkArenaCStringResult result{UINT64_C(9),9,9};g_arena_uri_failure=true;const char input[]="arena_3";const auto status=deherm_dmsdk_arena_cstring_dispatch(UINT16_C(3),reinterpret_cast<const uint8_t*>(input),UINT32_C(7),UINT64_C(0),output,UINT32_C(64),&result);g_arena_uri_failure=false;if(status!=DEHERM_DMSDK_ARENA_CSTRING_NATIVE_FAILURE||result.native_result!=0||result.output_length!=0||result.required_length!=0)return 276;for(char value:output)if(value!='\0')return 277;}
return 0;}
