// Generated by scripts/generate-dmsdk-universal-bindings.mjs. Do not edit.
#pragma once
#define DEHERM_TEST_TO_NETWORK_ID 234
#define DEHERM_TEST_TO_HOST_ID 229
#define DEHERM_TEST_DMSDK_CATALOG_SHA256 "e022158624fd769c4be6e957e86b8cd91c740626c5da625b738e4089de2cc571"
