// Generated by scripts/generate-script-recording-engine.mjs. Do not edit.
//
// The recording provider is the null/observer engine. It never executes Defold;
// it asserts the incoming call against its declared contract, records it, and
// returns a synthetic result of the declared shape.

#include "generated_script_recording_engine.h"

#include <defold_hermes/script_bridge_capi.hpp>
#include <defold_hermes/script_matrix4_arena.hpp>
#include <defold_hermes/script_url_arena.hpp>

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

using namespace defold_hermes;

namespace {

struct Observation {
  bool recorded = false;
  uint32_t arity = 0;
  std::string arguments;
  std::string context;
  std::string violation;
  bool driven = false;
  uint32_t resultCount = 0;
  std::string results;
  std::string status;
};

Observation gObservations[DEHERM_RECORDING_ROUTE_COUNT][DEHERM_RECORDING_TRANSPORT_COUNT];
uint32_t gTransport = 0;
uint32_t gViolations = 0;
char gLastError[512];

const char* textOf(int32_t id) {
  return id >= 0 && static_cast<uint32_t>(id) < DEHERM_RECORDING_TEXT_COUNT
      ? kDehermRecordingText[id] : "";
}

const char* handleName(ScriptHandleKind kind, uint8_t semantic) {
  if (kind == ScriptHandleKind::kGuiNode) return "gui-node";
  if (kind == ScriptHandleKind::kLuaUserdata) return "lua-userdata";
  if (kind == ScriptHandleKind::kLuaSemanticHandle) {
    return semantic > 0 && semantic < DEHERM_RECORDING_SEMANTIC_HANDLE_COUNT
        ? kDehermRecordingSemanticHandleNames[semantic] : "unknown";
  }
  return "unknown";
}

void renderValue(const ScriptValue& value, std::string& out, uint32_t depth) {
  if (depth > 8) { out += "deep"; return; }
  switch (value.tag) {
    case ScriptValueTag::kUndefined: out += "undef"; return;
    case ScriptValueTag::kNull: out += "null"; return;
    case ScriptValueTag::kBoolean: out += "bool"; return;
    case ScriptValueTag::kNumber: out += "num"; return;
    case ScriptValueTag::kString: {
      char buffer[32];
      std::snprintf(buffer, sizeof(buffer), "str:%u", value.length);
      out += buffer;
      return;
    }
    case ScriptValueTag::kHandle:
      if (value.handleKind == ScriptHandleKind::kHash) { out += "hash"; return; }
      if (value.handleKind == ScriptHandleKind::kUrl) { out += "url"; return; }
      out += "h:";
      out += handleName(value.handleKind, value.reserved);
      return;
    case ScriptValueTag::kDefoldValue:
      switch (value.defoldKind) {
        case ScriptDefoldValueKind::kVector3: out += "dv:v3"; return;
        case ScriptDefoldValueKind::kVector4: out += "dv:v4"; return;
        case ScriptDefoldValueKind::kQuaternion: out += "dv:quat"; return;
        case ScriptDefoldValueKind::kMatrix4: out += "dv:mat4"; return;
        default: out += "dv:unknown"; return;
      }
    case ScriptValueTag::kTable: {
      const auto* entries = static_cast<const ScriptTableEntry*>(value.data);
      const auto kind = static_cast<ScriptTableKind>(value.reserved);
      if (kind == ScriptTableKind::kSequence) {
        out += "seq(";
        for (uint32_t index = 0; index < value.length; ++index) {
          if (index) out += ",";
          renderValue(entries[index].value, out, depth + 1);
        }
        out += ")";
        return;
      }
      if (kind == ScriptTableKind::kRecord) {
        out += "rec(";
        for (uint32_t index = 0; index < value.length; ++index) {
          if (index) out += ",";
          const auto& key = entries[index].key;
          out.append(static_cast<const char*>(key.data), key.length);
          out += "=";
          renderValue(entries[index].value, out, depth + 1);
        }
        out += ")";
        return;
      }
      out += "map(";
      for (uint32_t index = 0; index < value.length; ++index) {
        if (index) out += ",";
        renderValue(entries[index].key, out, depth + 1);
        out += "=>";
        renderValue(entries[index].value, out, depth + 1);
      }
      out += ")";
      return;
    }
    case ScriptValueTag::kCallback: out += "cb"; return;
  }
  out += "unknown";
}

/** Structural contract check for one declared argument slot. */
bool matches(const ScriptValue& value, uint32_t shapeIndex, std::string& failure) {
  const auto& shape = kDehermRecordingShapes[shapeIndex];
  const auto expectTag = [&](ScriptValueTag tag) {
    if (value.tag == tag) return true;
    failure = "argument-tag-mismatch";
    return false;
  };
  switch (shape.code) {
    case DEHERM_RECORDING_SHAPE_UNDEFINED: return expectTag(ScriptValueTag::kUndefined);
    case DEHERM_RECORDING_SHAPE_NULL: return expectTag(ScriptValueTag::kNull);
    case DEHERM_RECORDING_SHAPE_BOOLEAN: return expectTag(ScriptValueTag::kBoolean);
    case DEHERM_RECORDING_SHAPE_NUMBER: return expectTag(ScriptValueTag::kNumber);
    case DEHERM_RECORDING_SHAPE_STRING:
      if (!expectTag(ScriptValueTag::kString)) return false;
      if (value.length && !value.data) { failure = "string-argument-has-null-storage"; return false; }
      return true;
    case DEHERM_RECORDING_SHAPE_HASH:
      if (!expectTag(ScriptValueTag::kHandle)) return false;
      if (value.handleKind != ScriptHandleKind::kHash) { failure = "hash-argument-handle-kind"; return false; }
      return true;
    case DEHERM_RECORDING_SHAPE_URL:
      if (!expectTag(ScriptValueTag::kHandle)) return false;
      if (value.handleKind != ScriptHandleKind::kUrl) { failure = "url-argument-handle-kind"; return false; }
      if (!value.data) { failure = "url-argument-has-no-arena-token"; return false; }
      return true;
    case DEHERM_RECORDING_SHAPE_HANDLE:
    case DEHERM_RECORDING_SHAPE_GUI_NODE:
    case DEHERM_RECORDING_SHAPE_USERDATA:
      if (!expectTag(ScriptValueTag::kHandle)) return false;
      if (value.handleKind != ScriptHandleKind::kGuiNode &&
          value.handleKind != ScriptHandleKind::kLuaUserdata &&
          value.handleKind != ScriptHandleKind::kLuaSemanticHandle) {
        failure = "retained-handle-argument-kind";
        return false;
      }
      if (value.length == 0) { failure = "retained-handle-argument-has-no-runtime-token"; return false; }
      return true;
    case DEHERM_RECORDING_SHAPE_VECTOR3:
    case DEHERM_RECORDING_SHAPE_VECTOR4:
    case DEHERM_RECORDING_SHAPE_QUATERNION:
    case DEHERM_RECORDING_SHAPE_MATRIX4:
      return expectTag(ScriptValueTag::kDefoldValue);
    case DEHERM_RECORDING_SHAPE_SEQUENCE:
    case DEHERM_RECORDING_SHAPE_RECORD:
    case DEHERM_RECORDING_SHAPE_MAP:
      if (!expectTag(ScriptValueTag::kTable)) return false;
      if (value.length && !value.data) { failure = "table-argument-has-null-storage"; return false; }
      return true;
    case DEHERM_RECORDING_SHAPE_CALLBACK:
      return expectTag(ScriptValueTag::kCallback);
    default:
      failure = "unsupported-declared-shape";
      return false;
  }
}

struct Synthesizer {
  ScriptCallFrame* frame;
  std::string failure;

  bool value(uint32_t shapeIndex, ScriptValue* out) {
    const auto& shape = kDehermRecordingShapes[shapeIndex];
    *out = {};
    switch (shape.code) {
      case DEHERM_RECORDING_SHAPE_UNDEFINED: out->tag = ScriptValueTag::kUndefined; return true;
      case DEHERM_RECORDING_SHAPE_NULL: out->tag = ScriptValueTag::kNull; return true;
      case DEHERM_RECORDING_SHAPE_BOOLEAN:
        out->tag = ScriptValueTag::kBoolean; out->number = 1.0; return true;
      case DEHERM_RECORDING_SHAPE_NUMBER:
        out->tag = ScriptValueTag::kNumber; out->number = 1.0; return true;
      case DEHERM_RECORDING_SHAPE_STRING: return string("deherm", out);
      case DEHERM_RECORDING_SHAPE_HASH:
        out->tag = ScriptValueTag::kHandle;
        out->handleKind = ScriptHandleKind::kHash;
        out->payload = UINT64_C(0x123456789abcdef0);
        return true;
      case DEHERM_RECORDING_SHAPE_URL:
        if (!frame->urlArena) { failure = "result-url-needs-a-frame-url-arena"; return false; }
        if (!frame->urlArena->store({1, 0, 2, 3}, out)) {
          failure = "result-url-arena-exhausted";
          return false;
        }
        return true;
      case DEHERM_RECORDING_SHAPE_HANDLE:
      case DEHERM_RECORDING_SHAPE_GUI_NODE:
      case DEHERM_RECORDING_SHAPE_USERDATA:
        out->tag = ScriptValueTag::kHandle;
        out->handleKind = shape.code == DEHERM_RECORDING_SHAPE_GUI_NODE
            ? ScriptHandleKind::kGuiNode
            : shape.code == DEHERM_RECORDING_SHAPE_USERDATA
                ? ScriptHandleKind::kLuaUserdata
                : ScriptHandleKind::kLuaSemanticHandle;
        out->reserved = shape.aux;
        out->length = 1;
        out->payload = (UINT64_C(1) << 32u) | UINT64_C(1);
        return true;
      case DEHERM_RECORDING_SHAPE_VECTOR3:
        out->tag = ScriptValueTag::kDefoldValue;
        out->defoldKind = ScriptDefoldValueKind::kVector3;
        out->defoldValue[0] = 1.0f; out->defoldValue[1] = 2.0f; out->defoldValue[2] = 3.0f;
        return true;
      case DEHERM_RECORDING_SHAPE_VECTOR4:
      case DEHERM_RECORDING_SHAPE_QUATERNION:
        out->tag = ScriptValueTag::kDefoldValue;
        out->defoldKind = shape.code == DEHERM_RECORDING_SHAPE_VECTOR4
            ? ScriptDefoldValueKind::kVector4 : ScriptDefoldValueKind::kQuaternion;
        for (uint32_t lane = 0; lane < 4; ++lane) out->defoldValue[lane] = static_cast<float>(lane + 1);
        return true;
      case DEHERM_RECORDING_SHAPE_MATRIX4: {
        if (!frame->matrix4Arena) { failure = "result-matrix4-needs-a-frame-arena"; return false; }
        float elements[16];
        for (uint32_t lane = 0; lane < 16; ++lane) elements[lane] = static_cast<float>(lane);
        if (!frame->matrix4Arena->store(elements, out)) {
          failure = "result-matrix4-arena-exhausted";
          return false;
        }
        return true;
      }
      case DEHERM_RECORDING_SHAPE_SEQUENCE: {
        if (!shape.childCount) return table(ScriptTableKind::kSequence, 0, nullptr, out);
        ScriptTableEntry entry{};
        entry.key.tag = ScriptValueTag::kNumber;
        entry.key.number = 1.0;
        if (!value(kDehermRecordingShapeRefs[shape.childFirst], &entry.value)) return false;
        return table(ScriptTableKind::kSequence, 1, &entry, out);
      }
      case DEHERM_RECORDING_SHAPE_RECORD: {
        std::vector<ScriptTableEntry> entries(shape.childCount);
        for (uint32_t index = 0; index < shape.childCount; ++index) {
          const uint32_t child = kDehermRecordingShapeRefs[shape.childFirst + index];
          if (!string(textOf(kDehermRecordingShapes[child].key), &entries[index].key)) return false;
          if (!value(child, &entries[index].value)) return false;
        }
        return table(ScriptTableKind::kRecord, shape.childCount,
            entries.empty() ? nullptr : entries.data(), out);
      }
      case DEHERM_RECORDING_SHAPE_MAP: {
        ScriptTableEntry entry{};
        if (!value(kDehermRecordingShapeRefs[shape.childFirst], &entry.key)) return false;
        if (!value(kDehermRecordingShapeRefs[shape.childFirst + 1], &entry.value)) return false;
        return table(ScriptTableKind::kMap, 1, &entry, out);
      }
      default:
        failure = "unsupported-declared-result-shape";
        return false;
    }
  }

  bool string(const char* literal, ScriptValue* out) {
    const uint32_t length = static_cast<uint32_t>(std::strlen(literal));
    if (!frame->stringScratch ||
        frame->stringScratchUsed > frame->stringScratchCapacity ||
        length > frame->stringScratchCapacity - frame->stringScratchUsed) {
      failure = "result-string-scratch-exhausted";
      return false;
    }
    char* destination = frame->stringScratch + frame->stringScratchUsed;
    std::memcpy(destination, literal, length);
    frame->stringScratchUsed += length;
    *out = {};
    out->tag = ScriptValueTag::kString;
    out->data = destination;
    out->length = length;
    return true;
  }

  bool table(ScriptTableKind kind, uint32_t count, const ScriptTableEntry* entries, ScriptValue* out) {
    // Every table claims at least one scratch slot so that two empty tables in
    // one result graph never share a storage address. The universal encoder
    // detects cycles by comparing ScriptValue::data pointers, so aliasing empty
    // tables would be rejected as a cycle.
    const uint32_t reserved = count ? count : 1u;
    if (!frame->tableScratch ||
        frame->tableScratchUsed > frame->tableScratchCapacity ||
        reserved > frame->tableScratchCapacity - frame->tableScratchUsed) {
      failure = "result-table-scratch-exhausted";
      return false;
    }
    ScriptTableEntry* destination = frame->tableScratch + frame->tableScratchUsed;
    for (uint32_t index = 0; index < count; ++index) destination[index] = entries[index];
    frame->tableScratchUsed += reserved;
    *out = {};
    out->tag = ScriptValueTag::kTable;
    out->reserved = static_cast<uint8_t>(kind);
    out->length = count;
    out->data = destination;
    return true;
  }
};

bool Dispatch(void*, ScriptCallFrame* frame) {
  const uint32_t route = deherm_recording_find_route(frame->stableId);
  if (route >= DEHERM_RECORDING_ROUTE_COUNT) {
    std::snprintf(gLastError, sizeof(gLastError), "recording engine has no route for stable id %u",
        frame->stableId);
    ++gViolations;
    return false;
  }
  const auto& descriptor = kDehermRecordingRoutes[route];
  Observation& observation = gObservations[route][gTransport];
  observation.recorded = true;
  observation.arity = frame->argumentCount;
  observation.context = textOf(descriptor.context);
  observation.arguments.clear();
  observation.violation.clear();

  if (frame->argumentCount != descriptor.argumentCount) {
    observation.violation = "arity-mismatch";
  } else if (frame->argumentCount && !frame->arguments) {
    observation.violation = "argument-storage-is-null";
  } else {
    for (uint32_t index = 0; index < frame->argumentCount; ++index) {
      if (index) observation.arguments += " ";
      renderValue(frame->arguments[index], observation.arguments, 0);
      std::string failure;
      if (observation.violation.empty() &&
          !matches(frame->arguments[index], kDehermRecordingShapeRefs[descriptor.argumentFirst + index], failure)) {
        observation.violation = failure;
      }
    }
  }
  if (observation.violation.empty() && descriptor.resultCount) {
    if (!frame->results) observation.violation = "result-storage-is-null";
    else if (frame->resultCapacity < descriptor.resultCount) observation.violation = "result-capacity-below-contract";
  }
  if (observation.violation.empty() && (frame->stringScratchUsed || frame->tableScratchUsed)) {
    observation.violation = "frame-scratch-was-not-fresh";
  }
  if (!observation.violation.empty()) {
    ++gViolations;
    std::snprintf(gLastError, sizeof(gLastError), "recording contract violation: %s",
        observation.violation.c_str());
    return false;
  }

  Synthesizer synthesizer{frame, {}};
  for (uint32_t index = 0; index < descriptor.resultCount; ++index) {
    if (!synthesizer.value(kDehermRecordingShapeRefs[descriptor.resultFirst + index], &frame->results[index])) {
      observation.violation = synthesizer.failure;
      ++gViolations;
      std::snprintf(gLastError, sizeof(gLastError), "recording result synthesis failed: %s",
          synthesizer.failure.c_str());
      return false;
    }
  }
  frame->resultCount = descriptor.resultCount;
  return true;
}

const char* LastError(void*) { return gLastError; }

void Release(void*, ScriptHandleKind, uint32_t, uint64_t) noexcept {}

}  // namespace

extern "C" {

uint32_t deherm_recording_find_route(uint32_t stableId) {
  for (uint32_t index = 0; index < DEHERM_RECORDING_ROUTE_COUNT; ++index) {
    if (kDehermRecordingRoutes[index].stableId == stableId) return index;
  }
  return DEHERM_RECORDING_ROUTE_COUNT;
}

void deherm_recording_install(void) {
  gLastError[0] = '\0';
  installScriptBridgeApi({nullptr, Dispatch, LastError, Release});
}

void deherm_recording_uninstall(void) { uninstallScriptBridgeApi(); }

void deherm_recording_select_transport(uint32_t transport) {
  gTransport = transport < DEHERM_RECORDING_TRANSPORT_COUNT ? transport : 0;
}

const char* deherm_recording_observed_arguments(uint32_t route, uint32_t transport) {
  return gObservations[route][transport].arguments.c_str();
}

uint32_t deherm_recording_observed_arity(uint32_t route, uint32_t transport) {
  return gObservations[route][transport].arity;
}

const char* deherm_recording_observed_context(uint32_t route, uint32_t transport) {
  return gObservations[route][transport].context.c_str();
}

const char* deherm_recording_observed_violation(uint32_t route, uint32_t transport) {
  return gObservations[route][transport].violation.c_str();
}

uint32_t deherm_recording_violation_count(void) { return gViolations; }

void deherm_recording_record_results(
    uint32_t route, uint32_t transport, uint32_t resultCount,
    const char* specification, const char* status) {
  if (route >= DEHERM_RECORDING_ROUTE_COUNT || transport >= DEHERM_RECORDING_TRANSPORT_COUNT) return;
  Observation& observation = gObservations[route][transport];
  observation.driven = true;
  observation.resultCount = resultCount;
  observation.results = specification ? specification : "";
  observation.status = status ? status : "";
}

const char* deherm_recording_driver_results(uint32_t route, uint32_t transport) {
  return gObservations[route][transport].results.c_str();
}

uint32_t deherm_recording_driver_result_count(uint32_t route, uint32_t transport) {
  return gObservations[route][transport].resultCount;
}

const char* deherm_recording_driver_status(uint32_t route, uint32_t transport) {
  return gObservations[route][transport].status.c_str();
}

int deherm_recording_driver_present(uint32_t route, uint32_t transport) {
  return gObservations[route][transport].driven ? 1 : 0;
}

}  // extern "C"
