// Generated by scripts/generate-script-recording-engine.mjs. Do not edit.
// Real Emscripten/Wasm entry point for the generated browser callback vectors.

#include "generated_script_recording_engine.h"

#include <cstdio>

extern "C" int deherm_recording_browser_run_exact(void);
// The full production bootstrap library also declares the demo modules. They
// are unreachable in this exact-call executable; provide inert link symbols so
// the Emscripten linker can retain the real callback registry without pulling
// Defold's Lua timer implementation into this transport-only proof.
extern "C" double defold_hermes_example_math_add(double, double) { return 0.0; }
extern "C" double defold_hermes_example_math_multiply(double, double) { return 0.0; }
extern "C" uint32_t defold_hermes_lua_timer_delay(
    double, uint8_t, uint32_t, uint32_t, uint32_t, uint32_t) { return UINT32_MAX; }
extern "C" uint8_t defold_hermes_lua_timer_cancel(uint32_t) { return 0; }
extern "C" uint8_t defold_hermes_lua_timer_trigger(uint32_t) { return 0; }

int main() {
  deherm_recording_install();
  deherm_recording_select_transport(DEHERM_RECORDING_TRANSPORT_DIRECT_MEMORY);
  const int status = deherm_recording_browser_run_exact();
  deherm_recording_uninstall();
  if (status != 0 || deherm_recording_violation_count() != 0) {
    std::printf("DEHERM_SCRIPT_BROWSER_CALLBACK_EXACT_FAIL status=%d violations=%u\n",
        status, deherm_recording_violation_count());
    return status ? status : 1;
  }
  std::printf("DEHERM_SCRIPT_BROWSER_CALLBACK_EXACT_OK routes=%u callbacks=%u plan=%s\n",
      DEHERM_RECORDING_BROWSER_CALLBACK_EXACT_COUNT,
      DEHERM_RECORDING_BROWSER_CALLBACK_EXACT_CALLBACK_COUNT,
      DEHERM_RECORDING_PLAN_SHA256);
  return 0;
}
