// Generated by scripts/generate-dmsdk-universal-bindings.mjs. Do not edit.
#pragma once
#define DEHERM_TEST_TO_NETWORK_ID 234
#define DEHERM_TEST_TO_HOST_ID 229
#define DEHERM_TEST_DMSDK_CATALOG_SHA256 "8fe44b7cd39449530dd63ecafb1a492642ecb85d93cc0d80c7caef6a2cab68c1"
