// Generated by scripts/generate-script-recording-engine.mjs. Do not edit.
#pragma once

#include <stdint.h>

#define DEHERM_RECORDING_SCHEMA_VERSION 1u
#define DEHERM_RECORDING_DEFOLD_REVISION "7f0f554f41f9dce1e0ddff99bf08200657d1ee05"
#define DEHERM_RECORDING_PLAN_SHA256 "6f83c9cdf23fa8d0e2f5c042872fe9545966ff45bfcf0e0c30a5624151c85a84"
#define DEHERM_RECORDING_EXPECTED_TRACE_SHA256 "b4dfb908454ad20f700ab1a35b1577a19854d8d0452f60a48df518538dab7680"
#define DEHERM_RECORDING_ROUTE_COUNT 915u
#define DEHERM_RECORDING_SHAPE_COUNT 427u
#define DEHERM_RECORDING_SHAPE_REF_COUNT 2253u
#define DEHERM_RECORDING_TEXT_COUNT 1264u
#define DEHERM_RECORDING_TRANSPORT_COUNT 3u
#define DEHERM_RECORDING_SEMANTIC_HANDLE_COUNT 16u

enum DehermRecordingShapeCode {
  DEHERM_RECORDING_SHAPE_UNDEFINED = 0,
  DEHERM_RECORDING_SHAPE_NULL = 1,
  DEHERM_RECORDING_SHAPE_BOOLEAN = 2,
  DEHERM_RECORDING_SHAPE_NUMBER = 3,
  DEHERM_RECORDING_SHAPE_STRING = 4,
  DEHERM_RECORDING_SHAPE_HASH = 5,
  DEHERM_RECORDING_SHAPE_URL = 6,
  DEHERM_RECORDING_SHAPE_HANDLE = 7,
  DEHERM_RECORDING_SHAPE_GUI_NODE = 8,
  DEHERM_RECORDING_SHAPE_USERDATA = 9,
  DEHERM_RECORDING_SHAPE_VECTOR3 = 10,
  DEHERM_RECORDING_SHAPE_VECTOR4 = 11,
  DEHERM_RECORDING_SHAPE_QUATERNION = 12,
  DEHERM_RECORDING_SHAPE_MATRIX4 = 13,
  DEHERM_RECORDING_SHAPE_SEQUENCE = 14,
  DEHERM_RECORDING_SHAPE_RECORD = 15,
  DEHERM_RECORDING_SHAPE_MAP = 16,
  DEHERM_RECORDING_SHAPE_CALLBACK = 17,
  DEHERM_RECORDING_SHAPE_UNSUPPORTED = 18
};

enum DehermRecordingTransport {
  DEHERM_RECORDING_TRANSPORT_JSI = 0,
  DEHERM_RECORDING_TRANSPORT_DIRECT_MEMORY = 1,
  DEHERM_RECORDING_TRANSPORT_TYPED_NATIVE = 2
};

enum DehermRecordingStatus {
  DEHERM_RECORDING_STATUS_EXERCISE = 0,
  DEHERM_RECORDING_STATUS_SKIP = 1
};

typedef struct DehermRecordingShape {
  uint8_t code;
  uint8_t aux;
  uint16_t childCount;
  uint32_t childFirst;
  int32_t key;
} DehermRecordingShape;

typedef struct DehermRecordingRoute {
  uint32_t stableId;
  int32_t canonical;
  int32_t context;
  uint16_t contract;
  uint8_t argumentCount;
  uint8_t resultCount;
  uint32_t argumentFirst;
  uint32_t resultFirst;
  uint8_t status[DEHERM_RECORDING_TRANSPORT_COUNT];
  int32_t reason[DEHERM_RECORDING_TRANSPORT_COUNT];
} DehermRecordingRoute;

#ifdef __cplusplus
extern "C" {
#endif

extern const char* const kDehermRecordingText[DEHERM_RECORDING_TEXT_COUNT];
extern const DehermRecordingShape kDehermRecordingShapes[DEHERM_RECORDING_SHAPE_COUNT];
extern const uint32_t kDehermRecordingShapeRefs[DEHERM_RECORDING_SHAPE_REF_COUNT];
extern const DehermRecordingRoute kDehermRecordingRoutes[DEHERM_RECORDING_ROUTE_COUNT];
extern const uint32_t kDehermRecordingOrder[DEHERM_RECORDING_ROUTE_COUNT];
extern const char* const kDehermRecordingSemanticHandleNames[DEHERM_RECORDING_SEMANTIC_HANDLE_COUNT];
extern const char* const kDehermRecordingTransportNames[DEHERM_RECORDING_TRANSPORT_COUNT];

/** Installs the recording provider underneath the real script bridge seam. */
void deherm_recording_install(void);
void deherm_recording_uninstall(void);
void deherm_recording_select_transport(uint32_t transport);
/** Recorded arity/argument/context observation for one route on one transport. */
const char* deherm_recording_observed_arguments(uint32_t route, uint32_t transport);
uint32_t deherm_recording_observed_arity(uint32_t route, uint32_t transport);
const char* deherm_recording_observed_context(uint32_t route, uint32_t transport);
const char* deherm_recording_observed_violation(uint32_t route, uint32_t transport);
uint32_t deherm_recording_violation_count(void);
/** Driver-side observation of what the real binding stack returned. */
void deherm_recording_record_results(
    uint32_t route, uint32_t transport, uint32_t resultCount,
    const char* specification, const char* status);
const char* deherm_recording_driver_results(uint32_t route, uint32_t transport);
uint32_t deherm_recording_driver_result_count(uint32_t route, uint32_t transport);
const char* deherm_recording_driver_status(uint32_t route, uint32_t transport);
int deherm_recording_driver_present(uint32_t route, uint32_t transport);
/** Synthesises the declared shape onto a caller-owned wire value graph. */
uint32_t deherm_recording_find_route(uint32_t stableId);

#ifdef __cplusplus
}
#endif
