// Generated by scripts/generate-script-callback-lifecycle.mjs. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <defold_hermes/callback_lifecycle_registry.hpp>

namespace defold_hermes::callback_lifecycle {
struct Route { uint16_t index; uint32_t stableId; const char* canonicalId; const char* callbackParameter; Lifetime lifetime; const char* owner; const char* invocationContext; const char* threadAffinity; bool registryEligible; };
inline constexpr size_t kRouteCount = 25;
const Route* routes() noexcept;
const Route* find(uint32_t stableId) noexcept;
}  // namespace defold_hermes::callback_lifecycle
