// Generated by scripts/generate-dmsdk-named-scalar-bindings.mjs. Do not edit.
#pragma once

// No named-scalar declaration has a safe default policy in this wave.
// Consequently this header intentionally declares no JSI installation surface.
