// Generated by scripts/generate-native-module-providers.mjs. Do not edit.
#pragma once
#if !defined(DM_PLATFORM_HTML5)
#include <jsi/jsi.h>
namespace defold_hermes {
void installGeneratedNativeModuleProviders(facebook::jsi::Runtime& runtime, facebook::jsi::Object& modules);
}
#endif
