// Generated by scripts/generate-script-universal-value-bindings.mjs. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

#include <defold_hermes/script_bridge_capi.hpp>

namespace defold_hermes::universal_value {

enum class DispatchStatus : uint8_t { kMissing, kSuccess, kError };

struct Operation {
  uint32_t stableId;
  const char* canonicalId;
  const char* modulePath;
  const char* member;
  uint8_t minimumArgumentCount;
  uint8_t maximumArgumentCount;
  uint8_t resultCount;
};

struct LuaApi {
  void* context = nullptr;
  DispatchStatus (*invoke)(void*, const Operation&, ScriptCallFrame*, char*, size_t) noexcept = nullptr;
};

inline constexpr size_t kOperationCount = 158;
inline constexpr size_t kMaximumArgumentCount = 7;
inline constexpr size_t kMaximumResultCount = 3;
inline constexpr uint32_t kMaximumDepth = 8;
inline constexpr uint32_t kMaximumEntries = 256;
inline constexpr uint32_t kMaximumStringBytes = 65536;

const Operation* operations() noexcept;
const Operation* find(uint32_t stableId) noexcept;
DispatchStatus dispatch(ScriptCallFrame*, char*, size_t, const LuaApi*) noexcept;

}  // namespace defold_hermes::universal_value
