// Generated by scripts/generate-script-overload-dispatch.mjs. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <defold_hermes/script_bridge_capi.hpp>

namespace defold_hermes::overload_dispatch {
enum class DispatchStatus : uint8_t { kMissing, kSuccess, kError };
enum CodecMask : uint16_t { kNumber=1u<<0, kVector3=1u<<1, kVector4=1u<<2, kQuaternion=1u<<3, kMatrix4=1u<<4 };
struct Operation { uint16_t index; uint32_t stableId; const char* canonicalId; const char* modulePath; const char* member; uint16_t shapeOffset; uint8_t shapeCount; };
struct Shape { uint16_t argumentOffset; uint8_t argumentCount; uint16_t resultMask; };
struct LuaApi { void* context = nullptr; DispatchStatus (*invoke)(void*, const Operation&, const Shape&, ScriptCallFrame*, char*, size_t) noexcept = nullptr; };
inline constexpr size_t kBindingCount = 8;
const Operation* operations() noexcept;
const Operation* find(uint32_t stableId) noexcept;
const Shape* shapes() noexcept;
const uint16_t* argumentCodecs() noexcept;
DispatchStatus dispatch(ScriptCallFrame*, char*, size_t, const LuaApi*) noexcept;
}
