// Generated by scripts/generate-bindings.mjs. Do not edit.
#pragma once

#if !defined(DM_PLATFORM_HTML5)
#include <jsi/jsi.h>

namespace defold_hermes {
class CallbackRegistry;
void installGeneratedModules(facebook::jsi::Runtime& runtime, facebook::jsi::Object& modules, CallbackRegistry& callbacks);
}
#endif
