// Generated by scripts/generate-dmsdk-base64-span-bindings.mjs. Do not edit.
#ifndef DEFOLD_HERMES_GENERATED_DMSDK_BASE64_SPAN_H
#define DEFOLD_HERMES_GENERATED_DMSDK_BASE64_SPAN_H
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
uint8_t deherm_dmsdk_base64_span_dm_crypt_base64_decode(const uint8_t* input, uint32_t input_length, uint8_t* output, uint32_t* inout_output_length);
uint8_t deherm_dmsdk_base64_span_dm_crypt_base64_encode(const uint8_t* input, uint32_t input_length, uint8_t* output, uint32_t* inout_output_length);
#ifdef __cplusplus
}
#endif
#endif
