// Generated by scripts/generate-dmsdk-universal-bindings.mjs. Do not edit.
#pragma once
#include <stdint.h>
#if !defined(DM_PLATFORM_HTML5)
#include <jsi/jsi.h>
#endif
namespace defold_hermes {
struct DmSdkUniversalJsiRegistrationMetadata {
  const char* module_name;
  const char* method_name;
  uint32_t recipe_count;
  uint32_t value_bytes;
};
inline constexpr DmSdkUniversalJsiRegistrationMetadata kDmSdkUniversalJsiRegistration = {
  "DmSdkUniversal", "call", UINT32_C(1361), UINT32_C(24)
};
#if !defined(DM_PLATFORM_HTML5)
void installDmSdkUniversalModule(facebook::jsi::Runtime& runtime, facebook::jsi::Object& modules);
#endif
}
