// Generated by scripts/generate-script-universal-value-bindings.mjs. Do not edit.
#pragma once

#include <stdint.h>

// Project builds may tune these bounds without regenerating the API catalog.
// They affect only the Static Hermes scratch pool, not the portable wire ABI.
#ifndef DEHERM_SCRIPT_STATIC_FRAME_REENTRANCY
#define DEHERM_SCRIPT_STATIC_FRAME_REENTRANCY 4u
#endif
#ifndef DEHERM_SCRIPT_STATIC_FRAME_STRING_BYTES
#define DEHERM_SCRIPT_STATIC_FRAME_STRING_BYTES 16384u
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct DehermScriptUniversalStaticFrame DehermScriptUniversalStaticFrame;

DehermScriptUniversalStaticFrame* deherm_script_static_frame_acquire(void);
uint32_t deherm_script_static_frame_bytes(void);
uint32_t deherm_script_static_frame_pool_bytes(void);
void deherm_script_static_frame_release(DehermScriptUniversalStaticFrame* frame);
void deherm_script_static_frame_reset(DehermScriptUniversalStaticFrame* frame);
uint32_t deherm_script_static_push_undefined(DehermScriptUniversalStaticFrame* frame);
uint32_t deherm_script_static_push_null(DehermScriptUniversalStaticFrame* frame);
uint32_t deherm_script_static_push_boolean(DehermScriptUniversalStaticFrame* frame, uint8_t value);
uint32_t deherm_script_static_push_number(DehermScriptUniversalStaticFrame* frame, double value);
uint32_t deherm_script_static_push_string(DehermScriptUniversalStaticFrame* frame, uint32_t byte_length);
uint8_t deherm_script_static_write_string_byte(DehermScriptUniversalStaticFrame* frame, uint32_t value_index, uint32_t byte_offset, uint8_t value);
uint32_t deherm_script_static_push_handle(DehermScriptUniversalStaticFrame* frame, uint8_t kind, uint8_t semantic_kind, uint32_t runtime, uint32_t payload_low, uint32_t payload_high);
uint32_t deherm_script_static_push_defold_value(DehermScriptUniversalStaticFrame* frame, uint8_t kind, float x, float y, float z, float w);
uint32_t deherm_script_static_push_table(DehermScriptUniversalStaticFrame* frame, uint8_t kind, uint32_t length);
uint8_t deherm_script_static_set_entry(DehermScriptUniversalStaticFrame* frame, uint32_t table_index, uint32_t entry, uint32_t key_index, uint32_t value_index);
uint8_t deherm_script_static_set_argument(DehermScriptUniversalStaticFrame* frame, uint32_t slot, uint32_t value_index);
uint32_t deherm_script_static_dispatch(DehermScriptUniversalStaticFrame* frame, uint32_t stable_id, uint32_t argument_count);
uint32_t deherm_script_static_result_count(const DehermScriptUniversalStaticFrame* frame);
uint32_t deherm_script_static_result_root(const DehermScriptUniversalStaticFrame* frame, uint32_t slot);
uint8_t deherm_script_static_value_tag(const DehermScriptUniversalStaticFrame* frame, uint32_t value_index);
uint8_t deherm_script_static_value_auxiliary(const DehermScriptUniversalStaticFrame* frame, uint32_t value_index);
uint8_t deherm_script_static_value_handle_kind(const DehermScriptUniversalStaticFrame* frame, uint32_t value_index);
uint8_t deherm_script_static_value_defold_kind(const DehermScriptUniversalStaticFrame* frame, uint32_t value_index);
uint32_t deherm_script_static_value_length(const DehermScriptUniversalStaticFrame* frame, uint32_t value_index);
double deherm_script_static_value_number(const DehermScriptUniversalStaticFrame* frame, uint32_t value_index);
uint32_t deherm_script_static_value_payload_low(const DehermScriptUniversalStaticFrame* frame, uint32_t value_index);
uint32_t deherm_script_static_value_payload_high(const DehermScriptUniversalStaticFrame* frame, uint32_t value_index);
uint32_t deherm_script_static_value_runtime(const DehermScriptUniversalStaticFrame* frame, uint32_t value_index);
void deherm_script_static_release_handle(uint8_t kind, uint32_t runtime, uint32_t payload_low, uint32_t payload_high);
float deherm_script_static_value_lane(const DehermScriptUniversalStaticFrame* frame, uint32_t value_index, uint32_t lane);
char* deherm_script_static_value_string(DehermScriptUniversalStaticFrame* frame, uint32_t value_index);
uint32_t deherm_script_static_entry_key(const DehermScriptUniversalStaticFrame* frame, uint32_t table_index, uint32_t entry);
uint32_t deherm_script_static_entry_value(const DehermScriptUniversalStaticFrame* frame, uint32_t table_index, uint32_t entry);
char* deherm_script_static_error(DehermScriptUniversalStaticFrame* frame);

#ifdef __cplusplus
}
#endif
