// Generated by scripts/generate-dmsdk-named-scalar-bindings.mjs. Do not edit.
#ifndef DEFOLD_HERMES_GENERATED_DMSDK_NAMED_SCALAR_H
#define DEFOLD_HERMES_GENERATED_DMSDK_NAMED_SCALAR_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// No named-scalar declaration has a safe default policy in this wave.

#ifdef __cplusplus
} // extern "C"
#endif

#endif // DEFOLD_HERMES_GENERATED_DMSDK_NAMED_SCALAR_H
