// Generated by scripts/generate-static-hermes-vmath.mjs. Do not edit.
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// A quiet NaN reports a generated-shape or engine dispatch error.
// Sound-typed wrappers convert this sentinel to a deterministic exception.
double deherm_static_vmath_8d4b1f66_length_vector3(float arg0_x, float arg0_y, float arg0_z);
double deherm_static_vmath_8d4b1f66_length_vector4(float arg0_x, float arg0_y, float arg0_z, float arg0_w);
double deherm_static_vmath_8d4b1f66_length_quaternion(float arg0_x, float arg0_y, float arg0_z, float arg0_w);
double deherm_static_vmath_a027f373_project_vector3_vector3(float arg0_x, float arg0_y, float arg0_z, float arg1_x, float arg1_y, float arg1_z);
double deherm_static_vmath_b1bb687b_length_sqr_vector3(float arg0_x, float arg0_y, float arg0_z);
double deherm_static_vmath_b1bb687b_length_sqr_vector4(float arg0_x, float arg0_y, float arg0_z, float arg0_w);
double deherm_static_vmath_b1bb687b_length_sqr_quaternion(float arg0_x, float arg0_y, float arg0_z, float arg0_w);

#ifdef __cplusplus
}
#endif
