// Generated by scripts/generate-lua-bridge.mjs. Do not edit.
#pragma once

#include <defold_hermes/lua_bridge.hpp>

namespace defold_hermes::lua_bridge::generated {

enum class Binding : uint32_t {
  TimerDelay = 0,
  TimerCancel = 1,
  TimerTrigger = 2,
  Count = 3
};

bool initialize(LuaBridge& bridge, lua_State* state, RegistryApi registryApi, InstanceApi instanceApi = {});

bool timerDelay(LuaBridge& bridge, double delay, bool repeating, Handle callback, uint32_t* out);
bool timerCancel(LuaBridge& bridge, uint32_t handle, bool* out);
bool timerTrigger(LuaBridge& bridge, uint32_t handle, bool* out);

}  // namespace defold_hermes::lua_bridge::generated
