// Generated by scripts/generate-script-universal-value-bindings.mjs. Do not edit.
#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DEHERM_SCRIPT_UNIVERSAL_ABI_VERSION 1u
#define DEHERM_SCRIPT_UNIVERSAL_MAX_ARGUMENTS 32u
#define DEHERM_SCRIPT_UNIVERSAL_MAX_RESULTS 3u
#define DEHERM_SCRIPT_UNIVERSAL_MAX_DEPTH 8u
#define DEHERM_SCRIPT_UNIVERSAL_MAX_ENTRIES 256u
#define DEHERM_SCRIPT_UNIVERSAL_MAX_VALUES 547u
#define DEHERM_SCRIPT_UNIVERSAL_MAX_STRING_BYTES 65536u
#define DEHERM_SCRIPT_UNIVERSAL_MAX_MATRIX4_VALUES 16u
#define DEHERM_SCRIPT_UNIVERSAL_MAX_URL_VALUES 32u

typedef enum DehermScriptUniversalStatus {
  DEHERM_SCRIPT_UNIVERSAL_OK = 0,
  DEHERM_SCRIPT_UNIVERSAL_ROUTE_MISSING = 1,
  DEHERM_SCRIPT_UNIVERSAL_INVALID_VALUE = 2,
  DEHERM_SCRIPT_UNIVERSAL_ARENA_EXHAUSTED = 3,
  DEHERM_SCRIPT_UNIVERSAL_BACKEND_ERROR = 4
} DehermScriptUniversalStatus;

typedef struct DehermScriptUniversalValue {
  uint8_t tag;
  uint8_t handle_kind;
  uint8_t defold_kind;
  uint8_t auxiliary;
  uint32_t length;
  double number;
  uint64_t payload;
  uint32_t data_offset;
  uint32_t runtime;
  float lanes[4];
} DehermScriptUniversalValue;

typedef struct DehermScriptUniversalEntry {
  uint32_t key_index;
  uint32_t value_index;
} DehermScriptUniversalEntry;

typedef struct DehermScriptUniversalUrl {
  uint64_t socket;
  uint64_t reserved;
  uint64_t path;
  uint64_t fragment;
} DehermScriptUniversalUrl;

DehermScriptUniversalStatus deherm_script_universal_dispatch(
    uint32_t stable_id,
    const DehermScriptUniversalValue* input_values, uint32_t input_value_count,
    const DehermScriptUniversalEntry* input_entries, uint32_t input_entry_count,
    const char* input_strings, uint32_t input_string_bytes,
    const float* input_floats, uint32_t input_float_count,
    const DehermScriptUniversalUrl* input_urls, uint32_t input_url_count,
    const uint32_t* argument_roots, uint32_t argument_count,
    DehermScriptUniversalValue* output_values, uint32_t output_value_capacity,
    uint32_t* output_value_count,
    DehermScriptUniversalEntry* output_entries, uint32_t output_entry_capacity,
    uint32_t* output_entry_count,
    char* output_strings, uint32_t output_string_capacity,
    uint32_t* output_string_bytes,
    float* output_floats, uint32_t output_float_capacity,
    uint32_t* output_float_count,
    DehermScriptUniversalUrl* output_urls, uint32_t output_url_capacity,
    uint32_t* output_url_count,
    uint32_t* result_roots, uint32_t result_capacity,
    uint32_t* result_count,
    char* error, uint32_t error_capacity);

void deherm_script_universal_release(DehermScriptUniversalValue* value);

#ifdef __cplusplus
}
static_assert(sizeof(DehermScriptUniversalValue) == 48, "universal wire value layout drifted");
static_assert(offsetof(DehermScriptUniversalValue, number) == 8, "universal wire number offset drifted");
static_assert(offsetof(DehermScriptUniversalValue, payload) == 16, "universal wire payload offset drifted");
static_assert(offsetof(DehermScriptUniversalValue, lanes) == 32, "universal wire lane offset drifted");
static_assert(sizeof(DehermScriptUniversalEntry) == 8, "universal wire entry layout drifted");
static_assert(sizeof(DehermScriptUniversalUrl) == 32, "universal wire URL layout drifted");
#else
_Static_assert(sizeof(DehermScriptUniversalValue) == 48, "universal wire value layout drifted");
_Static_assert(offsetof(DehermScriptUniversalValue, number) == 8, "universal wire number offset drifted");
_Static_assert(offsetof(DehermScriptUniversalValue, payload) == 16, "universal wire payload offset drifted");
_Static_assert(offsetof(DehermScriptUniversalValue, lanes) == 32, "universal wire lane offset drifted");
_Static_assert(sizeof(DehermScriptUniversalEntry) == 8, "universal wire entry layout drifted");
_Static_assert(sizeof(DehermScriptUniversalUrl) == 32, "universal wire URL layout drifted");
#endif
