// Generated by scripts/generate-dmsdk-cstring-value-bindings.mjs. Do not edit.
#pragma once
#if defined(DEHERM_ENABLE_PRIVATE_DMSDK_CSTRING_VALUE) && !defined(DM_PLATFORM_HTML5)
#include <jsi/jsi.h>
namespace defold_hermes { void installDmSdkCStringValueModule(facebook::jsi::Runtime&,facebook::jsi::Object&); }
#endif
