// Generated by @deherm/compiler dmsdk-universal-static-frame. Do not edit.
#pragma once

#include <stdint.h>
#include <defold_hermes/generated_dmsdk_universal.h>

#define DEHERM_DMSDK_STATIC_FRAME_ARGUMENT_CAPACITY UINT32_C(32)
#ifndef DEHERM_DMSDK_STATIC_FRAME_REENTRANCY
#define DEHERM_DMSDK_STATIC_FRAME_REENTRANCY 4u
#endif

#ifdef __cplusplus
extern "C" {
#endif
typedef struct DehermDmSdkUniversalStaticFrame DehermDmSdkUniversalStaticFrame;
DehermDmSdkUniversalStaticFrame* deherm_dmsdk_static_frame_acquire(void);
void deherm_dmsdk_static_frame_release(DehermDmSdkUniversalStaticFrame* frame);
void deherm_dmsdk_static_frame_reset(DehermDmSdkUniversalStaticFrame* frame);
uint32_t deherm_dmsdk_static_frame_bytes(void);
uint32_t deherm_dmsdk_static_frame_pool_bytes(void);
uint8_t deherm_dmsdk_static_frame_set(DehermDmSdkUniversalStaticFrame* frame,uint32_t slot,uint32_t payload_low,uint32_t payload_high,uint32_t auxiliary_low,uint32_t auxiliary_high,uint32_t tag,uint32_t type_id);
uint32_t deherm_dmsdk_static_frame_dispatch(DehermDmSdkUniversalStaticFrame* frame,uint32_t id,uint32_t argument_count);
uint32_t deherm_dmsdk_static_frame_result_payload_low(const DehermDmSdkUniversalStaticFrame* frame);
uint32_t deherm_dmsdk_static_frame_result_payload_high(const DehermDmSdkUniversalStaticFrame* frame);
uint32_t deherm_dmsdk_static_frame_result_auxiliary_low(const DehermDmSdkUniversalStaticFrame* frame);
uint32_t deherm_dmsdk_static_frame_result_auxiliary_high(const DehermDmSdkUniversalStaticFrame* frame);
uint32_t deherm_dmsdk_static_frame_result_tag(const DehermDmSdkUniversalStaticFrame* frame);
uint32_t deherm_dmsdk_static_frame_result_type_id(const DehermDmSdkUniversalStaticFrame* frame);
#ifdef __cplusplus
}
#endif
