// Generated by scripts/generate-dmsdk-scratch-scalar-out-bindings.mjs. Do not edit.
#pragma once
#if !defined(DM_PLATFORM_HTML5)
#include <jsi/jsi.h>
namespace defold_hermes { void installDmSdkScratchScalarOutModule(facebook::jsi::Runtime&, facebook::jsi::Object&); }
#endif
