// Generated by scripts/generate-dmsdk-fixed-digest-bindings.mjs. Do not edit.
#ifndef DEFOLD_HERMES_GENERATED_DMSDK_FIXED_DIGEST_H
#define DEFOLD_HERMES_GENERATED_DMSDK_FIXED_DIGEST_H
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_md5(const uint8_t* input, uint32_t input_length, uint8_t output[16], uint32_t output_capacity);
uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_sha1(const uint8_t* input, uint32_t input_length, uint8_t output[20], uint32_t output_capacity);
uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_sha256(const uint8_t* input, uint32_t input_length, uint8_t output[32], uint32_t output_capacity);
uint8_t deherm_dmsdk_fixed_digest_dm_crypt_hash_sha512(const uint8_t* input, uint32_t input_length, uint8_t output[64], uint32_t output_capacity);
#ifdef __cplusplus
}
#endif
#endif
