// Generated by scripts/generate-dmsdk-scalar-thunks.mjs. Do not edit.
#ifndef DEFOLD_HERMES_GENERATED_DMSDK_SCALAR_H
#define DEFOLD_HERMES_GENERATED_DMSDK_SCALAR_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

uint16_t deherm_dmsdk_dm_endian_byte_swap_u16(uint16_t x);
uint32_t deherm_dmsdk_dm_endian_byte_swap_u32(uint32_t x);
uint64_t deherm_dmsdk_dm_endian_byte_swap_u64(uint64_t x);
uint32_t deherm_dmsdk_dm_endian_to_host_u32(uint32_t x);
uint64_t deherm_dmsdk_dm_endian_to_host_u64(uint64_t x);
uint16_t deherm_dmsdk_dm_endian_to_host_u16(uint16_t x);
uint64_t deherm_dmsdk_dm_endian_to_network_u64(uint64_t x);
uint16_t deherm_dmsdk_dm_endian_to_network_u16(uint16_t x);
uint32_t deherm_dmsdk_dm_endian_to_network_u32(uint32_t x);
void deherm_dmsdk_dm_log_log_finalize_v(void);
void deherm_dmsdk_dm_log_finalize_v(void);
uint64_t deherm_dmsdk_dm_time_get_monotonic_time_v(void);
uint64_t deherm_dmsdk_dm_time_get_time_v(void);
void deherm_dmsdk_dm_time_sleep_u32(uint32_t useconds);
float deherm_dmsdk_dm_trig_lookup_cos_f32(float radians);
float deherm_dmsdk_dm_trig_lookup_sin_f32(float radians);
uint8_t deherm_dmsdk_dm_utf8_is_breaking_u32(uint32_t c);
uint8_t deherm_dmsdk_dm_utf8_is_white_space_u32(uint32_t c);
uint16_t deherm_dmsdk_endian_swap16_u16(uint16_t x);
uint32_t deherm_dmsdk_endian_swap32_u32(uint32_t x);
uint64_t deherm_dmsdk_endian_swap64_u64(uint64_t x);
uint16_t deherm_dmsdk_endian_to_host16_u16(uint16_t x);
uint32_t deherm_dmsdk_endian_to_host32_u32(uint32_t x);
uint64_t deherm_dmsdk_endian_to_host64_u64(uint64_t x);
uint16_t deherm_dmsdk_endian_to_network16_u16(uint16_t x);
uint32_t deherm_dmsdk_endian_to_network32_u32(uint32_t x);
uint64_t deherm_dmsdk_endian_to_network64_u64(uint64_t x);
void deherm_dmsdk_profile_finalize_v(void);
void deherm_dmsdk_profile_initialize_v(void);
uint8_t deherm_dmsdk_profile_is_initialized_v(void);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // DEFOLD_HERMES_GENERATED_DMSDK_SCALAR_H
