// Generated by scripts/generate-dmsdk-scalar-thunks.mjs. Do not edit.
#pragma once

#if !defined(DM_PLATFORM_HTML5)
#include <jsi/jsi.h>
namespace defold_hermes {
void installDmSdkScalarModule(facebook::jsi::Runtime& runtime, facebook::jsi::Object& modules);
}
#endif
