// Generated by scripts/generate-script-universal-value-bindings.mjs. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

#include <defold_hermes/script_bridge_capi.hpp>

namespace defold_hermes::universal_value {

enum class DispatchStatus : uint8_t { kMissing, kSuccess, kError };

struct Operation {
  uint32_t stableId;
  const char* canonicalId;
  const char* modulePath;
  const char* member;
  uint8_t minimumArgumentCount;
  uint8_t maximumArgumentCount;
  uint8_t minimumResultCount;
  uint8_t maximumResultCount;
  uint8_t resultCount;
  /**
   * Dense semantic borrowed-handle kind of this route's single declared
   * result, or zero when the result is not a rooted engine handle.
   *
   * A route's lowering family is a single-winner precedence in which a
   * table-shaped parameter outranks a handle, so a constructor that takes a
   * definition record is marshalled here rather than by the handle-lowering
   * table - while still returning a live engine object. Without this the
   * result would cross as an anonymous Lua userdata and every handle-lowered
   * consumer would refuse it. The numbering is the one
   * script_handle_lowering::SemanticHandleKind uses, derived by both
   * generators from the same pinned classification.
   */
  uint16_t resultSemanticKind;
  /**
   * Per-call frame scratch this route's value shapes can reach, derived from
   * the same projected signature the arity fields come from. A transport sizes
   * its frame from these; a backend may not address scratch beyond them.
   */
  uint16_t inputTableEntryCapacity;
  uint16_t outputTableEntryCapacity;
  uint8_t matrix4Arena;
  uint8_t urlArena;
};

struct LuaApi {
  void* context = nullptr;
  DispatchStatus (*invoke)(void*, const Operation&, ScriptCallFrame*, char*, size_t) noexcept = nullptr;
};

inline constexpr size_t kOperationCount = 915;
inline constexpr size_t kMaximumArgumentCount = 32;
inline constexpr size_t kMaximumResultCount = 4;
inline constexpr uint32_t kMaximumDepth = 8;
inline constexpr uint32_t kMaximumEntries = 256;
inline constexpr uint32_t kMaximumStringBytes = 65536;

const Operation* operations() noexcept;
const Operation* find(uint32_t stableId) noexcept;
DispatchStatus dispatch(ScriptCallFrame*, char*, size_t, const LuaApi*) noexcept;

}  // namespace defold_hermes::universal_value
