// Generated by scripts/generate-script-url-address-classification.mjs. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <defold_hermes/script_bridge_capi.hpp>

namespace defold_hermes::url_binding {
enum class DispatchStatus : uint8_t { kMissing, kSuccess, kError };
enum CodecMask : uint16_t {
  kNil = 1u << 0, kBoolean = 1u << 1, kInteger = 1u << 2, kNumber = 1u << 3,
  kString = 1u << 4, kHash = 1u << 5, kUrl = 1u << 6, kVector3 = 1u << 7,
  kVector4 = 1u << 8, kQuaternion = 1u << 9
};
enum class ResultCodec : uint8_t { kNone, kNil, kBoolean, kInteger, kNumber, kString, kHash, kHashOrNil, kUrl, kVector3, kVector4, kQuaternion };
struct Operation { uint16_t index; uint32_t stableId; const char* canonicalId; const char* module; const char* member; uint16_t argumentOffset; uint8_t requiredArgumentCount; uint8_t maximumArgumentCount; ResultCodec resultCodec; };
struct LuaApi { void* context = nullptr; DispatchStatus (*invoke)(void*, const Operation&, const uint16_t*, ScriptCallFrame*, char*, size_t) noexcept = nullptr; };
inline constexpr size_t kBindingCount = 70;
const Operation* operations() noexcept;
const Operation* find(uint32_t stableId) noexcept;
const uint16_t* argumentCodecs() noexcept;
DispatchStatus dispatch(ScriptCallFrame*, char*, size_t, const LuaApi*) noexcept;
}
