// Generated by scripts/generate-dmsdk-hash-span-bindings.mjs. Do not edit.
#ifndef DEFOLD_HERMES_GENERATED_DMSDK_HASH_SPAN_RUNTIME_H
#define DEFOLD_HERMES_GENERATED_DMSDK_HASH_SPAN_RUNTIME_H
#include <stdint.h>
typedef enum DehermDmSdkHashSpanStatus { DEHERM_DMSDK_HASH_SPAN_OK=0, DEHERM_DMSDK_HASH_SPAN_UNKNOWN_ID=1, DEHERM_DMSDK_HASH_SPAN_NULL_STORAGE=2 } DehermDmSdkHashSpanStatus;
typedef struct DehermDmSdkHashSpanDescriptor { uint16_t id; uint8_t result_bits; const char* declaration_id; } DehermDmSdkHashSpanDescriptor;
#ifdef __cplusplus
extern "C" {
#endif
uint32_t deherm_dmsdk_hash_span_count(void);
const DehermDmSdkHashSpanDescriptor* deherm_dmsdk_hash_span_descriptors(void);
DehermDmSdkHashSpanStatus deherm_dmsdk_hash_span_dispatch(uint16_t id, const uint8_t* input, uint32_t input_length, uint64_t* out_hash);
#ifdef __cplusplus
}
#endif
#endif
