// Generated by scripts/generate-dmsdk-hash-state-bindings.mjs. Do not edit.
#ifndef DEFOLD_HERMES_GENERATED_DMSDK_HASH_STATE_H
#define DEFOLD_HERMES_GENERATED_DMSDK_HASH_STATE_H
#include <stdint.h>
#define DEHERM_DMSDK_HASH_STATE_CAPACITY_PER_WIDTH UINT32_C(16)
typedef enum DehermDmSdkHashStateStatus { DEHERM_DMSDK_HASH_STATE_OK=0, DEHERM_DMSDK_HASH_STATE_UNKNOWN_ID=1, DEHERM_DMSDK_HASH_STATE_NULL_STORAGE=2, DEHERM_DMSDK_HASH_STATE_INVALID_HANDLE=3, DEHERM_DMSDK_HASH_STATE_CAPACITY_EXHAUSTED=4, DEHERM_DMSDK_HASH_STATE_INVALID_ARGUMENT=5, DEHERM_DMSDK_HASH_STATE_REENTRANT=6 } DehermDmSdkHashStateStatus;
typedef enum DehermDmSdkHashStateId {
  DEHERM_DMSDK_HASH_STATE_CLONE_32 = 0,
  DEHERM_DMSDK_HASH_STATE_CLONE_64 = 1,
  DEHERM_DMSDK_HASH_STATE_FINAL_32 = 2,
  DEHERM_DMSDK_HASH_STATE_FINAL_64 = 3,
  DEHERM_DMSDK_HASH_STATE_INIT_32 = 4,
  DEHERM_DMSDK_HASH_STATE_INIT_64 = 5,
  DEHERM_DMSDK_HASH_STATE_RELEASE_32 = 6,
  DEHERM_DMSDK_HASH_STATE_RELEASE_64 = 7,
  DEHERM_DMSDK_HASH_STATE_UPDATE_BUFFER_32 = 8,
  DEHERM_DMSDK_HASH_STATE_UPDATE_BUFFER_64 = 9,
} DehermDmSdkHashStateId;
typedef struct DehermDmSdkHashStateDescriptor { uint16_t id; uint8_t width; uint8_t consumes; const char* operation; const char* declaration_id; } DehermDmSdkHashStateDescriptor;
#ifdef __cplusplus
extern "C" {
#endif
uint32_t deherm_dmsdk_hash_state_count(void);
const DehermDmSdkHashStateDescriptor* deherm_dmsdk_hash_state_descriptors(void);
DehermDmSdkHashStateStatus deherm_dmsdk_hash_state_dispatch(uint16_t id, uint64_t handle, const uint8_t* input, uint32_t input_length, uint8_t reverse_hash, uint64_t* out_value);
#ifdef __cplusplus
}
#endif
#endif
