// Generated by scripts/generate-dmsdk-scalar-thunks.mjs. Do not edit.
#ifndef DEFOLD_HERMES_GENERATED_DMSDK_SCALAR_RUNTIME_H
#define DEFOLD_HERMES_GENERATED_DMSDK_SCALAR_RUNTIME_H

#include <stdint.h>

#define DEHERM_DMSDK_SCALAR_MAX_ARGUMENTS 1

typedef enum DehermDmSdkScalarValueKind {
  DEHERM_DMSDK_SCALAR_VOID = 0,
  DEHERM_DMSDK_SCALAR_BOOL = 1,
  DEHERM_DMSDK_SCALAR_U16 = 2,
  DEHERM_DMSDK_SCALAR_U32 = 3,
  DEHERM_DMSDK_SCALAR_U64 = 4,
  DEHERM_DMSDK_SCALAR_F32 = 5
} DehermDmSdkScalarValueKind;

typedef enum DehermDmSdkScalarStatus {
  DEHERM_DMSDK_SCALAR_OK = 0,
  DEHERM_DMSDK_SCALAR_UNKNOWN_ID = 1,
  DEHERM_DMSDK_SCALAR_WRONG_ARITY = 2,
  DEHERM_DMSDK_SCALAR_NULL_STORAGE = 3
} DehermDmSdkScalarStatus;

typedef enum DehermDmSdkScalarFlags {
  DEHERM_DMSDK_SCALAR_NATIVE_JS = 1,
  DEHERM_DMSDK_SCALAR_BROWSER_JS = 2,
  DEHERM_DMSDK_SCALAR_MAY_BLOCK = 4
} DehermDmSdkScalarFlags;

typedef struct DehermDmSdkScalarDescriptor {
  uint16_t id;
  uint8_t argument_count;
  uint8_t return_kind;
  uint8_t argument_kinds[DEHERM_DMSDK_SCALAR_MAX_ARGUMENTS];
  uint8_t flags;
  const char* declaration_id;
  const char* symbol;
} DehermDmSdkScalarDescriptor;

#ifdef __cplusplus
extern "C" {
#endif

uint32_t deherm_dmsdk_scalar_count(void);
const DehermDmSdkScalarDescriptor* deherm_dmsdk_scalar_descriptors(void);
DehermDmSdkScalarStatus deherm_dmsdk_scalar_dispatch(
    uint16_t id, const uint64_t* arguments, uint32_t argument_count, uint64_t* result);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // DEFOLD_HERMES_GENERATED_DMSDK_SCALAR_RUNTIME_H
