// Generated by scripts/generate-dmsdk-enum-value-bindings.mjs. Do not edit.
#ifndef DEFOLD_HERMES_GENERATED_DMSDK_ENUM_VALUE_H
#define DEFOLD_HERMES_GENERATED_DMSDK_ENUM_VALUE_H
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
uint32_t deherm_dmsdk_enum_dm_buffer_get_size_for_value_type_i32(int32_t type);
int32_t deherm_dmsdk_enum_dm_graphics_get_installed_adapter_family_v(void);
void deherm_dmsdk_enum_dm_log_setlevel_i32(int32_t severity);
int32_t deherm_dmsdk_enum_dm_log_get_level_v(void);
void deherm_dmsdk_enum_dm_log_set_level_i32(int32_t severity);
int32_t deherm_dmsdk_enum_dm_sound_set_group_mute_u64_bool(uint64_t group, uint8_t mute);
int32_t deherm_dmsdk_enum_dm_sound_toggle_group_mute_u64(uint64_t group);
#ifdef __cplusplus
}
#endif
#endif
