// Generated by scripts/generate-native-module-providers.mjs. Do not edit.
#ifndef DEHERM_NATIVE_MODULE_PROVIDER_H
#define DEHERM_NATIVE_MODULE_PROVIDER_H
#include <stddef.h>
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
#define DEHERM_NATIVE_MODULE_PROVIDER_ABI_VERSION UINT32_C(1)
#define DEHERM_NATIVE_MODULE_MAX_ARGUMENTS UINT32_C(8)
typedef enum DehermNativeModuleArgumentKindV1 {
  DEHERM_NATIVE_MODULE_ARGUMENT_U32 = 1,
  DEHERM_NATIVE_MODULE_ARGUMENT_UTF8 = 2,
  DEHERM_NATIVE_MODULE_ARGUMENT_BYTES = 3,
  DEHERM_NATIVE_MODULE_ARGUMENT_MUTABLE_BYTES = 4,
  DEHERM_NATIVE_MODULE_ARGUMENT_BOOL = 5
} DehermNativeModuleArgumentKindV1;
typedef enum DehermNativeModuleResultKindV1 {
  DEHERM_NATIVE_MODULE_RESULT_STATUS = 1,
  DEHERM_NATIVE_MODULE_RESULT_U32 = 2
} DehermNativeModuleResultKindV1;
typedef struct DehermNativeModuleArgumentV1 {
  uint32_t kind;
  uint32_t u32;
  const uint8_t* bytes;
  uint8_t* mutable_bytes;
  size_t length;
} DehermNativeModuleArgumentV1;
typedef struct DehermNativeModuleResultV1 { uint32_t u32; } DehermNativeModuleResultV1;
typedef struct DehermNativeModuleMethodV1 {
  uint32_t id;
  const char* name;
  uint32_t argument_count;
  uint32_t argument_kinds[DEHERM_NATIVE_MODULE_MAX_ARGUMENTS];
  uint32_t result_kind;
} DehermNativeModuleMethodV1;
typedef int32_t (*DehermNativeModuleInvokeV1)(
    void* context, uint32_t method_id,
    const DehermNativeModuleArgumentV1* arguments, size_t argument_count,
    DehermNativeModuleResultV1* result_out);
typedef struct DehermNativeModuleProviderV1 {
  uint32_t abi_version;
  uint32_t struct_size;
  const char* module_name;
  uint32_t module_abi_version;
  uint32_t method_count;
  const DehermNativeModuleMethodV1* methods;
  void* context;
  DehermNativeModuleInvokeV1 invoke;
} DehermNativeModuleProviderV1;
typedef enum DehermNativeModuleRegistryStatusV1 {
  DEHERM_NATIVE_MODULE_REGISTRY_OK = 0,
  DEHERM_NATIVE_MODULE_REGISTRY_INVALID_ARGUMENT = -1,
  DEHERM_NATIVE_MODULE_REGISTRY_FULL = -2,
  DEHERM_NATIVE_MODULE_REGISTRY_DUPLICATE = -3,
  DEHERM_NATIVE_MODULE_REGISTRY_NOT_FOUND = -4
} DehermNativeModuleRegistryStatusV1;
/* The registry copies descriptors into bounded core storage. Register on the
 * engine thread before the module's first lookup; registration may occur after
 * runtime construction because lookup is lazy. Once resolved, host functions
 * retain the provider context/invoke snapshot, so unregister only after that
 * runtime is destroyed. Byte/string
 * views are borrowed only for invoke(); mutable bytes are caller-owned output.
 * The bridge never marshals packet data through Lua. */
int32_t deherm_native_module_register_v1(const DehermNativeModuleProviderV1* provider);
int32_t deherm_native_module_unregister_v1(const char* module_name);
size_t deherm_native_module_provider_count_v1(void);
int32_t deherm_native_module_copy_provider_v1(size_t index, DehermNativeModuleProviderV1* provider_out);
int32_t deherm_native_module_resolve_v1(const char* module_name, uint32_t module_abi_version, DehermNativeModuleProviderV1* provider_out);
#ifdef __cplusplus
}  // extern "C"
#endif
#endif
